AUGREL/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record Type for Dealer Account</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master-Detail Relationship to dealership (Account)</description>
        <label>Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Latest Title on the Financial Account</description>
        <label>Title</label>
        <referenceTo>Title__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Customer_Full_Name__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to concatenate the proper name field components from the related account object so the customer may be addressed by their full name in a letter or other communication.</description>
        <formula>IF(Account__r.IsPersonAccount,
  IF(!ISBLANK(TEXT(Account__r.Salutation)), TEXT(Account__r.Salutation) &amp; &quot; &quot;, &quot;&quot;) &amp;
  IF(!ISBLANK(Account__r.FirstName), Account__r.FirstName &amp; &quot; &quot;, &quot;&quot;) &amp;
  IF(!ISBLANK(Account__r.Middle_Name__pc), Account__r.Middle_Name__pc &amp; &quot; &quot;, &quot;&quot;) &amp;
  Account__r.LastName &amp;
  IF(!ISBLANK(Account__r.Name_Suffix__pc), &quot;, &quot; &amp; Account__r.Name_Suffix__pc, &quot;&quot;)
,
  Account__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to determine the appropriate mailing city for a customer based on whether the account is a retail or lease and if it&apos;s a lease, whether the alternate billing address information is used.</description>
        <formula>IF(Financial_Account__r.RecordType.Name = &quot;Lease&quot; &amp;&amp; !ISBLANK(Mailing_City_BillTo__c), 
Mailing_City_BillTo__c, 
Mailing_City_Garage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mailing City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country_Code_Garage__c</fullName>
        <label>Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>Mailing Country Code Garage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to determine the appropriate mailing state for a customer based on whether the account is a retail or lease and if it&apos;s a lease, whether the alternate billing address information is used.</description>
        <formula>IF(Financial_Account__r.RecordType.Name = &quot;Lease&quot; &amp;&amp; !ISBLANK(Mailing_City_BillTo__c), 
TEXT(Mailing_State_BillTo__c),
TEXT(Mailing_State_Garage__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mailing State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street1__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to determine the appropriate mailing street first line for a customer based on whether the account is a retail or lease and if it&apos;s a lease, whether the alternate billing address information is used.</description>
        <formula>IF(Financial_Account__r.RecordType.Name = &quot;Lease&quot; &amp;&amp; !ISBLANK(Mailing_City_BillTo__c)
,
IF(FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_BillTo__c) = 0, Mailing_Street_BillTo__c, LEFT(Mailing_Street_BillTo__c, FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_BillTo__c) - 1))
,
IF(FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_Garage__c) = 0, Mailing_Street_Garage__c, LEFT(Mailing_Street_Garage__c, FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_Garage__c) - 1))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mailing Street1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street2__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to determine the appropriate mailing second street line for a customer based on whether the account is a retail or lease and if it&apos;s a lease, whether the alternate billing address information is used.</description>
        <formula>IF(Financial_Account__r.RecordType.Name = &quot;Lease&quot; &amp;&amp; !ISBLANK(Mailing_City_BillTo__c)
,
IF(FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_BillTo__c) = 0, &quot;&quot;, RIGHT(Mailing_Street_BillTo__c, LEN(Mailing_Street_BillTo__c) - FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_BillTo__c)))
,
IF(FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_Garage__c) = 0, &quot;&quot;, RIGHT(Mailing_Street_Garage__c, LEN(Mailing_Street_Garage__c) - FIND(SUBSTITUTE($Label.LineBreak, &quot;-&quot;, &quot;&quot;), Mailing_Street_Garage__c)))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mailing Street2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to determine the appropriate mailing zip code for a customer based on whether the account is a retail or lease and if it&apos;s a lease, whether the alternate billing address information is used.</description>
        <formula>IF(Financial_Account__r.RecordType.Name = &quot;Lease&quot; &amp;&amp; !ISBLANK(Mailing_City_BillTo__c), 
Mailing_PostalCode_BillTo__c &amp; IF(!ISBLANK(Billing_Zip_Code_Extn__c), &quot;-&quot; &amp; Billing_Zip_Code_Extn__c, &quot;&quot;) 
, 
Mailing_Postal_Code_Garage__c &amp; IF(!ISBLANK(Garage_Zip_Code_Extn__c), &quot;-&quot; &amp; Garage_Zip_Code_Extn__c, &quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mailing Zip</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Title__c.object
<CustomObject>
    <description>This object contains Title info. It will be related to the  FA.</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FA Account that this Title record belongs to</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_To__c</fullName>
        <description>Option to whom the Title should be send to</description>
        <label>Send To</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Originating Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Title</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/UC_NewCase_SendTo.cls
/**
	* UC_NewCase_SendTo - Helper class for NewCaseController for Send To and Title Release date functionality
	* @author: Clayton Bruckert
	* @version: 1.0
*/

public with sharing class UC_NewCase_SendTo{
    private String Borrower = 'Customer';//11'0-Primary Borrower';
    private String CoBorrower = 'Co-Signer';//'6-Co-Borrower';
    private String OrigDealer = 'Originating Dealer';
    private String Third_Party = '3rd Party';

	Case thisCase;
	Financial_Account_Customer__c thisPrimaryBorrower;
	Financial_Account_Customer__c thisCoBorrower;
	Financial_Account__c thisFA;
	Title__c thisTitle;
	
	public UC_NewCase_SendTo(Case UseCase, Financial_Account_Customer__c UsePrimaryBorrower, Financial_Account_Customer__c UseCoBorrower, Financial_Account__c UseFA){
		thisCase = UseCase;
		if(UsePrimaryBorrower==null){
			thisPrimaryBorrower = new Financial_Account_Customer__c();
		}else{
			thisPrimaryBorrower = UsePrimaryBorrower;	
		}
		if(UseCoBorrower==null){
			thisCoBorrower = new Financial_Account_Customer__c();
		}else{
			thisCoBorrower = UseCoBorrower;	
		}
		if(useFA == null){
			thisFA = new Financial_Account__c();
		}else{
			thisFA = UseFA;	
		}
		System.debug('current fa: '+thisFA);
	}
	
	public void FillAddress(){
        String NewAddress = '';
        System.debug('*** Evaluating: ThisCase.Send_To__c = '+ThisCase.Send_To__c);
        if(thisCase.Send_To__c == Borrower){
            System.debug('*** Entering borrower: '+thisPrimaryBorrower);
			if(thisPrimaryBorrower.id != null){
	            Financial_Account_Customer__c useFAC = [select Customer_Full_Name__c, Mailing_Street1__c, Mailing_Street2__c, Mailing_City__c, Mailing_State__c, Mailing_Zip__c, Mailing_Country_Code_Garage__c
	                        FROM Financial_Account_Customer__c 
	                        WHERE id =: thisPrimaryBorrower.id];
	            NewAddress = FormatAddress(useFAC);
			}
        }else if(thisCase.Send_To__c == 'Co-borrower'){
            System.debug('*** Entering Coborrower: '+thisCoBorrower);
			if(thisCoBorrower.id != null){
	            Financial_Account_Customer__c useFAC = [select Customer_Full_Name__c, Mailing_Street1__c, Mailing_Street2__c, Mailing_City__c, Mailing_State__c, Mailing_Zip__c, Mailing_Country_Code_Garage__c
	                        FROM Financial_Account_Customer__c 
	                        WHERE id =: thisCoBorrower.id];
	            NewAddress = FormatAddress(useFAC);				
			}
        }else if(ThisCase.Send_To__c == OrigDealer){
            System.debug('*** Entering Originating Dealer: '+thisFA);
			if(thisFA.id != null){
	            Account useDealer = [select name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry FROM account WHERE Id IN (SELECT Dealership__c FROM financial_account__c WHERE id =: thisFA.id) LIMIT 1];
	            if(useDealer != null) NewAddress = FormatAddress(useDealer);	
			}
        }else if(ThisCase.Send_To__c == Third_Party){
            System.debug('*** 3rd party');
            // as per Req we are handling this option
        }
        
        thisCase.Send_to_Name_Address__c = NewAddress;
         
    }
	
    private String FormatAddress(Financial_Account_Customer__c RelatedObj){
        String result = '';
        if(RelatedObj!=null){
	        result += RelatedObj.Customer_Full_Name__c == null ? '' : RelatedObj.Customer_Full_Name__c;
	        result += RelatedObj.Mailing_Street1__c == null ? '' : '\n' + RelatedObj.Mailing_Street1__c;
	        result += RelatedObj.Mailing_Street2__c == null ? '' : '\n' + RelatedObj.Mailing_Street2__c;
	        result += RelatedObj.Mailing_City__c == null ? ''    : '\n' + RelatedObj.Mailing_City__c;
	        result += RelatedObj.Mailing_State__c == null ? ''   : ', ' + RelatedObj.Mailing_State__c;
	        result += RelatedObj.Mailing_Zip__c == null ? ''     : '   ' + RelatedObj.Mailing_Zip__c;
	        result += RelatedObj.Mailing_Country_Code_Garage__c == null ? '' : '\n' + RelatedObj.Mailing_Country_Code_Garage__c;
		}
        System.debug('*** new address: ' + result);
        return result;
    }
    
    private String FormatAddress(Account RelatedObj){
        String result = '';
        if(RelatedObj!=null){
	        result += RelatedObj.Name == null ? '' : RelatedObj.Name;
	        result += RelatedObj.BillingStreet == null ? '' : '\n' + RelatedObj.BillingStreet;
	        result += RelatedObj.BillingCity == null ? ''    : '\n' + RelatedObj.BillingCity;
	        result += RelatedObj.BillingState == null ? ''   : ', ' + RelatedObj.BillingState;
	        result += RelatedObj.BillingPostalCode == null ? ''     : '   ' + RelatedObj.BillingPostalCode;
	        result += RelatedObj.BillingCountry == null ? '' : '\n' + RelatedObj.BillingCountry;
		}
        System.debug('*** new address: ' + result);     
        return result;
    }
    
}