AUGREL/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Tax Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Record Type for Branch Account</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <label>Model Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number_Last_8_Ch__c</fullName>
        <formula>TRIM(RIGHT(Vehicle_Identification_Number__c, 8))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle Identification Number Last 8 Ch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle Identification Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts (Branch)</relationshipLabel>
        <relationshipName>Financial_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Reversed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Collateral__r.Make__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Collateral__r.Model_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Collateral__r.Model_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Loan type of account</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code_Garage__c</fullName>
        <description>Zip Code</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Make__c</formula>
        <label>(IVR) Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Name__c</formula>
        <label>(IVR) Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Year__c</formula>
        <label>(IVR) Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Social_Security_Number__c</fullName>
        <formula>Account__r.Social_Security_Number__pc</formula>
        <label>(IVR) Social Security Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Identification_Number__c</fullName>
        <formula>Account__r.Tax_Identification_Number__c</formula>
        <label>(IVR) Tax Identification Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number_Last_8_Ch__c</fullName>
        <formula>TRIM(RIGHT(Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c, 8))</formula>
        <label>(IVR) Vehicle Identification Num Last8Ch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c</formula>
        <label>(IVR) Vehicle Identification Number</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/SfClosedAccount__x.object
<CustomObject>
    <description>SfClosedAccount</description>
    <externalDataSource>ODataService</externalDataSource>
    <externalName>SfClosedAccount</externalName>
    <fields>
        <fullName>accountClosedDate__c</fullName>
        <description>accountClosedDate</description>
        <externalDeveloperName>accountClosedDate</externalDeveloperName>
        <label>accountClosedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>accountType__c</fullName>
        <description>accountType</description>
        <externalDeveloperName>accountType</externalDeveloperName>
        <label>accountType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>branch__c</fullName>
        <description>branch</description>
        <externalDeveloperName>branch</externalDeveloperName>
        <label>branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>businessName__c</fullName>
        <description>businessName</description>
        <externalDeveloperName>businessName</externalDeveloperName>
        <label>businessName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>financialAccountNumber__c</fullName>
        <description>financialAccountNumber</description>
        <externalDeveloperName>financialAccountNumber</externalDeveloperName>
        <label>financialAccountNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>financialAccountStatus__c</fullName>
        <description>financialAccountStatus</description>
        <externalDeveloperName>financialAccountStatus</externalDeveloperName>
        <label>financialAccountStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>firstName__c</fullName>
        <description>firstName</description>
        <externalDeveloperName>firstName</externalDeveloperName>
        <label>firstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last8VinNumber__c</fullName>
        <description>last8VinNumber</description>
        <externalDeveloperName>last8VinNumber</externalDeveloperName>
        <label>last8VinNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lastName__c</fullName>
        <description>lastName</description>
        <externalDeveloperName>lastName</externalDeveloperName>
        <label>lastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>make__c</fullName>
        <description>make</description>
        <externalDeveloperName>make</externalDeveloperName>
        <label>make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>modelName__c</fullName>
        <description>modelName</description>
        <externalDeveloperName>modelName</externalDeveloperName>
        <label>modelName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>modelYear__c</fullName>
        <description>modelYear</description>
        <externalDeveloperName>modelYear</externalDeveloperName>
        <label>modelYear</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ssn__c</fullName>
        <description>ssn</description>
        <externalDeveloperName>ssn</externalDeveloperName>
        <label>ssn</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tin__c</fullName>
        <description>tin</description>
        <externalDeveloperName>tin</externalDeveloperName>
        <label>tin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vehicleIdentificationNumber__c</fullName>
        <description>vehicleIdentificationNumber</description>
        <externalDeveloperName>vehicleIdentificationNumber</externalDeveloperName>
        <label>vehicleIdentificationNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zipcode__c</fullName>
        <description>zipcode</description>
        <externalDeveloperName>zipcode</externalDeveloperName>
        <label>zipcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SfClosedAccount</label>
    <pluralLabel>SfClosedAccount</pluralLabel>
</CustomObject>

AUGREL/src/classes/TFSC_SearchController.cls
/**    
    * @author  Amanjot Purewal
        * @date 8/25/2015    
        * @description This class handles Custom Search Parameters and methods
     */ 

public with Sharing class TFSC_SearchController{
    // UI fields
    public String fANumber{get;set;}
    public String sSN{get;set;}
    public String tIN{get;set;}
    public String fName{get;set;}
    public String lName{get;set;}
    public String busiName{get;set;}
    public String garZip{get;set;}
    public String vINFull{get;set;}
    public String vIN8{get;set;}
    
    public String TestWSResponse;
    
    public Integer noOfFAC;
    public Integer noArchiveOfFAC {get;Set;}
    public Integer getnoOfFAC(){
        return noOfFAC;
    }
    public Integer noOfFA;
    public Integer getnoOfFA(){
        return noOfFA;
    }
    public String oneFAId;
    public String getoneFAId(){
        return oneFAId;
    }
    public String oneFANo;
    public String getoneFANo(){
        return oneFANo;
    }
    private String queryFilter='';
    private Integer resultLimit1 = 10;
    private Integer resultLimit2 = 50;
    public list<Financial_Account_Customer__c> searchedFACs{get;set;} 
    public list<SfClosedAccount__x> searchedArchivedFACs{get;set;} 
    public LIST<ArchiveSearchResult> ArchiveResults {get; Set;}
    

    public TFSC_SearchController(){
        searchedFACs = null;
        noOfFA=-1;
        TestWSResponse = 'Running Test';
    }
    public void reset(){        
        searchedFACs = null;
        searchedArchivedFACs= null;
    }

// create the dynamic query based on the User input parameters 
    public void searchFAC(){
        noOfFAC = -1;
        noOfFA = -1;
        oneFAId ='';
        oneFANo ='';
        
        PullActiveFAC();
        
        if(searchedFACs != null){       
            noOfFAC = searchedFACs.size();      
            Set <Id> uniqueSearchedFAs = new Set<Id>();
            for(Financial_Account_Customer__c fac : searchedFACs){// Check if search returns a unique FA (there may be multiple FAC but if they all belong to one FA), then auto pop the FA in console
                uniqueSearchedFAs.add(fac.Financial_Account__r.Id);
            }
            if(uniqueSearchedFAs !=null && uniqueSearchedFAs.size() == 1){
                noOfFA = 1; //No of Unique FAs
                oneFAId = searchedFACs.get(0).Financial_Account__r.Id;
                oneFANo  = searchedFACs.get(0).Financial_Account_Number__c;
            }
        }
        if(noOfFAC == 0 ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'No Records found for this search Criteria')); 
        }else if(noOfFAC > resultLimit2 ){
            searchedFACs.remove(50);//Remove the last result if more than 50 are returned.
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Your search returned more than 50 results. Not all results are displayed below. Enter additional criteria to refine your search.'));
        }else if(noOfFAC >= resultLimit1 ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please enter additional criteria to refine your search.'));
        }
    }
    public void SearchArchivedFAC(){
        noOfFAC = -1;
        noOfFA = -1;
        oneFAId ='';
        oneFANo ='';
        noArchiveOfFAC = -1;
        
        PullActiveFAC();
        PullArchivedFAC();
        
        // For search all we are not auto navigating to the FA
        if(searchedFACs != null){       
            noOfFAC = searchedFACs.size();      
        }
        if(searchedArchivedFACs != null){
            noArchiveOfFAC = searchedArchivedFACs.size();
        }
        if(noOfFAC == 0 && noArchiveOfFAC == 0){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'No Records found for this search Criteria')); 
        }
        if(noOfFAC > resultLimit2 ){
            searchedFACs.remove(50);//Remove the last result if more than 50 are returned.
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Your search returned more than 50 results. Not all results are displayed below. Enter additional criteria to refine your search.'));
        }
        if(noOfFAC >= resultLimit1 ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please enter additional criteria to refine your search.'));
        }
        if(noArchiveOfFAC > resultLimit2 ){
            searchedArchivedFACs.remove(50);//Remove the last result if more than 50 are returned.
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Your search returned more than 50 results. Not all results are displayed below. Enter additional criteria to refine your search.'));
        }
        if(noArchiveOfFAC >= resultLimit1 ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please enter additional criteria to refine your search.'));
        }
    }
    // if an archived FA is chosen the following steps are needed:
    // 1) Check if FA exists in SFDC
    // 2) if not Tibco_ws_SendFARequest.SendRequest('0016142681'{fa Num},Dt {account closed date},'034'{account branch},'Retail'{acct type});
    // 2a) verify that FA now exists and then open
    // 3) if so open the FA
    public void createFAFromArchive(){
        System.debug('**** looking to create the FA from Archive');
        String sArchiveFANum = Apexpages.currentPage().getParameters().get('ArchiveFANum');
        datetime dtAccountClosedDate = null;
        if(Apexpages.currentPage().getParameters().get('AccountClosedDate')!=''){
            dtAccountClosedDate = datetime.parse(Apexpages.currentPage().getParameters().get('AccountClosedDate'));
        }
        String sAccountBranch = Apexpages.currentPage().getParameters().get('AccountBranch');
        String sAccountType = Apexpages.currentPage().getParameters().get('AccountType');
        
        if(sArchiveFANum != ''){
            LIST<Financial_Account__c> existingFA = [select id from Financial_Account__c where Financial_Account_Number__c=:sArchiveFANum];
            if(existingFA.size()>0){
                System.debug('**** the FA Num: '+sArchiveFANum);
                noOfFA = 1; //No of Unique FAs
                oneFAId = existingFA.get(0).Id;
                oneFANo = sArchiveFANum;                
            }else{
                System.debug('**** Time to pull from tape back-up');
                String CalloutResult = CallOutTibco_ws_SendFARequest(sArchiveFANum, dtAccountClosedDate, sAccountBranch, sAccountType);
                if(CalloutResult=='SUCCESS'){
                    LIST<Financial_Account__c> newFA = [select id, Financial_Account_Number__c from Financial_Account__c where Financial_Account_Number__c=:sArchiveFANum];
                    if(newFA.size()>0){
                        System.debug('**** the FA Num: '+newFA.get(0).Financial_Account_Number__c);
                        noOfFA = 1;
                        oneFAId = newFA.get(0).id;
                        oneFANo = newFA.get(0).Financial_Account_Number__c;
                    }
                }else{
                    // display any error messages
                    String message = '';
                    if(CalloutResult=='NO_DATA_FOUND'){
                        message='No FA found or No FAC found';
                    }else if(CalloutResult=='ERROR'){
                        message='Technical Error';
                    }else{
                        message='Error attempting retrieve the FA and FAC: '+CalloutResult;
                    }
                    System.debug('**** Unable to pull record: '+CalloutResult);
                    ApexPages.Message WSErr = new ApexPages.message(ApexPages.severity.error, message);
                    ApexPages.addmessage(WSErr);
                }
            }
        }
    }
    
    private void PullActiveFAC(){
        
        try{
            searchedFACs = (List<Financial_Account_Customer__c>)Database.Query(ActiveFAQuery());            
        }catch(QueryException se){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,se.getMessage()));
        }       
    }
    private void PullArchivedFAC(){
        try{
            ArchiveResults = new LIST<ArchiveSearchResult>();
            String ArcSOQL = ArchiveFAQuery();
            if(!Test.isRunningTest()){
                System.debug('**** searching archive');
                searchedArchivedFACs = (List<SfClosedAccount__x>)Database.Query(ArcSOQL);
                for(SfClosedAccount__x ca: searchedArchivedFACs){
                    Datetime acctCloseDate;
                    if(ca.accountClosedDate__c != null){
                        acctCloseDate = ca.accountClosedDate__c;
                    }else{
                        acctCloseDate = Datetime.now();
                    }
                    ArchiveResults.add(new ArchiveSearchResult(
                                ca.accountType__c,
                                ca.branch__c, 
                                acctCloseDate.format(), 
                                ca.businessName__c, 
                                ca.financialAccountNumber__c, 
                                ca.financialAccountStatus__c, 
                                ca.firstName__c, 
                                string.valueOf(ca.Id), 
                                ca.last8VinNumber__c, 
                                ca.lastName__c, 
                                ca.make__c, 
                                ca.modelName__c, 
                                ca.modelYear__c, 
                                ca.ssn__c, 
                                ca.tin__c, 
                                ca.vehicleIdentificationNumber__c, 
                                ca.zipcode__c
                                ));
                }
            }else{
                ArchiveResults.add(new ArchiveSearchResult(
                            '',
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            '', 
                            ''
                            ));
            }
        }catch(Exception se){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Unable to connect with external object. please try again later'));
        }
    }
    
    
    private String ActiveFAQuery(){
        String queryFilter = '';
        String selectFields = 'SELECT Id, Account__r.FirstName, Account__r.LastName, Account__r.Name, Account__r.IsPersonAccount, Vehicle_Identification_Number__c,Financial_Account__r.Collateral__r.Vehicle_Identification_Number_Last_8_Ch__c,Model_Year__c,Make__c,Model_Name__c,Mailing_Postal_Code_Garage__c,Financial_Account_Number__c,Social_Security_Number__c,Tax_Identification_Number__c,Financial_Account__r.Id,Financial_Account__r.Finance_Account_Status__c FROM Financial_Account_Customer__c';
        String queryOrder = 'Account__r.Name , Mailing_Postal_Code_Garage__c,Financial_Account_Number__c '; // Order By fields
        String queryLimit = '51';//Put the max number of records limit here  
        
        if(TFSC_Utils.isNotNullAndNotEmpty(fANumber)){
            fANumber=fANumber.replaceAll(' ','');
            fANumber = fANumber.trim().toUpperCase();
            if(fANumber.length() == 10 || fANumber.length() == 11 ){
                queryFilter = queryFilter + ' Financial_Account__r.Financial_Account_Number__c =\''+String.escapeSingleQuotes(fANumber)+'\' AND';
            }else if(fANumber.length() == 20 ){  
                if(fANumber.startsWith('000704') && fANumber.endsWith('0001') ){
                    fANumber = fANumber.substring(6,16);
                }else if(fANumber.startsWith('0000000000')){            
                    fANumber = fANumber.substring(10,12)+'0'+fANumber.substring(12,20);
                }
                queryFilter = queryFilter + ' Financial_Account__r.Financial_Account_Number__c =\''+String.escapeSingleQuotes(fANumber)+'\' AND';
            }
        }    
        if(TFSC_Utils.isNotNullAndNotEmpty(sSN)){
                queryFilter = queryFilter +' Social_Security_Number__c =\''+String.escapeSingleQuotes(sSN)+'\' AND' ;
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(tIN)){
                
               queryFilter = queryFilter + ' Tax_Identification_Number__c =\''+String.escapeSingleQuotes(tIN)+'\' AND' ;
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(lName)){
             lName=lName.trim();
             lName=lName.toUpperCase();
             queryFilter = queryFilter + ' Account__r.LastName =\''+String.escapeSingleQuotes(lName)+'\' AND';
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(fName)) {
                    fName=fName.trim();
                    fName=fName.toUpperCase();
                    queryFilter = queryFilter + ' Account__r.FirstName LIKE \''+String.escapeSingleQuotes(fName)+'%\' AND';
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(garZip)){
                queryFilter = queryFilter + ' Mailing_Postal_Code_Garage__c =\''+String.escapeSingleQuotes(garZip)+'\' AND' ;
        }    
        if(TFSC_Utils.isNotNullAndNotEmpty(busiName)){
                queryFilter = queryFilter + ' Account__r.Name LIKE \''+String.escapeSingleQuotes(busiName)+'%\' AND  Account__r.RecordType.Name =\'Business Account\' AND';       
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(vINFull)){
                vINFull=vINFull.replaceAll(' ','');
                vINFull = vINFull.toUpperCase();
                queryFilter = queryFilter + ' Vehicle_Identification_Number__c =\''+String.escapeSingleQuotes(vINFull)+'\' AND' ;
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(vIN8)){
                vIN8 =vIN8.replaceAll(' ','');
                vIN8 = vIN8.toUpperCase();
                queryFilter = queryFilter +' Financial_Account__r.Collateral__r.Vehicle_Identification_Number_Last_8_Ch__c =\''+String.escapeSingleQuotes(vIN8)+'\' AND' ;
        }    
        if(queryFilter.endsWith('AND')){    
            queryFilter = queryFilter.Substring(0,queryFilter.length()-4);//Remove the last "AND" from query String
        }
        return selectFields+' WHERE '+queryFilter+' ORDER BY '+queryOrder+' LIMIT '+queryLimit ;
    }
    private String ArchiveFAQuery(){
        String queryFilter = '';
        String selectFields = 'Select accountType__c, branch__c, accountClosedDate__c, businessName__c, financialAccountNumber__c, financialAccountStatus__c, firstName__c, Id, last8VinNumber__c, lastName__c, make__c, modelName__c, modelYear__c, ssn__c, tin__c, vehicleIdentificationNumber__c, zipcode__c from SfClosedAccount__x';
        String queryOrder = 'businessName__c , zipcode__c, financialAccountNumber__c '; // Order By fields
        String queryLimit = '51';//Put the max number of records limit here  
        
        if(TFSC_Utils.isNotNullAndNotEmpty(fANumber)){
            fANumber = fANumber.toUpperCase();
            if(fANumber.length() == 10 || fANumber.length() == 11 ){
                queryFilter = queryFilter + ' financialAccountNumber__c =\''+String.escapeSingleQuotes(fANumber)+'\' AND';
            }else if(fANumber.length() == 20 ){  
                if(fANumber.startsWith('000704') && fANumber.endsWith('0001') ){
                    fANumber = fANumber.substring(6,16);
                }else if(fANumber.startsWith('0000000000')){            
                    fANumber = fANumber.substring(10,12)+'0'+fANumber.substring(12,20);
                }
                queryFilter = queryFilter + ' financialAccountNumber__c =\''+String.escapeSingleQuotes(fANumber)+'\' AND';
            }
        }           
        if(TFSC_Utils.isNotNullAndNotEmpty(sSN)){
                queryFilter = queryFilter +' ssn__c =\''+String.escapeSingleQuotes(sSN)+'\' AND' ;
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(tIN)){
               queryFilter = queryFilter + ' tin__c =\''+String.escapeSingleQuotes(tIN)+'\' AND' ;
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(lName)){
            queryFilter = queryFilter + ' lastName__c =\''+String.escapeSingleQuotes(lName)+'\' AND';
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(fName)) {
                    queryFilter = queryFilter + ' firstName__c LIKE \''+String.escapeSingleQuotes(fName)+'%\' AND';
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(garZip)){
                queryFilter = queryFilter + ' zipcode__c =\''+String.escapeSingleQuotes(garZip)+'\' AND' ;
        }    
        if(TFSC_Utils.isNotNullAndNotEmpty(busiName)){
                queryFilter = queryFilter + ' businessName__c LIKE \''+String.escapeSingleQuotes(busiName)+'%\' AND  accountType__c =\'Business Account\' AND';       
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(vINFull)){
                vINFull = vINFull.toUpperCase();
                queryFilter = queryFilter + ' vehicleIdentificationNumber__c =\''+String.escapeSingleQuotes(vINFull)+'\' AND' ;
        }
        if(TFSC_Utils.isNotNullAndNotEmpty(vIN8)){
                vIN8 = vIN8.toUpperCase();
                queryFilter = queryFilter +' last8VinNumber__c =\''+String.escapeSingleQuotes(vIN8)+'\' AND' ;
        }    
        
        if(queryFilter.endsWith('AND')){    
            queryFilter = queryFilter.Substring(0,queryFilter.length()-4);//Remove the last "AND" from query String
        }
        //queryFilter = 'financialaccountnumber__c = ';
        System.debug('**** the archive query: '+selectFields+' WHERE '+queryFilter+' ORDER BY '+queryOrder+' LIMIT '+queryLimit);
        return selectFields+' WHERE '+queryFilter+' ORDER BY '+queryOrder+' LIMIT '+queryLimit ;
    }
    
    public String CallOutTibco_ws_SendFARequest(String archiveFANum, DateTime ClosedDate, String AcctBranch, String AcctType){
        string strResult = '';
        if(!Test.isRunningTest()){
            strResult = Tibco_ws_SendFARequest.SendRequest(archiveFANum, ClosedDate, AcctBranch, AcctType);
        }else{
            strResult=TestWSResponse;
        }
        return strResult;
    }
    
    public class ArchiveSearchResult{
        //Select accountType__c, branch__c, accountClosedDate__c, businessName__c, financialAccountNumber__c, financialAccountStatus__c, firstName__c, Id, last8VinNumber__c, lastName__c, make__c, modelName__c, modelYear__c, ssn__c, tin__c, vehicleIdentificationNumber__c, zipcode__c
        public String accountType {get; set;}
        public String branch {get; set;} 
        public String accountClosedDate {get; set;} 
        public String businessName {get; set;} 
        public String financialAccountNumber {get; set;} 
        public String financialAccountStatus {get; set;} 
        public String firstName {get; set;} 
        public String Id {get; set;} 
        public String last8VinNumber {get; set;} 
        public String lastName {get; set;} 
        public String make {get; set;} 
        public String modelName {get; set;} 
        public String modelYear {get; set;} 
        public String ssn {get; set;} 
        public String tin {get; set;} 
        public String vehicleIdentificationNumber {get; set;} 
        public String zipcode {get; set;}
        
        public ArchiveSearchResult(
                    String useaccountType,
                    String usebranch, 
                    String useaccountClosedDate, 
                    String usebusinessName, 
                    String usefinancialAccountNumber, 
                    String usefinancialAccountStatus, 
                    String usefirstName, 
                    String useId, 
                    String uselast8VinNumber, 
                    String uselastName, 
                    String usemake, 
                    String usemodelName, 
                    String usemodelYear, 
                    String usessn, 
                    String usetin, 
                    String usevehicleIdentificationNumber, 
                    String usezipcode){
            accountType = useaccountType;
            branch = usebranch; 
            accountClosedDate = useaccountClosedDate; 
            if(usebusinessName == null){
                businessName = usefirstName + ' ' + uselastName; 
            }else{
                businessName = usebusinessName; 
            }
            financialAccountNumber = usefinancialAccountNumber; 
            financialAccountStatus = usefinancialAccountStatus; 
            firstName = usefirstName; 
            Id = useId; 
            last8VinNumber = uselast8VinNumber; 
            lastName = uselastName; 
            make = usemake; 
            modelName = usemodelName; 
            modelYear = usemodelYear; 
            ssn = usessn; 
            tin = usetin; 
            vehicleIdentificationNumber = usevehicleIdentificationNumber; 
            zipcode = usezipcode;               
        }
    }
}