AUGREL/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Universal_Customer_Id__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>Universal Customer Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

AUGREL/src/objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>CustomString4__c</fullName>
        <label>CustomString4</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Year__c</fullName>
        <label>Vehicle Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Charges_Late__c</fullName>
        <description>Late charges</description>
        <label>Late Charge Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Account_Number__c</fullName>
        <description>***Populated by a workflow rule*** 

Contains the Exchange formatted account number.</description>
        <label>Exchange Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Collateral__r.Model_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payoff_Amount_Gross__c</fullName>
        <description>payoff amount (Lease - gross)</description>
        <label>Payoff Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Election_Language_Preference__c</fullName>
        <label>Language Preference</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doc Trans May Be Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Year__c</formula>
        <label>(IVR) Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Universal_Customer_Id__c</fullName>
        <label>Universal Customer Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <fields>
        <fullName>Form_Number__c</fullName>
        <label>Form Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field__c.object
<CustomObject>
    <description>Represents fields that appear on forms in the Adobe Forms Service. The columns identify source objects and fields, the target field on Document Request, and special processing instructions.</description>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Forms_QueryConfig__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forms_QueryConfig</label>
        <referenceTo>Forms_QueryConfig__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>ALFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOGIC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The target field on the document request record or line item where the data will be stored.</description>
        <label>Target Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field_Junction__c.object
<CustomObject>
    <description>Junction object linking Forms with their Form Fields and supporting re-use of fields across forms.</description>
    <fields>
        <fullName>Form_Field__c</fullName>
        <label>Form Field</label>
        <referenceTo>Form_Field__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form-Field Junction</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Form-Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Field Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Request__c.object
<CustomObject>
    <fields>
        <fullName>Form_Number__c</fullName>
        <label>Form Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Form Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Form Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_LogicConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Logic_Condition__c</fullName>
        <label>Logic Condition</label>
        <picklist>
            <picklistValues>
                <fullName>IF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referecen_Attribute__c</fullName>
        <description>This field will be used as input for logic</description>
        <label>Referecen Attribute</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value__c</fullName>
        <label>value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Forms Logic Configuration</label>
    <nameField>
        <label>Forms_LogicConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Logic Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_QueryConfig__c.object
<CustomObject>
    <description>Forms_QueryConfig for SourceSystem=&apos;SFDC&apos; in Form_Field__c</description>
    <fields>
        <fullName>Complex_Query__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complex Query</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DataType__c</fullName>
        <label>DataType</label>
        <picklist>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Object_Field__c</fullName>
        <label>Document_Object_Field</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_APIName__c</fullName>
        <label>Field_APIName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Field__c</fullName>
        <label>Filter Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_ApiName__c</fullName>
        <label>Object_ApiName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferenceAttribute__c</fullName>
        <label>ReferenceAttribute</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>Forms Query Configuration</label>
    <nameField>
        <label>QueryConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Query Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_DataAggregatorTest.cls
/*
#########################################################################################
Project Name..........: TFS Forms Implementation
File..................: <Forms_DataAggregatorTest> 
Version...............: <1.0>
Created by............: INFOSYS TECHNOLOGIES
Created Date..........: <10/16/2015> 
Last Modified by......: <thenmozhi>
Last Modified Date....: <11/27/2015 >
Description...........: <This test class has been written covering code for Forms_DataAggregator class for SFDC data>

Change Request History:
thenmozhi       27/11/2015   Added assertequals statement
##########################################################################################
 */
 @isTest 
private class Forms_DataAggregatorTest {
    public static String loadQuoteXML;
    public static String loadAssetXML;
    
     static testmethod void constructQueryNullTest(){
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
        dataAggregator.constructQuery(null,null);
    }
  
   /*
      Method Name:createRecords
      Method Signature/Inputs:Forms_TestDataUtil.insertForm('2000');
      Method Return Type/outputs: Inserting records
      Method Description:This method is used to insert test data for the desired object
     */
       static void createRecords(){
        
        Forms_TestDataUtil.insertFormFieldsForRequest();
        Forms_TestDataUtil.insertFormFieldsForALFAandSFDC();//TC_144 
        
       // Forms_EffectiveState__c effectiveState = new Forms_EffectiveState__c();
        //effectiveState.State_Code__c = 'CA';
       // effectiveState.State_Name__c = 'California';
        //insert effectiveState;
        
        Collateral__c collateral = new Collateral__c();
        collateral.Model_year__c='2016';
        insert collateral;
        
        Financial_Account__c financialAccount = new Financial_Account__c();
        financialAccount.Name = 'John Doe';
        financialAccount.Financial_Account_Number__c = '111111111';
        financialAccount.Charges_Late__c = 10000;
        financialAccount.Payoff_Amount_Gross__c = 20000;
        financialAccount.Exchange_Account_Number__c = '5000';
        financialAccount.collateral__C =collateral.id; 
        Insert financialAccount;
        
        Contact contactObj = new Contact();
        contactObj.FirstName = 'John';
        contactObj.LastName ='Doe';
        contactObj.Phone = '9999988888';
        Insert contactObj;
    }
    /*
      Method Name: dataAggregator
      Method Signature/Inputs:createRecords() method is input
      Method Return Type/outputs: output map for SFDC data
      Method Description:This method is used to check the code coverage for FORMS_DataAggegator class sucess scenario 
    */
     static testMethod void dataAggregator(){
         Form__c form = Forms_TestDataUtil.insertForm('2000');
        createRecords();
        Map<String, String> inputMap = new Map<String, String>();
        inputMap.put('accountnumber', '111111111');
        inputMap.put('formnumber', '2000');
        inputMap.put('formtype', 'Automated');
        inputMap.put('dispatchmode', 'Fax');
        inputMap.put('effectivestatecode', 'CA');
        inputMap.put('name', 'John Doe');
        
        Forms_QueryConfig__c queryConfig = new Forms_QueryConfig__c();
        queryConfig.Complex_Query__c = true;
        queryConfig.DataType__c = 'String';
        queryConfig.Document_Object_Field__c = 'Language__c';
        queryConfig.Field_APIName__c = 'Election_language_Preference__c';
        queryConfig.Filter_Field__c = '';
        queryConfig.Object_ApiName__c = '';
        queryConfig.Query__c = 'Select  Election_Language_Preference__c  from financial_Account_customer__c where Financial_Account__r.Financial_Account_Number__c=? and Account__r.Universal_Customer_Id__c=?';
        queryConfig.ReferenceAttribute__c = 'String-accountnumber:String-externalid';
        insert queryConfig;
        
        Forms_QueryConfig__c queryConfig1 = new Forms_QueryConfig__c();
        queryConfig1.Complex_Query__c = false;
        queryConfig1.DataType__c = 'Integer';
        queryConfig1.Document_Object_Field__c = 'Vehicle_Year__c';
        queryConfig1.Field_APIName__c = 'Collateral__r.Model_Year__c';
        queryConfig1.Filter_Field__c = 'Financial_Account_Number__c';
        queryConfig1.Object_ApiName__c = 'Financial_Account__c';        
        queryConfig1.ReferenceAttribute__c = 'accountnumber';
        insert queryConfig1;
        
        Form_Field__c formField = new Form_Field__c();
        formField.Data_Type__c = 'String';
        formField.Name = 'Language';
        formField.Target_Field__c = 'Language__C';
        formField.Source_System__c = 'SFDC';        
        formField.Forms_QueryConfig__c = queryConfig.Id;
        insert formField;
        
        Form_Field__c formField1 = new Form_Field__c();
        formField1.Data_Type__c = 'Integer';
        formField1.Name = 'VehicleYear';
        formField1.Target_Field__c = 'Vehicle_Year__c';
        formField1.Source_System__c = 'SFDC';        
        formField1.Forms_QueryConfig__c = queryConfig1.Id;
        insert formField1;
        
        Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
        formFieldJunction.Form__c = form.Id;
        formFieldJunction.Form_Field__c = formField.Id;
        insert formFieldJunction;
        
        Form_Field_Junction__c formFieldJunction1 = new Form_Field_Junction__c();
        formFieldJunction1.Form__c = form.Id;
        formFieldJunction1.Form_Field__c = formField1.Id;
        insert formFieldJunction1;
        
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
        Map<String, String> outputMap = dataAggregator.queryForLookupData('2000',inputMap);//TC_141
        system.debug('::outputMap::'+json.serialize(outputMap));
        system.debug('::outputMap1::'+outputMap.containsKey('effectivestatename')+ 'Calii'+outputMap.get('accountnumber'));
        //system.assertequals(outputMap.containsKey('effectivestatename'),false);//TC_142
        //system.assertequals(outputMap.get('CustomString4__c'),'CA');
        
        Forms_DataAggregator dataAggregator1= new Forms_DataAggregator();
        
        //system.assertequals(outputMap.get('latechargedue'),'10000.00');
    }
     /*
      Method Name: dataAggregatorFailure
      Method Signature/Inputs:createRecords() method is input
      Method Return Type/outputs: output map for SFDC data
      Method Description:This method is used to check the code coverage for FORMS_DataAggegator class Failure scenario 
    */
    static testMethod void dataAggregatorFailure(){
    Form__c form = Forms_TestDataUtil.insertForm('2000');
        createRecords();
        Map<String, String> inputMap = new Map<String, String>();
        inputMap.put('accountnumber', '111111111');
        inputMap.put('formnumber', '2000');
        inputMap.put('formtype', 'Automated');
        inputMap.put('dispatchmode', 'Fax');
        inputMap.put('name', 'John');
        
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
         
        Map<String, String> outputMap = dataAggregator.queryForLookupData('2000',inputMap);
        system.assertequals(outputMap.containsKey('latechargedue'),false);//TC_142
    }
   /*
      Method Name: dataAggregatorWrongFormIdFailure
      Method Signature/Inputs:createRecords() method is input and wrong Form Id
      Method Return Type/outputs: output map for SFDC data
      Method Description:This method is used to check the code coverage for FORMS_DataAggegator class Failure scenario 
    */
    static testMethod void dataAggregatorWrongFormIdFailure(){
    Form__c form = Forms_TestDataUtil.insertForm('2000');
        createrecords();
        Map<String, String> inputMap = new Map<String, String>();
        
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
        inputMap.put('accountnumber', '111111111');
        inputMap.put('formnumber', '2000');
        inputMap.put('formtype', 'Automated');
        inputMap.put('dispatchmode', 'Fax');
        Map<String, String> outputMap = dataAggregator.queryForLookupData('2001',inputMap);//TC_143
        system.assertEquals(outputMap.size(), 0);
    }    
    
    Static testmethod void executeComplexQueryTest(){
    Form__c form = Forms_TestDataUtil.insertForm('2000');
        createRecords();
        Map<String, String> inputMap = new Map<String, String>();
        
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
        inputMap.put('accountnumber', '111111111');
        inputMap.put('formnumber', '2000');
        inputMap.put('formtype', 'Automated');
        inputMap.put('dispatchmode', 'Fax');
        List<Forms_QueryConfig__c> queryConfigList = new List<Forms_QueryConfig__c>();
        Forms_QueryConfig__c queryConfig = new Forms_QueryConfig__c();
        queryConfig.Complex_Query__c = true;
        queryConfig.DataType__c = 'String';
        queryConfig.Document_Object_Field__c = 'Language__c';
        queryConfig.Field_APIName__c = 'Election_language_Preference__c';
        queryConfig.Filter_Field__c = '';
        queryConfig.Object_ApiName__c = '';
        queryConfig.Query__c = 'Select  Election_Language_Preference__c  from financial_Account_customer__c where Financial_Account__r.Financial_Account_Number__c=? and Account__r.Universal_Customer_Id__c=?';
        queryConfig.ReferenceAttribute__c = 'String-accountnumber:String-externalid';
        insert queryConfig;
        

        
        queryConfigList.add(queryConfig);
                
        dataAggregator.executeComplexQuery(queryConfigList,inputMap);
        //
        }
        
        
    static testmethod void aggregateFormDataTest(){
   
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
        Form__c form = Forms_TestDataUtil.insertForm('3102IN');
        Form_Request__c formRequest = Forms_TestDataUtil.getValidFormRequest('3102IN');
        Document_Request__c docReq = Forms_TestDataUtil.getDocumentRequest('4015');
        Forms_DocumentDataHolder documentData = new Forms_DocumentDataHolder();
        documentData.setDocumentRequest(docReq);
        Map<String, String> inputMap = new Map<String, String>();
        inputMap.put('accountnumber', '111111111');
        inputMap.put('formnumber', '3102IN');
        inputMap.put('formtype', 'Automated');
        inputMap.put('dispatchmode', 'Fax');
        inputMap.put('netBilledType527', '100');
        inputMap.put('netBilledType53', '100');
        //for admin,addon,lateFees and other Charges
        inputMap.put('adminCharges', '100');
        inputMap.put('addOnCharges', '100');
        inputMap.put('otherCharges', '100');
         inputMap.put('lateFees', '100'); 

        dataAggregator.aggregateFormData(form,formRequest ,documentData ,inputMap);
        
        Forms_DataAggregator dataAggregator1= new Forms_DataAggregator();
        Form__c form1 = Forms_TestDataUtil.insertForm('6156');
        Form_Request__c formRequest1 = Forms_TestDataUtil.getValidFormRequest('6156');        
        inputMap.put('formnumber', '6156');        
        dataAggregator1.aggregateFormData(form1,formRequest1 ,documentData ,inputMap);
        
        Forms_DataAggregator dataAggregator2= new Forms_DataAggregator();
        Form__c form2 = Forms_TestDataUtil.insertForm('6153');
        Form_Request__c formRequest2 = Forms_TestDataUtil.getValidFormRequest('6153');        
        inputMap.put('formnumber', '6153');        
        dataAggregator2.aggregateFormData(form2,formRequest2 ,documentData ,inputMap);
        
        Forms_DataAggregator dataAggregator3= new Forms_DataAggregator();
        Form__c form3 = Forms_TestDataUtil.insertForm('6153MD');
        Form_Request__c formRequest3 = Forms_TestDataUtil.getValidFormRequest('6153MD');        
        inputMap.put('formnumber', '6153MD');        
        dataAggregator3.aggregateFormData(form3,formRequest3,documentData ,inputMap);
        
        Forms_DataAggregator dataAggregator4= new Forms_DataAggregator();
        Form__c form4 = Forms_TestDataUtil.insertForm('8051');
        Form_Request__c formRequest4 = Forms_TestDataUtil.getValidFormRequest('8051');        
        inputMap.put('formnumber', '8051');        
        dataAggregator4.aggregateFormData(form4,formRequest4,documentData ,inputMap);
        
        Forms_DataAggregator dataAggregator5= new Forms_DataAggregator();
        Form__c form5 = Forms_TestDataUtil.insertForm('8051OH');
        Form_Request__c formRequest5 = Forms_TestDataUtil.getValidFormRequest('8051OH');        
        inputMap.put('formnumber', '8051OH');        
        dataAggregator5.aggregateFormData(form5,formRequest5,documentData ,inputMap);
                   
        Forms_DataAggregator dataAggregator6= new Forms_DataAggregator();
        Form__c form6 = Forms_TestDataUtil.insertForm('8051WA');
        Form_Request__c formRequest6 = Forms_TestDataUtil.getValidFormRequest('8051WA');        
        inputMap.put('formnumber', '8051WA');        
        dataAggregator6.aggregateFormData(form6,formRequest6,documentData ,inputMap);
        
        
        Forms_DataAggregator dataAggregator7= new Forms_DataAggregator();
        Form__c form7 = Forms_TestDataUtil.insertForm('3385');
        Form_Request__c formRequest7 = Forms_TestDataUtil.getValidFormRequest('3385');        
        inputMap.put('formnumber', '3385');        
        dataAggregator7.aggregateFormData(form7,formRequest7,documentData ,inputMap);
        
        Forms_DataAggregator dataAggregator8= new Forms_DataAggregator();
        Form__c form8 = Forms_TestDataUtil.insertForm('600-01');
        Form_Request__c formRequest8 = Forms_TestDataUtil.getValidFormRequest('600-01');        
        inputMap.put('formnumber', '600-01');        
        dataAggregator8.aggregateFormData(form8,formRequest8,documentData ,inputMap);
        
        //testing 6029 form calculations
        Forms_DataAggregator dataAggregator9= new Forms_DataAggregator();
        Form__c form9 = Forms_TestDataUtil.insertForm('6029');
        Form_Request__c formRequest9 = Forms_TestDataUtil.getValidFormRequest('6029');        
        inputMap.put('formnumber', '6029');        
        dataAggregator9.aggregateFormData(form9,formRequest9,documentData ,inputMap);
        
        //testing 6015 Form calculations
        Forms_DataAggregator dataAggregator10= new Forms_DataAggregator();
        Form__c form10 = Forms_TestDataUtil.insertForm('6015');
        Form_Request__c formRequest10 = Forms_TestDataUtil.getValidFormRequest('6015');        
        inputMap.put('formnumber', '6015');
        inputMap.put('netBilledType527','100');
        inputMap.put('taxBilledType527','200');  
        inputMap.put('netBilledType531','100');
        inputMap.put('taxBilledType531','200'); 
        inputMap.put('charge','100');
        dataAggregator10.aggregateFormData(form10,formRequest10,documentData ,inputMap);
        
         //testing 4015MO Form calculations
        Forms_DataAggregator dataAggregator11= new Forms_DataAggregator();
        Form__c form11 = Forms_TestDataUtil.insertForm('4015MO');
        Form_Request__c formRequest11 = Forms_TestDataUtil.getValidFormRequest('4015MO');        
        inputMap.put('formnumber', '4015MO');
        inputMap.put('gross53','53');
        inputMap.put('gross505','505');  
        inputMap.put('gross502','502');
        inputMap.put('gross509','509');
        inputMap.put('gross527','527');     
        inputMap.put('gross531','531');
        inputMap.put('allGrossChargeTypes','1000');
        dataAggregator11.aggregateFormData(form11,formRequest11,documentData ,inputMap);
        
         //testing 4005ME Form calculations
        Forms_DataAggregator dataAggregator12= new Forms_DataAggregator();
        Form__c form12 = Forms_TestDataUtil.insertForm('4005ME');
        Form_Request__c formRequest12 = Forms_TestDataUtil.getValidFormRequest('4005ME');        
        inputMap.put('formnumber', '4005ME'); 
        inputMap.put('gross502','502');
        inputMap.put('gross509','509');
        inputMap.put('gross617','617');     
        inputMap.put('gross531','531');
        inputMap.put('gross527','527');
        inputMap.put('expense102','102');
        inputMap.put('expense104','104');
        inputMap.put('expense106','106');
        inputMap.put('expense100','100');
        inputMap.put('expense110','110');
        inputMap.put('expense112','112');
        inputMap.put('expense120','120');
        inputMap.put('expense122','122');
        
        dataAggregator12.aggregateFormData(form12,formRequest12,documentData ,inputMap);
        
        
       
        }
    static testmethod void testCalUnpaidGrossBalance(){
        
         //testing 4015 Form calculations
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
        Form__c form = Forms_TestDataUtil.insertForm('4015');
        Form_Request__c formRequest = Forms_TestDataUtil.getValidFormRequest('4015');
        Document_Request__c docReq = Forms_TestDataUtil.getDocumentRequest('4015');
        Forms_DocumentDataHolder documentData = new Forms_DocumentDataHolder();
        documentData.setDocumentRequest(docReq);
        Map<String,String> inputMap = new Map<String,String>();
        inputMap.put('formnumber', '4015');
        inputMap.put('netBilledType53','100');
        inputMap.put('taxBilledType53','200');  
        inputMap.put('netBilledType502','100');
        inputMap.put('taxBilledType502','200');
        inputMap.put('netBilledType505','100');
        inputMap.put('taxBilledType505','200');  
        inputMap.put('netBilledType509','100');
        inputMap.put('taxBilledType509','200');
        inputMap.put('netBilledType527','100');
        inputMap.put('taxBilledType527','200');  
        inputMap.put('netBilledType531','100');
        inputMap.put('taxBilledType531','200');
        inputMap.put('netBilledType529','100');
        inputMap.put('taxBilledType529','200');
        inputMap.put('currentpaymentdue','100');
        inputMap.put('SCHEDULEMISCTYPE','Test');
        inputMap.put('charge','100');
        Forms_ResponseDataHolder.setSingleNodeData(inputMap);
        dataAggregator.aggregateFormData(form,formRequest,documentData ,Forms_ResponseDataHolder.getSingleNodeData());                
    }
   // testing extra functionality
   Static testmethod void executeQueryTest(){
    Form__c form = Forms_TestDataUtil.insertForm('323-10');
        createRecords();
        Map<String, String> inputMap = new Map<String, String>();
        
        Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
        inputMap.put('accountnumber', '111111111');
        inputMap.put('formnumber', '323-10'); 
        inputMap.put('formtype', 'Automated');
        inputMap.put('dispatchmode', 'Fax');
        
        Forms_QueryConfig__c queryConfig = new Forms_QueryConfig__c();
        queryConfig.Complex_Query__c = false;
        queryConfig.DataType__c = 'String';
        queryConfig.Document_Object_Field__c = 'Language__c';
        queryConfig.Field_APIName__c = 'Election_language_Preference__c';
        queryConfig.Filter_Field__c = '';
        queryConfig.Object_ApiName__c = '';
        queryConfig.Query__c = 'Select  Election_Language_Preference__c from financial_Account_customer__c where Financial_Account__r.Financial_Account_Number__c=? and Account__r.Universal_Customer_Id__c=?';
        queryConfig.ReferenceAttribute__c = 'String-accountnumber:String-externalid';
        insert queryConfig;
        List<Forms_QueryConfig__c> queryConfigList = new List<Forms_QueryConfig__c>();
        queryConfigList.add(queryConfig);
        
        //queryConfig.Query__c
        dataAggregator.queryConfigkey='key1';
        dataAggregator.queryConfigvalue='value1';
        dataAggregator.sql='Select  Election_Language_Preference__c  from financial_Account_customer__c';
      //  dataAggregator.executeComplexQuery(queryConfigList,inputMap);
         List<sObject> sObjectResult = dataAggregator.executeQueryTogetRecords('Select  Election_Language_Preference__c from financial_Account_customer__c');
       
       //Testing new method 
       Map<String,String> dataMap = new Map <String,String>();
       Map<String,String> resultMap = new Map <String,String>(); 
       Document_Request__c docReq = Forms_TestDataUtil.getDocumentRequest('4015');
       Forms_DocumentDataHolder documentData = new Forms_DocumentDataHolder();
       documentData.setDocumentRequest(docReq);
       dataMap.put('formnumber','6029'); 
       Map<String,String> LogicdataMap1 = new Map<String,String>();                
       logicdataMap1  =  dataAggregator.aggregateLogicDate(dataMap, resultMap,documentData);   
        }
      Static testmethod void aggregateLogicDateTest(){
       Map<String,String> dataMap = new Map <String,String>();
       Map<String,String> resultMap = new Map <String,String>(); 
       dataMap.put('formnumber','4015'); 
       Map<String,String> LogicdataMap1 = new Map<String,String>();
       Forms_DataAggregator dataAggregator= new Forms_DataAggregator();
       Document_Request__c docReq = Forms_TestDataUtil.getDocumentRequest('4015');
       Forms_DocumentDataHolder documentData = new Forms_DocumentDataHolder();
       documentData.setDocumentRequest(docReq);
       Form__c frm1 =new Form__c();
       frm1.Name='Automatic';
       frm1.Form_Number__c='4015';
       insert frm1;
       Forms_LogicConfiguration__c logicConfig = new Forms_LogicConfiguration__c();
       logicConfig.Name='LogicTest';
       logicConfig.Referecen_Attribute__c='productcode';
       logicConfig.Logic_Condition__c='IF';
       logicConfig.Operator__c='IN';
       logicConfig.value__c='BANK_700,BANK_800,RET_BAL_LN,RET_SIM_LN';
       dataMap.put('productcode','BANK_700');
       insert logicConfig;
       Form_Field__c frmField = new Form_Field__c();
       frmField.Name='Vehicle Model';
       frmField.Data_Type__c='String';
       frmField.Source_System__c='LOGIC';
       frmField.Forms_Logic_Config__c = logicConfig.Id;
       insert frmField;
       Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
       formFieldJunction.Form__c=frm1.Id;
       formFieldJunction.Form_Field__c=frmField.Id;
       insert formFieldJunction;  
         test.startTest();
           LogicdataMap1 = dataAggregator.aggregateLogicDate(dataMap,resultMap,documentData);
          test.stopTest();          
       }

}