AUGREL/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>External ID:
Dealer: Dealership number
Branch: City State Zip</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Universal_Customer_Id__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>Universal Customer Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <label>Model Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle Identification Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts (Branch)</relationshipLabel>
        <relationshipName>Financial_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code_Edit_Message__c</fullName>
        <description>Edit message code</description>
        <label>Code Edit Message</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Reversed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Collateral__r.Make__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Collateral__r.Model_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Latest Title on the Financial Account</description>
        <label>Title</label>
        <referenceTo>Title__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_Code_Description__c</fullName>
        <label>Type Code Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease type of account</description>
        <label>Lease</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Make__c</formula>
        <label>(IVR) Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Email__c</fullName>
        <description>Marketing Email Address</description>
        <label>Marketing Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Name__c</formula>
        <label>(IVR) Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Universal_Customer_Id__c</fullName>
        <label>Universal Customer Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c</formula>
        <label>(IVR) Vehicle Identification Number</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Title__c.object
<CustomObject>
    <description>This object contains Title info. It will be related to the  FA.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Collateral that is related to the FA</description>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FA Account that this Title record belongs to</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Reason__c</fullName>
        <description>Reason why the Title is being hold off</description>
        <label>Hold Reason</label>
        <picklist>
            <controllingField>Title_Status__c</controllingField>
            <picklistValues>
                <fullName>Band2 Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BK No Closing Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSG Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat/Rebook/SCRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Overpayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misapplied Pmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Acct-Title Not Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Contract/DMS Folder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No ODO/Missing Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Within Maturity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total Loss-Addr Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <description>ID from STARS/Siebel in which the Title was migrated from</description>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Status__c</fullName>
        <description>Depicts the status of the Title.</description>
        <label>Title Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending-Not Yet Received</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Title</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/UC_Account_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the icon and message displayed based on FinAcct Code_Edit_Message__c</description>
    <fields>
        <fullName>Icon__c</fullName>
        <description>Identifies the icon to display.</description>
        <inlineHelpText>Identifies the icon to display.</inlineHelpText>
        <label>Icon</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Message__c</fullName>
        <description>Message to display in hover in Salesforce.</description>
        <inlineHelpText>Message to display in hover in Salesforce.</inlineHelpText>
        <label>Salesforce Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UC Account Status</label>
</CustomObject>

AUGREL/src/classes/TFSC_WS_CreateClosedDemographicsV1Test.cls
@isTest
private class TFSC_WS_CreateClosedDemographicsV1Test {
	static Collateral__c collateral;
    
	static title__c t1;
	
	static Account acct;
    
    static Financial_Account__c fa;
    static Financial_Account_Customer__c fac ;
	
	static testMethod void myUnitTest() {
		createBaseData();
		LIST<account> testAcc = new LIST<account>();
		testAcc.add(acct);
		LIST<Title__c> testTitle = new LIST<Title__c>();
		testTitle.add(t1);
        
        Test.startTest();
        	
    	TFSC_WS_CreateClosedDemographicsV1.CreateUpdateDemographicsRequest req = new TFSC_WS_CreateClosedDemographicsV1.CreateUpdateDemographicsRequest(); 
		TFSC_WS_CreateClosedDemographicsV1.DemographicsAndCollateralDetails dcd = new TFSC_WS_CreateClosedDemographicsV1.DemographicsAndCollateralDetails();
		
		dcd.operation = TFSC_WS_CreateClosedDemographicsV1.operation.CREATE;
		dcd.financialAccount = fa;
		dcd.modifyFinancialAccount = false;
		dcd.financialAccountCustomer = fac;
		dcd.modifyFinancialAccountCustomer = false;
		dcd.collateral = collateral;
		dcd.modifyCollateral = false;
		LIST<TFSC_WS_CreateClosedDemographicsV1.DemographicsAndCollateralDetails> dcds = new list<TFSC_WS_CreateClosedDemographicsV1.DemographicsAndCollateralDetails>();
		dcds.add(dcd);
		
    	req.account = testAcc;
		req.title = testTitle;
		req.modifyAccount = false;
		req.demographicsAndCollateralDetails = dcds;
		
		System.debug('+*+*+ fac.Financial_Account__r.Financial_Account_Number__c: '+fac.Financial_Account__r.Financial_Account_Number__c);
		
        TFSC_WS_CreateClosedDemographicsV1.createUpdateDemographics(req);
            
        Test.stopTest();
	}
    static void createBaseData() {
		collateral = new Collateral__c(Name = '4T1BE32KX6U714628', Vehicle_Identification_Number__c = '4T1BE32KX6U714628', make__c = 'Toyota', model_name__c = 'camry');
		insert collateral;
		
       	t1 = new Title__c(title_status__c = 'Held', Hold_Reason__c = 'Band2 Review', collateral__c = collateral.id, Legacy_ID__c='1324');
      	insert t1;
      	
        Id acctRecordType = [select Id from recordtype where sObjectType = 'Account' and name = 'Customer' limit 1].Id;
      
      	acct = new Account(Account_Number__c='1234567890', Universal_Customer_Id__c='1234567890', firstName = 'John', lastName = 'Doe', recordTypeId = acctRecordType, Social_Security_Number__pc='123123123');
      	insert acct;
            
      	UC_Account_Status__c acctStatus = new UC_Account_Status__c(name='1000', Icon__c = 'Green', Salesforce_Message__c='test');
      	insert acctStatus;
      
      	Id faRecordTypeId = [select Id from recordType where sObjectType = 'Financial_Account__c' and name = 'Lease' limit 1].Id;
 
      	fa = new Financial_Account__c(name = 'FA', Title__c = t1.id, Finance_Account_Status__c = 'Open', Financial_Account_Number__c = '1234567890', Collateral__c = collateral.Id,
          	code_edit_message__c = '1000', branch__c = acct.Id, type_code_description__c = 'NotActuarial', RecordTypeId=faRecordTypeId);
      	insert fa;
		fa = [select name, Title__c, Finance_Account_Status__c, Financial_Account_Number__c, code_edit_message__c, branch__c, type_code_description__c, Collateral__r.Vehicle_Identification_Number__c, RecordTypeId from Financial_Account__c where name = 'FA'];
		
      	System.debug('*** the first FA: '+fa);
      
      	fac = new Financial_Account_Customer__c(name = 'FAC1000', financial_account__c = fa.id, account__c = acct.Id, Universal_Customer_Id__c = '1234567890',
            Customer_Role_Type__c = '0-Primary Borrower', Borrower_Position__c = 'Primary', Borrower_Status__c='ACTIVE', Marketing_Email__c = 'me@msn.com',
            financial_account_customer__c = '1234567890');            
              
      	insert fac; 
		fac = [select name, financial_account__c, account__c, Universal_Customer_Id__c, Financial_Account__r.Financial_Account_Number__c, Customer_Role_Type__c, Borrower_Position__c, Borrower_Status__c, Marketing_Email__c from financial_account_customer__c where name = 'FAC1000' LIMIT 1];
		
		System.debug('+*+*+ fac.Financial_Account__r.Financial_Account_Number__c: '+fac.Financial_Account__r.Financial_Account_Number__c);
    }
}