AUGREL/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Tax Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <label>Business Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <label>Model Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle Identification Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>CO_Host_Account_Number__c</fullName>
        <description>***Populated by a workflow rule*** 

Contains the CO Host formatted account number.</description>
        <label>CO Host Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_List_Number_1__c</fullName>
        <label>Collection List Number 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Reversed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>History_Counter_Days_Past_Due__c</fullName>
        <description>&quot;DPD</description>
        <label>Days Past Due</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>HomePhone BillTo</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Collateral__r.Make__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Collateral__r.Model_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Collateral__r.Model_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FA_Role_Status__c</fullName>
        <description>external ID -  Account No~Position~Status</description>
        <externalId>true</externalId>
        <label>FA Role Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Garage__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code_Garage__c</fullName>
        <description>Zip Code</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State_BillTo__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Make__c</formula>
        <label>(IVR) Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Number</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Name__c</formula>
        <label>(IVR) Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Year__c</formula>
        <label>(IVR) Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Identification_Number__c</fullName>
        <formula>Account__r.Tax_Identification_Number__c</formula>
        <label>(IVR) Tax Identification Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c</formula>
        <label>(IVR) Vehicle Identification Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Bill_To__c</fullName>
        <description>Work Phone Number</description>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Garage__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_SearchControllerTest.cls
@isTest
private class TFSC_SearchControllerTest {
    
   	static testmethod void positiveTest1() {
	    createBaseData();
	    TFSC_searchController cont = new TFSC_searchController();
	    //cont.TFSC_SearchController();
	    //Positive Scenario1
	    cont.fANumber = '00070411111111110001';
	    cont.sSN = '11111111';
	    cont.fName = 'FN';
	    cont.lName = 'LName';
	    cont.garZip = '11111';
	    cont.vINFull = '11111111111111111111';
	    cont.vIN8 = '11111111';
	    cont.searchFAC();
	    cont.reset();
	    Integer tempInt =  cont.getnoOfFAC();
	    tempInt =  cont.getnoOfFA();
	    String tempStr = cont.getoneFAId();
	    tempStr = cont.getoneFANo();
    }
   	static testmethod void positiveTest2() {
		createBaseData();
	    TFSC_searchController cont = new TFSC_searchController();
	    
	    cont.fANumber = '1111111111';
	    cont.tIN = '11111111';
	    cont.busiName = 'Business';
	    cont.lName = 'LName';
	    cont.garZip = '11111';
	    cont.vINFull = '11111111111111111111';
	    cont.vIN8 = '11111111';
	    cont.searchFAC();
	    cont.reset();
	    Integer tempInt =  cont.getnoOfFAC();
	    tempInt =  cont.getnoOfFA();
	    String tempStr = cont.getoneFAId();
	    tempStr = cont.getoneFANo();

	    cont.searchFAC();
    }
   	static testmethod void positiveTest3() {
		createBaseData();
	    TFSC_searchController cont = new TFSC_searchController();
	    
	    cont.fANumber = '00070412345678900001';
	    cont.tIN = '11111111';
	    cont.busiName = 'Business';
	    cont.lName = 'LName';
	    cont.garZip = '11111';
	    cont.vINFull = '11111111111111111111';
	    cont.vIN8 = '11111111';
	    cont.searchFAC();
		cont.SearchArchivedFAC();
	    cont.reset();
    }
   	static testmethod void positiveTest4() {
		createBaseData();
	    TFSC_searchController cont = new TFSC_searchController();
	    
	    cont.fANumber = '00000000001234567890';
	    cont.tIN = '11111111';
	    cont.busiName = 'Business';
	    cont.lName = 'LName';
	    cont.garZip = '11111';
	    cont.vINFull = '11111111111111111111';
	    cont.vIN8 = '11111111';
	    cont.searchFAC();
		cont.SearchArchivedFAC();
	    cont.reset();
    }
   	static testmethod void archiveQueryTest() {
	    createBaseData();
	    TFSC_searchController cont = new TFSC_searchController();
	    
	    cont.fANumber = '00070411111111110001';
	    cont.sSN = '11111111';
	    cont.fName = 'FN';
	    cont.lName = 'LName';
	    cont.garZip = '11111';
	    cont.vINFull = '11111111111111111111';
	    cont.vIN8 = '11111111';
	    cont.TestWSResponse = 'SUCCESS';

		cont.SearchArchivedFAC();
	    
    }
   	static testmethod void archiveCreateTest() {
	    createBaseData();
	    TFSC_searchController cont = new TFSC_searchController();
		PageReference pr = Page.TFSC_Search;
		Test.setCurrentPage(pr);
		ApexPages.currentPage().getParameters().put('ArchiveFANum','00070411111111110001');
		ApexPages.currentPage().getParameters().put('AccountClosedDate','');
		ApexPages.currentPage().getParameters().put('AccountBranch','');
		ApexPages.currentPage().getParameters().put('AccountType','');
		
		cont.createFAFromArchive();	    
    }
   	static testmethod void negTest() {
	    createBaseData();
	    TFSC_searchController cont = new TFSC_searchController();
	    
	    //Negative Scenario = 0 records
	    cont.fANumber = '00000000001111110001';
	    cont.sSN = '00000000';
	    cont.fName = 'FN';
	    cont.lName = 'LName';
	    cont.garZip = '11111';
	    cont.vINFull = '11111111111111111111';
	    cont.vIN8 = '11111111';
	    
	    cont.searchFAC();
	    System.assertEquals(cont.searchedFACs.size(), 0);
    }

    private static Financial_Account__c insertFA(Collateral__c car) {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = '1111111111', Collateral__c=car.Id,Finance_Account_Status__c='Active', CO_Host_Account_Number__c='00070411111111110001' );
        financialAccount.Collection_List_Number_1__c = '1704'; // for FPD
        financialAccount.History_Counter_Days_Past_Due__c = '10';
        insert financialAccount;        
       
        return financialAccount;
    }
    private static Financial_Account_Customer__c insertFAC(Financial_Account__c fa, Account acc) {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Financial_Account_Customer__c fac = new Financial_Account_Customer__c(Financial_Account__c = fa.Id, Account__c = acc.Id, Mailing_Postal_Code_Garage__c='11111' );
    fac.Borrower_Position__c = 'Primary';
        fac.Borrower_Status__c = 'Active';
        fac.Mailing_State_BillTo__c = 'CO';        
        fac.Work_Phone_Garage__c = '1111111111';
        fac.Mobile_Phone__c = '1111111111';
        fac.Home_Phone_Garage__c = '1111111111';
        fac.Work_Phone_Bill_To__c = '1111111111';
        fac.HomePhone_BillTo__c = '1111111111';
        fac.Borrower_Status__c = 'Active';
        fac.Customer_Role_Type__c = 'test';
        fac.FA_Role_Status__c = 'test';
    fac.Financial_Account_Customer__c = 'test2' + TFSC_TestUtils.generateRandomString(4);


        insert fac;        
       
        return fac;
    }
	private static void createBaseData(){
		Id persAccId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Customer', 'Account');
	    Id bussAccId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Business_Account', 'Account');

	    Account personAcct = new Account(FirstName='FName',LastName ='LName',RecordTypeId=persAccId, Social_Security_Number__pc='11111111');
	    insert personAcct;

	    Account bussAcc = new Account(name = 'Business Account123' ,RecordTypeId=bussAccId,Tax_Identification_Number__c='11111111');
	    insert bussAcc;

	    Collateral__c car = new Collateral__c(Vehicle_Identification_Number__c ='11111111111111111111',Make__c='Toyota', Model_Name__c='Camry',Model_Year__c='2015');
	    insert car;

	    Financial_Account__c fa = insertFA(car);    
	    
	    Financial_Account_Customer__c personfac = insertFAC(fa, personAcct);
	    Financial_Account_Customer__c busifac = insertFAC(fa, bussAcc);    
	}

}