AUGREL/src/objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Collateral__r.Model_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_YearOfTheVehicle.cls
/*
#########################################################################################

Project Name..........: TFS AB

File..................: <TFSC_YearOfTheVehicle> 

Version...............: <1.0>

Created by............: INFOSYS TECHNOLOGIES

Created Date..........: <14/12/2015> 

Last Modified by......: <ARJUN SONI>

Last Modified Date....: <16/12/2015 >

Description...........: <This Class has been written for feching the List of year of vehicle field from Collateral object.>
##########################################################################################
*/
public with sharing class TFSC_YearOfTheVehicle 
{  
    @InvocableMethod(label='Year Of The Vehicle' description='Returns the Year Of The Vehicle for the current record of FA')
    public static List<String> YearOfTheVehicle(List<String> faIds)
        {
        List<String> YearOfTheVehicleList=new List<String>();
        String faId = faIds.get(0);
        List<Financial_Account__c> FA=[SELECT Collateral__r.Model_Year__c  FROM Financial_Account__c where id=:faId];
        for(Financial_Account__c c :FA )
            {                   
            String YearOfTheVehicle =c.Collateral__r.Model_Year__c;
            YearOfTheVehicleList.add(YearOfTheVehicle);        
            }   
        System.debug('****************** returned list\'s contents: ' + YearOfTheVehicleList);
        return YearOfTheVehicleList;  
        }
}