AUGREL/src/objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certifiedmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certifiedmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoCustomer_AddyAddress1__c</fullName>
        <label>CoCustomer AddyAddress1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <label>CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CustomCurrency1__c</fullName>
        <label>CustomCurrency1</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomDate__c</fullName>
        <label>CustomDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CustomString1__c</fullName>
        <label>CustomString1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomString2__c</fullName>
        <label>CustomString2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomString3__c</fullName>
        <label>CustomString3</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomString4__c</fullName>
        <label>CustomString4</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number__c</fullName>
        <label>Dealer Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_Name__c</fullName>
        <description>Dispatch Name (Print Central, Print Local, Email, Fax)</description>
        <label>Dispatch Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>Document Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormId__c</fullName>
        <label>Form ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormType__c</fullName>
        <description>Type of Form (Interactive, Automatic)</description>
        <label>Form Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LegalEnvelop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NumberOfCopies__c</fullName>
        <label>NumberOfCopies</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_Address1__c</fullName>
        <label>Recipient Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Address2__c</fullName>
        <label>Recipient Address 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_CityStateZipCode__c</fullName>
        <label>Recipient City State Zip code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Fax__c</fullName>
        <label>Recipient Fax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_NameLine1__c</fullName>
        <label>Recipient Name Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestID__c</fullName>
        <externalId>true</externalId>
        <label>RequestID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnEnvelope__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Return Envelope</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_SystemName__c</fullName>
        <label>System Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_SystemName__c</fullName>
        <description>Target System Name(FileNet, Documentum)</description>
        <label>System Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Make__c</fullName>
        <label>Vehicle Make</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <label>Vehicle Model</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Year__c</fullName>
        <label>Vehicle Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Document_Request_Line_Item__c.object
<CustomObject>
    <description>Extensions of snapshot data used to generate unique inputs for document processing in the Adobe Forms Service - used for fields that may be used many times as a child node in a single form generation.</description>
    <fields>
        <fullName>DispatchName__c</fullName>
        <description>Dispatch Name (Print Central, Print Local, Network print,Email, Fax)</description>
        <label>Dispatch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Request__c</fullName>
        <label>Document Request</label>
        <referenceTo>Document_Request__c</referenceTo>
        <relationshipLabel>Document Request Line Items</relationshipLabel>
        <relationshipName>Document_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Certified_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Certified Mail or not.</inlineHelpText>
        <label>Is Certified Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-Customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isLegalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Legal Return Envelope Required or not</description>
        <label>Is Legal Envelop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>noOfCopies__c</fullName>
        <description>Number of Copies required</description>
        <label>No Of Copies</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>returnEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Return Envelope Required or not</description>
        <label>return envelop required</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Request Line Item</label>
    <nameField>
        <label>Document Request Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <fields>
        <fullName>NumberOfCopies__c</fullName>
        <description>Integer value to indicate the number of copies to send to the customer</description>
        <label>NumberOfCopies</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>certifiedmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to indicate form needs to send via certified mail or not.</description>
        <label>certifiedmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to indicate to use legal envelope or not</description>
        <label>legalEnvelop</label>
        <type>Checkbox</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field__c.object
<CustomObject>
    <description>Represents fields that appear on forms in the Adobe Forms Service. The columns identify source objects and fields, the target field on Document Request, and special processing instructions.</description>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Input_Fields__c</fullName>
        <label>Input Fields</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_item_field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Checkbox to indicate whether field has multiplicity property and needs to be represented in document request line item.</description>
        <label>Line item field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Line_item_type__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Picklist for multiplicity fields to group together on one line item record when in the same node - value maps to Type field on document request line item.</description>
        <label>Line item type</label>
        <picklist>
            <controllingField>Line_item_field__c</controllingField>
            <picklistValues>
                <fullName>Co-Customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense Type</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The source field from which the data should be fetched.</description>
        <label>Source Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The target field on the document request record or line item where the data will be stored.</description>
        <label>Target Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WS_DestinationNode__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The node in the forms WSDL to which the field belongs.</description>
        <inlineHelpText>Object Notation of child nodes of the soap envelope beneath the &quot;LCForms&quot; level.  e.g. Request.CreationDate.
IF this is a 1:many, then instead of dot notation, use a pipe &apos;|&apos; after property that denotes a &apos;many object&apos;.  e.g. req.node.addys|addy.state</inlineHelpText>
        <label>WS_DestinationNode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WS_Sequence__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The node sequence as defined in the forms WSDL.</description>
        <label>WS_Sequence</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field_Junction__c.object
<CustomObject>
    <description>Junction object linking Forms with their Form Fields and supporting re-use of fields across forms.</description>
    <fields>
        <fullName>Form_Field__c</fullName>
        <label>Form Field</label>
        <referenceTo>Form_Field__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field if checked then the field is mandatory, if unchecked Field is optional.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Form-Field Junction</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Form-Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Field Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_WSGenerateDocumentTest.cls
@isTest
private class Forms_WSGenerateDocumentTest{
    
   
static testMethod void testWSGenerateDocument() {

Form__c formObj = Forms_TestDataUtil.insertForm('4201');
Forms_TestDataUtil.insertFormFieldsForRequest();
Forms_TestDataUtil.insertFormFieldsForResponse(); 
    
    //Inserting datetime datatype field inorder to cover code.
    Form_Field__c formField = new Form_Field__c();
    formField.Data_Type__c = 'DateTime';
    formField.Name = 'CreatedDate__c';
    formField.Target_Field__c = 'CreatedDate__c';
    formField.Source_Field__c = '';
    formField.Input_Fields__c = '';
    formField.WS_Sequence__c = 5;
    formField.WS_DestinationNode__c='request.createdDate';
    formField.Line_item_field__c=false;
    formField.Line_item_type__c=null;
    insert formField;
    
    Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
    formFieldJunction.Form__c = formobj.Id;
    formFieldJunction.Form_Field__c = formField.Id;
    formFieldJunction.required__c =true;
    insert formFieldJunction;
    
Document_Request__c docReq = new Document_Request__c();
docReq.CustomDate__c = system.today();
docReq.FormType__c = 'Interactive';
//docReq.Dispatch_Name__c='Local Print';
//docReq.ReturnEnvelope__c=true;
//docReq.LegalEnvelop__c=false;
//docReq.NumberOfCopies__c=2;
//docReq.CertifiedMail__c=false;
docReq.Target_SystemName__c = 'FileNet';
docReq.AccountNumber__C='ACC1234re311223';
docReq.DocumentType__C = 'DCT1';
docReq.RequestID__c='REQUES12345';
docReq.Source_SystemName__c = 'ALFA';
docReq.FormID__c='4201';
docReq.Dealer_Number__c='DEALER1111';
docReq.Vehicle_Year__c = 2008;
docReq.Vehicle_Make__C ='TOYOTA';
docReq.Vehicle_Model__c='LEXUS';
docReq.VIN__c = '232DSDSDSw3';
docReq.Recipient_NameLine1__c = 'NameLINE1';
docReq.Recipient_Address1__c = 'ADDRESS1';
docReq.Recipient_Address2__c = 'ADDRESS2';
docReq.Recipient_CityStateZipCode__c='CityStateZipCode';
docReq.Recipient_FAX__c = '912-234-1245';
docReq.CustomString1__c = 'Deceased Indicator';
docReq.CustomCurrency1__c = 34100.25;
docReq.CreatedDate__c=system.now();
docReq.CustomString2__c='Product Type';
docReq.CustomString3__c='Jurisdiction';
docReq.CustomString4__c='user branch';
case caseobj = Forms_TestDataUtil.getCase();
docReq.case__c=caseobj.id;

insert docReq;

Document_Request_Line_Item__c lineItem1 = new Document_Request_Line_Item__c();
lineItem1.Type__c = 'Dispatch';
lineItem1.dispatchName__c = 'Network print';
lineItem1.Document_Request__c = docReq.Id;
lineItem1.isLegalEnvelop__c = true;
lineItem1.returnEnvelop__c = true;
lineItem1.Is_Certified_Mail__c = true;
lineItem1.noOfCopies__c =2;
/*lineItem1.Type__c='Other Charges';        
lineItem1.CoCustomer_AddyAddress1__c='FAX';
lineItem1.CoCustomer_AddyAddress2__c='YES';
lineItem1.Document_Request__c = docReq.Id;*/

Document_Request_Line_Item__c lineItem2 = new Document_Request_Line_Item__c();
    
/*lineItem2.Type__c='Other Charges';        
lineItem2.CoCustomer_AddyAddress1__c='Print Central';
lineItem2.CoCustomer_AddyAddress2__c='NO';
lineItem2.Document_Request__c = docReq.Id;*/
lineItem2.Type__c = 'Dispatch';
lineItem2.dispatchName__c = 'FAX';
lineItem2.Document_Request__c = docReq.Id;
lineItem2.isLegalEnvelop__c = true;
lineItem2.returnEnvelop__c = true;
lineItem1.Is_Certified_Mail__c = true;
lineItem1.noOfCopies__c =2;

List<Document_Request_Line_Item__c> drlList = new List<Document_Request_Line_Item__c>();
drlList.add(lineItem1);
drlList.add(lineItem2);

insert drlList;

FORMS_WS_GenerateDocument.buildFormFieldMap('4201',docReq,drlList);
List<FORMS_WS_GenerateDocument.XMLNode> nodeList = new List<FORMS_WS_GenerateDocument.XMLNode>();
FORMS_WS_GenerateDocument.XMLNode node1 = new FORMS_WS_GenerateDocument.XMLNode('ser:RefToSequenceNo','1','','');
node1.children = new List<FORMS_WS_GenerateDocument.XMLNode>();
node1.childrenNodesByName = new Map<String,FORMS_WS_GenerateDocument.XMLNode>();
nodeList.add(node1);
node1.addChildren(nodeList);
node1.removeFromParent();


}
   /* public class XMLNode {

    public String name;
    public String value;
    public String nameSpaceString;
    public String nameSpacePrefix;
        
      public XMLNode(String nodeName, String nodeValue, String nameSpaceString, String nameSpacePrefix) {
      this.name = nodeName;
      this.value = nodeValue;
      this.nameSpaceString = nameSpaceString;
      this.nameSpacePrefix = nameSpacePrefix;
    }
    }*/
static testMethod void testAddChildren() {
    
    
    //List<FORMS_WS_GenerateDocument.XMLNode> nodeList = new List<FORMS_WS_GenerateDocument.XMLNode>();
    FORMS_WS_GenerateDocument.XMLNode node1 = new FORMS_WS_GenerateDocument.XMLNode('ser:RefToSequenceNo','1','','');
    //nodeList.add(node1);
    //FORMS_WS_GenerateDocument.addChildren(nodeList);
    //FORMS_WS_GenerateDocument.removeFromParent();
}
}