AUGREL/src/objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>LegalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LegalEnvelop</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Document_Request_Line_Item__c.object
<CustomObject>
    <description>Extensions of snapshot data used to generate unique inputs for document processing in the Adobe Forms Service - used for fields that may be used many times as a child node in a single form generation.</description>
    <fields>
        <fullName>Document_Request__c</fullName>
        <label>Document Request</label>
        <referenceTo>Document_Request__c</referenceTo>
        <relationshipLabel>Document Request Line Items</relationshipLabel>
        <relationshipName>Document_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-Customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isLegalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Legal Return Envelope Required or not</description>
        <label>Is Legal Envelop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>returnEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Return Envelope Required or not</description>
        <label>return envelop required</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Request Line Item</label>
    <nameField>
        <label>Document Request Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <fields>
        <fullName>legalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to indicate to use legal envelope or not</description>
        <label>legalEnvelop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>returnEnvelopRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to indicate return envelope is required of no</description>
        <label>returnEnvelopRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_LogicConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Document_Object__c</fullName>
        <description>name of the document request object field</description>
        <label>Document Object</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logic_Condition__c</fullName>
        <label>Logic Condition</label>
        <picklist>
            <picklistValues>
                <fullName>IF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referecen_Attribute__c</fullName>
        <description>This field will be used as input for logic</description>
        <label>Referecen Attribute</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>expression__c</fullName>
        <label>expression</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>failValue__c</fullName>
        <label>failValue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>successValue__c</fullName>
        <label>successValue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value__c</fullName>
        <label>value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Forms Logic Configuration</label>
    <nameField>
        <label>Forms_LogicConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Logic Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_LogicExecutorTest.cls
/*
#########################################################################################
Project Name..........: TFS Forms Implementation
File..................: <Forms_LogicExecutorTest> 
Version...............: <1.0>
Created by............: INFOSYS TECHNOLOGIES
Created Date..........: <02/26/2016> 
Last Modified by......: <pranav>
Last Modified Date....: <02/26/2016>
Description...........: <This test class has been written covering code for Forms_LogicExecutor class for SFDC data>

Change Request History:

##########################################################################################
 */



 @isTest 
private class Forms_LogicExecutorTest{


/*
      Method Name:testExecuteMethod1
      Method Signature/Inputs:
      Method Return Type/outputs: Testing Logic 
      Method Description:This method is used to insert test data for the desired Logic class
*/

 static testmethod void testExecuteMethod1(){

 Map <String,String> testDataMap = new Map<String,String>();
       testDataMap.put('testamount1','100');
       testDataMap.put('testamount2','100');
       testDataMap.put('refValkey','testRef');
  Map<String,String> testResultMap = new Map<String,String>();
 
 List<Forms_LogicConfiguration__c> logicConfigList1 = new  List<Forms_LogicConfiguration__c>();
 List<Forms_LogicConfiguration__c> logicConfigList2 = new  List<Forms_LogicConfiguration__c>();
 Forms_LogicConfiguration__c logicConfig1 = new Forms_LogicConfiguration__c();
 
            logicConfig1.Referecen_Attribute__c ='testamount';
            logicConfig1.Logic_Condition__c='ADDSUB';
            logicConfig1.expression__c='testamount1+testamount2';
            insert logicConfig1;
 logicConfigList1.add(logicConfig1);
 
 Forms_LogicConfiguration__c logicConfig2 = new Forms_LogicConfiguration__c();
            logicConfig2.Referecen_Attribute__c ='refValkey';
            logicConfig2.Logic_Condition__c='IF';
            logicConfig2.Operator__c='IN';
            ///logicConfig2.successValue__c;
           // logicConfig2.failValue__c;
            logicConfig2.value__c='abc,def';
            //logicConfig2.document_object__c;
            insert logicConfig2;
 logicConfigList2.add(logicConfig2);
 
// referenceValue

            test.starttest();
            //checking the first loop 
            Form__c formInserted=Forms_TestDataUtil.insertForm('4201');
            List<Document_Request_Line_Item__c> DocReqLineItemList=new List<Document_Request_Line_Item__c>();
        
        Document_Request_Line_Item__c docReqLineItem = new Document_Request_Line_Item__c();
        docReqLineItem.Type__c = Forms_Constant.DISPATHLINEITEMTYPE;        
        docReqLineItem.isLegalEnvelop__c = formInserted.legalEnvelop__c;
        docReqLineItem.returnEnvelop__c = formInserted.returnEnvelopRequired__c;
        DocReqLineItemList.add(docReqLineItem);        
        Document_Request_Line_Item__c docReqLineItem1 = new Document_Request_Line_Item__c();
        docReqLineItem1.Type__c = Forms_Constant.DISPATHLINEITEMTYPE;        
        docReqLineItem1.isLegalEnvelop__c = formInserted.legalEnvelop__c;
        docReqLineItem1.returnEnvelop__c = formInserted.returnEnvelopRequired__c;
        DocReqLineItemList.add(docReqLineItem1);          
        
        Document_request__c DocReq=Forms_TestDataUtil.getDocumentRequest('4201');
        
        Forms_DocumentDataHolder documentData=new Forms_DocumentDataHolder();
        documentData.setDocumentRequest(DocReq);
        documentData.setLineItems(DocReqLineItemList);                      
            Map<String,String>  resultMap1 = Forms_LogicExecutor.execute(testDataMap,logicConfigList1, testResultMap,documentData);
            //System.assert();
            
            //checking the else condition
            Map<String,String>  resultMap2 = Forms_LogicExecutor.execute(testDataMap,logicConfigList2, testResultMap,documentData);
            //System.assert();
            test.stoptest();
            
    }       
}