AUGREL/src/objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certifiedmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certifiedmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomString18__c</fullName>
        <description>Mapped to Name line1 which is coming loadThirdParty as it is overriding</description>
        <label>CustomString18</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomString1__c</fullName>
        <label>CustomString1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomString3__c</fullName>
        <label>CustomString3</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomString8__c</fullName>
        <label>CustomString8</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_DeviceName__c</fullName>
        <label>Dispatch Device Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_Name__c</fullName>
        <description>Dispatch Name (Print Central, Print Local, Email, Fax)</description>
        <label>Dispatch Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LegalEnvelop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NumberOfCopies__c</fullName>
        <label>NumberOfCopies</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_NameLine1__c</fullName>
        <label>Recipient Name Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Name_Line_2__c</fullName>
        <label>Recipient Name Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Document_Request_Line_Item__c.object
<CustomObject>
    <description>Extensions of snapshot data used to generate unique inputs for document processing in the Adobe Forms Service - used for fields that may be used many times as a child node in a single form generation.</description>
    <fields>
        <fullName>DispatchName__c</fullName>
        <description>Dispatch Name (Print Central, Print Local, Network print,Email, Fax)</description>
        <label>Dispatch Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_DeviceName__c</fullName>
        <description>This field is for devicename</description>
        <label>Dispatch_DeviceName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Request__c</fullName>
        <label>Document Request</label>
        <referenceTo>Document_Request__c</referenceTo>
        <relationshipLabel>Document Request Line Items</relationshipLabel>
        <relationshipName>Document_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Certified_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Certified Mail or not.</inlineHelpText>
        <label>Is Certified Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-Customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isLegalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Legal Return Envelope Required or not</description>
        <label>Is Legal Envelop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>noOfCopies__c</fullName>
        <description>Number of Copies required</description>
        <label>No Of Copies</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>returnEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Return Envelope Required or not</description>
        <label>return envelop required</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Request Line Item</label>
    <nameField>
        <label>Document Request Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <fields>
        <fullName>NumberOfCopies__c</fullName>
        <description>Integer value to indicate the number of copies to send to the customer</description>
        <label>NumberOfCopies</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>certifiedmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to indicate form needs to send via certified mail or not.</description>
        <label>certifiedmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEnvelop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to indicate to use legal envelope or not</description>
        <label>legalEnvelop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>returnEnvelopRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to indicate return envelope is required of no</description>
        <label>returnEnvelopRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Request__c.object
<CustomObject>
    <fields>
        <fullName>Device_Name__c</fullName>
        <label>Device Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_Name__c</fullName>
        <label>Dispatch Name</label>
        <picklist>
            <picklistValues>
                <fullName>Print Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Form Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Form Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_DataAggregatorHelper.cls
/*
#########################################################################################
Project Name..........: TFS Forms Implementation
File..................: Forms_DataAggregatorHelper
Version...............: 1.0
Created by............: INFOSYS TECHNOLOGIES
Created Date..........: 10/6/2015 
Last Modified by......: Thenmozhi
Last Modified Date....: 10/26/2015 
Description...........: This helper class has been written for fetching multiple dispatch modes  and languages details for specific forms


Change Request History:
thenmozhi      27/11/2015   Added commands for methods and header for code standard
Balaji    J    14/01/2016   Added two methods getOutStandingLeaseBalance and getSalesTaxOnOutStandingLeaseBalance for assigning balances docReqObj Object.

##########################################################################################
 */
public class Forms_DataAggregatorHelper {
    /*
      Method Name: aggregateDispatchInformation
      Method Signature/Inputs:Form__c formData, Form_Request__c formRequest, Forms_DocumentDataHolder documentData
      Method Return Type/outputs:Adding documentData 
      Method Description:This method is used to fetch document data
     */
    public void aggregateDispatchInformation(Form__c formData, Form_Request__c formRequest, Forms_DocumentDataHolder documentData,Map<string,string> dataMap){

        String dispatchTypes = formRequest.Dispatch_Name__c;
        if(dispatchTypes != null){
        List<String> dispatchType = dispatchTypes.split(';'); 
        for(String dispatchName : dispatchType){ 
            Document_Request_Line_Item__c docReqLineItem = new Document_Request_Line_Item__c();
            docReqLineItem.Type__c = Forms_Constant.DISPATHLINEITEMTYPE;
            docReqLineItem.dispatchName__c = dispatchName;
            docReqLineItem.isLegalEnvelop__c = formData.legalEnvelop__c;
            docReqLineItem.returnEnvelop__c = formData.returnEnvelopRequired__c;
            docReqLineItem.Is_Certified_Mail__c = formData.certifiedmail__c;
            docReqLineItem.noOfCopies__c = formData.NumberOfCopies__c;
            if(dispatchName.equalsIgnoreCase(Forms_Constant.DISPATCHNETWORKPRINT))
                docReqLineItem.Dispatch_DeviceName__c = formRequest.Device_Name__c;
            documentData.addLineItem(docReqLineItem);
            }
        }
        String formNumber = dataMap.get(Forms_Constant.FORMNUMBER);
        Map<String,String> expenseDescForExpenseType = new Map<String,String>();
        List<String> chargeCodes;
        Map<String,Decimal> getNetBilledNumber= new Map<String,Decimal>();
        Map<String,Decimal> getTaxBilledNumber= new Map<String,Decimal>();

       
          
    }
   
    /*account number convertion */

    public void convertAccountNumber(Map<String,String> dataMap, Forms_DocumentDataHolder documentData){

        String accountNumber = Forms_Utils.convertAccountNumber(dataMap.get('accountnumber'),dataMap.get('productcode'));
        Document_Request__c docRequest = documentData.getDocumentRequest();
        docRequest.AccountNumber__c = accountNumber; 
        documentData.setDocumentRequest(docRequest);

    } 
    /*
      Method Name: aggregateLanguagePreference
      Method Signature/Inputs:Form_Request__c formRequest, Forms_DocumentDataHolder documentData
      Method Return Type/outputs:Adding documentData for language preference 
      Method Description:This method is used to fetch document data for language preference.
     */
    public void aggregateLanguagePreference(Form_Request__c formRequest, Forms_DocumentDataHolder documentData){

        system.debug('Forms_DataAggregatorHelper::aggregateLanguagePreference:: doumentData  is '+documentData);
        //system.debug('Forms_DataAggregatorHelper::aggregateLanguagePreference:: Language is '+languagePreference);
        Document_Request__c docRequest = documentData.getDocumentRequest();
        docRequest.language__c = Forms_Utils.getLanguagePreference(docRequest.Language__c);
        documentData.setDocumentRequest(docRequest);
    }

    /*
      Method Name: handleDeceasedReceipent
      Method Signature/Inputs:Forms_DocumentDataHolder documentData
      Method Return Type/outputs:Adding Forms_Utils
      Method Description:This method is used to handle docReqObj  object 
     */
    public void handleDeceasedReceipent(Forms_DocumentDataHolder documentData){
        Document_Request__c docReqObj = documentData.getDocumentRequest();
        if(docReqObj.Recipient_NameLine1__c!=null)
        docReqObj.Recipient_NameLine1__c = Forms_Utils.handleDeceasedReceipent(docReqObj.Recipient_NameLine1__c, docReqObj.CustomString1__c);
        if(docReqObj.Customstring18__c!=null)
       
        docReqObj.Customstring18__c = Forms_Utils.handleDeceasedReceipent(docReqObj.Customstring18__c, docReqObj.CustomString1__c);
       
        if(docReqObj.Recipient_Name_Line_2__c!=null)
        docReqObj.Recipient_Name_Line_2__c = Forms_Utils.handleDeceasedReceipent(docReqObj.Recipient_Name_Line_2__c, docReqObj.CustomString3__c);
    }   
    
   public void trimAccNumber(Forms_DocumentDataHolder documentData,Map<String,String> responseDataMap){
      Document_Request__c docReqObj = documentData.getDocumentRequest();  
        if(responseDataMap.get('bankaccountnumber')!=null && responseDataMap.get('bankaccountnumber')!=' '){ 
           docReqObj.CustomString8__c = responseDataMap.get('bankaccountnumber').right(4);   
        }    
   }

}