AUGREL/src/objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>FormId__c</fullName>
        <label>Form ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Document_Request_Line_Item__c.object
<CustomObject>
    <description>Extensions of snapshot data used to generate unique inputs for document processing in the Adobe Forms Service - used for fields that may be used many times as a child node in a single form generation.</description>
    <fields>
        <fullName>Document_Request__c</fullName>
        <label>Document Request</label>
        <referenceTo>Document_Request__c</referenceTo>
        <relationshipLabel>Document Request Line Items</relationshipLabel>
        <relationshipName>Document_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-Customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document Request Line Item</label>
    <nameField>
        <label>Document Request Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field__c.object
<CustomObject>
    <description>Represents fields that appear on forms in the Adobe Forms Service. The columns identify source objects and fields, the target field on Document Request, and special processing instructions.</description>
    <fields>
        <fullName>Desired_Property__c</fullName>
        <description>Map this value to WS node</description>
        <label>Desired Property</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forms_QueryConfig__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forms_QueryConfig</label>
        <referenceTo>Forms_QueryConfig__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_item_type__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Picklist for multiplicity fields to group together on one line item record when in the same node - value maps to Type field on document request line item.</description>
        <label>Line item type</label>
        <picklist>
            <controllingField>Line_item_field__c</controllingField>
            <picklistValues>
                <fullName>Co-Customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense Type</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The target field on the document request record or line item where the data will be stored.</description>
        <label>Target Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field_Junction__c.object
<CustomObject>
    <description>Junction object linking Forms with their Form Fields and supporting re-use of fields across forms.</description>
    <fields>
        <fullName>Form_Field__c</fullName>
        <label>Form Field</label>
        <referenceTo>Form_Field__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form-Field Junction</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Form-Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Field Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_LogicConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Document_Object__c</fullName>
        <description>name of the document request object field</description>
        <label>Document Object</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referecen_Attribute__c</fullName>
        <description>This field will be used as input for logic</description>
        <label>Referecen Attribute</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value__c</fullName>
        <label>value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Forms Logic Configuration</label>
    <nameField>
        <label>Forms_LogicConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Logic Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_QueryConfig__c.object
<CustomObject>
    <description>Forms_QueryConfig for SourceSystem=&apos;SFDC&apos; in Form_Field__c</description>
    <fields>
        <fullName>DataType__c</fullName>
        <label>DataType</label>
        <picklist>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Object_Field__c</fullName>
        <label>Document_Object_Field</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_APIName__c</fullName>
        <label>Field_APIName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Field__c</fullName>
        <label>Filter Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_ApiName__c</fullName>
        <label>Object_ApiName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceAttribute__c</fullName>
        <label>ReferenceAttribute</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>Forms Query Configuration</label>
    <nameField>
        <label>QueryConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Query Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_Validation_Result__c.object
<CustomObject>
    <label>Forms Validation Result</label>
    <nameField>
        <displayFormat>FVE-{0000}</displayFormat>
        <label>Forms Validation Error Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Validation Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/FormServiceConfig__c.object
<CustomObject>
    <fields>
        <fullName>AttributeType__c</fullName>
        <label>AttributeType</label>
        <picklist>
            <picklistValues>
                <fullName>Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FormService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FormService</label>
        <referenceTo>FromServices__c</referenceTo>
        <relationshipName>FormServiceConfig</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link_to_DocumentRequestLineItem_Object__c</fullName>
        <label>Link to DocumentRequestLineItem Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_to_Document_Request_Object__c</fullName>
        <description>The field which corresponds to this field in Document Request object</description>
        <label>Link to Document Request Object</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceAttribute__c</fullName>
        <label>ReferenceAttribute</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Form Service Configuration</label>
    <nameField>
        <label>AttributeName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Service Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/FromServices__c.object
<CustomObject>
    <fields>
        <fullName>MultiNode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MultiNode</label>
        <type>Checkbox</type>
    </fields>
    <label>Form Services</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_DocumentRequestDataMapping.cls
/*
#################################################################################################################
Project Name         : TFS Forms Implementation
File                 : Forms_DocumentRequestDataMapping
Version              : <1.0>
Created by           : Infosys Offshore team
Created Date         : 12/10/2015 
Last Modified by     : <NAME>
Last Modified Date   : <MM/DD/YYYY >
Description          : This class will map the response values to Document request object.
                        Validates the response.
                        Builds the XML using FormsServiceConfig obj.

Change Request History:

Modified By      Date              Comments

Sridhar G      23/10/2015        Added Data type check and mapping fields to Document Request Object
                                 Added Static block for reading document requst fields data type 
                      
Sridhar G      27/10/2015        Added Data type check and mapping fields to Document Request line item Obejct

Charitha S     12/11/2015        Changed mappingResponseToDocReq method. this method is only responsible to map the sent reponseMap to DocReqObj
                                 and set to Forms_DocumentDataHolder.code changes & method signature in validateResponseData method which is 
                                 invoked from Forms_RequestProcessor for validation Reponse Data. Added new method generateDmsXML which is invoked from 
                                 Forms_RequestProcessor if validation is success.
                                 
Geetha M       18/11/2015        Changed the query in order to obtain service level fields as suggested by Hanumantha
###################################################################################################################
*/


public class Forms_DocumentRequestDataMapping{

  Document_Request__c docReqObj = new Document_Request__c();  
  public static List<FormServiceConfig__c> docReqMappingList = new List <FormServiceConfig__c>();
  public static Map<string,string> docReqMap = new Map<string,string>();
  public static Set<String> docReqSet = new Set<String>();
  Map<string, string> dataTypeMap = new map<string, string>(); 
   Set<String> logicSet = new  Set<String>(); 
 /* public static String type = null;
  public static Map<String, Schema.SObjectType> schemaMap = null;
  public static Schema.SObjectType docReqSchema = null;
  public static Map<String, Schema.SObjectField> fieldMap = null;
 
  static
  {
    type= Forms_Constant.DOCUMENTREQUEST;
    schemaMap = Schema.getGlobalDescribe();
    DocReqSchema = schemaMap.get(type);
    fieldMap = DocReqSchema.getDescribe().fields.getMap();
  }*/
  /* added for testing */
  public static String docReqXML='';  

  /*
    Method Name: mappingResponseToDocReq
    Method Signature/Inputs: responseDataMap from forms_requestProcessor, Forms_DocumentDataHolder class instance.
    Method Return Type/outputs: ResponseDataMap values will be assigned to DocumentRequest obj and documnetRequestLineitem object.
    Method Description: This method is called from Forms_requestProcessor class, where this method checks if the 
                        Datatype format is correct and gives the output in the objects.
  */
  public Forms_documentDataHolder mappingResponseToDocReq(map<String,string> responseDataMap, Forms_DocumentDataHolder documentData,
                                                            List<Form_Field_Junction__c> serviceList )
  {
    Forms_Utils.gettingAllMetaDataFields(Forms_Constant.DOCUMENTREQUEST);
    Map<String,String> docReqLineItemMap = new Map<STring,String>();
    Datetime startDate=system.now();
    Set<String> serviceIdSet = new Set<String>();
    docReqObj = documentData.getDocumentRequest();
    
     system.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq::Document Request::'+json.serialize(docReqObj));
      
    try
      { 
             
       System.debug('Forms_DocumentRequestDataMapping :: mappingResponseToDocReq()::docReqMap====>'+json.serialize(docReqMap));
       System.debug('Forms_DocumentRequestDataMapping :: mappingResponseToDocReq()::responseDataMap====>'+json.serialize(responseDataMap));
       System.debug('Forms_DocumentRequestDataMapping :: mappingResponseToDocReq()::responseDataMap====>'+json.serialize(responseDataMap.keyset()));
          
       /*integer serviceDocReqFieldCount = 0;
       Set<String> desiredFields = new Set<String>();
       for(Form_Field_Junction__c formFieldJunc : serviceList){
            
            if((formFieldJunc.Form_Field__r.Desired_Property__c!=null) && (formFieldJunc.Form_Field__r.Desired_Property__c.trim().length()>0)){
               desiredFields.add(formFieldJunc.Form_Field__r.Desired_Property__c);
            }    
           if(formFieldJunc.Form_Field__r.Target_Field__c !=null && formFieldJunc.Form_Field__r.Target_Field__c.trim().length()>0){
               serviceDocReqFieldCount++;
           }
           
        }
          System.debug('desiredfields'+desiredFields.size()+'::'+desiredFields+'::'+serviceList.size()+'::'+serviceDocReqFieldCount);
       */
      
     docReqMappingList = [SELECT FormService__r.name,FormService__r.MultiNode__c,Id,name,ReferenceAttribute__c,Link_to_Document_Request_Object__c,Link_to_DocumentRequestLineItem_Object__c from FormServiceConfig__c where (AttributeType__c =:Forms_Constant.RESPONSE) and ReferenceAttribute__c in :responseDataMap.keyset()];
     
     /* adding by manga  */
     List<Forms_QueryConfig__c> queryConfig =  [SELECT Field_APIName__c, Filter_Field__c, Object_APIName__c,ReferenceAttribute__c,DataType__c,Document_Object_Field__c FROM Forms_QueryConfig__c WHERE Document_Object_Field__c IN :responseDataMap.keyset()];
     Set<String> configSet = new Set<String>();
     for(Forms_QueryConfig__c queConfig:queryConfig){
        configSet.add(queConfig.Document_Object_Field__c);      
     }
      /* adding by manga  */
      
      /* Addeded by Balaji Jadav */
      /*List<Forms_LogicConfiguration__c> logicConfig = [Select Referecen_Attribute__c,value__c,
      Document_Object__c from  Forms_LogicConfiguration__c WHERE Document_Object__c IN : responseDataMap.keyset()];
       
      for (Forms_LogicConfiguration__c logiccon:logicConfig){
          logicSet.add(logiccon.Document_Object__c);
      }*/
         /* data mapping to document requst object matching desired field in form field object and reference attribute in form service configuration */
          
          List<Form_Field_Junction__c> formFields = Forms_DataSelector.getConfiguredFields(responseDataMap.get('formnumber'));
          for(Form_Field_Junction__c field: formFields) {
              String ffRef = field.Form_Field__r.Desired_Property__c;
              if(ffRef!=null && ffRef.trim().length()>0){
                  String value = responseDataMap.get(ffRef);
                  docReqMap.put(ffRef,field.Form_Field__r.Target_Field__c);
                  docReqSet.add(ffRef);    
              }
              
          }
      
      /* Addeded By Balaji Jadav */
     
        for(FormServiceConfig__c formServConf : docReqMappingList) {
            if(formServConf.Link_to_Document_Request_Object__c != null) {
                
                docReqMap.put(formServConf.ReferenceAttribute__c,formServConf.Link_to_Document_Request_Object__c);
                docReqSet.add(formServConf.ReferenceAttribute__c);
                
            }else if(formServConf.Link_to_DocumentRequestLineItem_Object__c != null && formServConf.FormService__r.MultiNode__c){
                //populating below map for multinode form services.
                docReqLineItemMap.put(formServConf.ReferenceAttribute__c,formServConf.Link_to_DocumentRequestLineItem_Object__c);
            }        
        }
     
        system.debug('Forms_DocumentRequestDataMapping :: mappingResponseToDocReq():: docReqSet:'+docReqSet); 
        system.debug('Forms_DocumentRequestDataMapping :: mappingResponseToDocReq():: docReqMap:'+docReqMap.size()+'::'+json.serialize(docReqMap));
        
        for(String resSingleKey : responseDataMap.keyset())
        {   
            if(docReqSet.contains(resSingleKey))
            {
                
              String apiNameDR = docReqMap.get(resSingleKey);
              system.debug('Forms_DocumentRequestDataMapping :: mappingResponseToDocReq():: apiNameDR:'+apiNameDR);
             // Schema.DisplayType fielddataType = fieldMap.get(apiNameDR).getDescribe().getType();
              Schema.DisplayType fielddataType = Forms_Utils.fieldMap.get(apiNameDR).getDescribe().getType();
              String fieldAPIName = Forms_Utils.fieldMap.get(apiNameDR).getDescribe().getName();
             // System.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq::<--fieldAPIName---->'+fieldAPIName+'<==fielddataType===>'+fielddataType + '<=== data===>'+responseDataMap.get(resSingleKey));  
                String responseData = responseDataMap.get(resSingleKey);
                if(responseData!=null && responseData.trim().length() > 0){
                if(fielddataType == Schema.DisplayType.Double){
                   
                    if(responseData.indexOf('.')==-1){
                        docReqObj.put(apiNameDR,Integer.valueOf(responseDataMap.get(resSingleKey)));
                    }else{
                       docReqObj.put(apiNameDR,Double.valueOf(responseDataMap.get(resSingleKey)));
                    }    
                }
                else if(fielddataType == Schema.DisplayType.DATE){
                  docReqObj.put(apiNameDR,date.valueOf(responseDataMap.get(resSingleKey)));
                }
                else if(fielddataType == Schema.DisplayType.DATETIME){
                  docReqObj.put(apiNameDR,DATETIME.valueOf(responseDataMap.get(resSingleKey)));
                }
                else if(fielddataType == Schema.DisplayType.boolean){
                  docReqObj.put(apiNameDR,boolean.valueOf(responseDataMap.get(resSingleKey)));
                }
                else{
                  docReqObj.put(apiNameDR,(responseDataMap.get(resSingleKey)));
                }
                }               
                system.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq::Valuesobj==>'+ docReqObj); 
                
        }
        /* Added by manga for testing */
        else{
              if(configSet.contains(resSingleKey)){
          
                  Schema.DisplayType fieldconfigdataType =Forms_Utils.fieldMap.get(resSingleKey).getDescribe().getType();
                  String fieldCnfgAPIName = Forms_Utils.fieldMap.get(resSingleKey).getDescribe().getName();
                  System.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq::<--fieldAPIName---->'+fieldCnfgAPIName+'<==fielddataType===>'+fieldconfigdataType + '<=== data===>'+responseDataMap.get(resSingleKey));
                  String responseData = responseDataMap.get(resSingleKey);
                  if(fieldconfigdataType  == Schema.DisplayType.Double){
                      if(responseData.indexOf('.')==-1)
                        docReqObj.put(resSingleKey,Integer.valueOf(responseData));
                     else
                       docReqObj.put(resSingleKey,Double.valueOf(responseData ));
                  }
                  else if(fieldconfigdataType  == Schema.DisplayType.DATE)
                      docReqObj.put(resSingleKey,date.valueOf(responseData));
                  else if(fieldconfigdataType  == Schema.DisplayType.DATETIME)
                      docReqObj.put(resSingleKey,DATETIME.valueOf(responseData));
                  else if(fieldconfigdataType  == Schema.DisplayType.boolean)
                      docReqObj.put(resSingleKey,boolean.valueOf(responseData ));
                  else
                  docReqObj.put(resSingleKey,responseData); 
                   
              }  
        }
     }
       
      documentData.setDocumentRequest(docReqObj);     
    //map Response to DocumentRequestLineItems object.
    if(docReqLineItemMap!=null && docReqLineItemMap.size()>0)
      mapResponseToDocReqLineItem(responsedataMap,docReqLineItemMap,documentData);
      
      system.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq::Document Request::'+json.serialize(docReqObj));
      Forms_Utils.executionTime(startDate,system.now(),'Forms_DocumentRequestDataMapping','mappingResponseToDocReq');
     
  }
  catch(Exception e)
  {
    System.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq::Forms_documentReqMApping : '+e.getStackTraceString());
    System.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq::Forms_documentReqMApping : '+e.getmessage());
  }
    return documentData;      
 } 

  /*
    Method Name: mapResponseToDocReqLineItem
    Method Signature/Inputs: responseDataMap , docReqLineItemMap, Forms_DocumentDataHolder class instance.
    Method Return Type/outputs: void
    Method Description: This method will check any multinode services are configured for form, if exists creates lineitems for
    each lineitemType with multi values retrieved from service and sets all lineitems to documentData.
  */
  public void mapResponseToDocReqLineItem(map<String,String> responsedataMap,Map<String,String> docReqLineItemMap, Forms_DocumentDataHolder documentData){
    
        Map<String, Map<String, List<String>>> lineItemsMap = new Map<String, Map<String, List<String>>>();
        Map<String, List<String>> multiNodeMap = new Map<String, List<String>>();
        Map<String, Integer> lineItemsCount = new Map<String,Integer>();
        List<Document_Request_Line_Item__c> docReqLineItemsList =  documentData.getLineItems(); 
        
        //get FormFieldJunction for multinode services  
        List<Form_Field_Junction__c> lineItems = Forms_DataSelector.getMultiServicesJunctions(responseDataMap,docReqLineItemMap);
        system.debug('@lineItems'+lineItems);                        
        for(Form_Field_Junction__c junction : lineItems){
           
            //for each multinode lineItem type creating map<lineItemType,map<Link_To_Document_Request_LineItem,List<values>>>>
            STring lineItemType = junction.Form_Field__r.Line_item_type__c;
            Integer count = 0 ;
            if(!lineItemsMap.containsKey(lineItemType))
            multiNodeMap = new Map<String,List<String>>();
            for(String lineItemKey : docReqLineItemMap.keySet())
            {
                if(junction.form_field__r.target_Field__c.equalsIgnoreCase(docReqLineItemMap.get(lineItemKey))){
                String responseData = responseDataMap.get(lineItemKey);
                if(responseData!=null && responseData.trim().length() > 0){ 
                String[] splitKey = responseData.split(',');
                count = splitKey.size();
                multiNodeMap.put(docReqLineItemMap.get(lineItemKey),splitKey);
                    }
                }
            }
            lineItemsMap.put(lineItemType,multiNodeMap);
            if(!lineItemsCount.containsKey(lineItemType) && count>0)
            lineItemsCount.put(lineItemType,count);
        }
        //populating lineItems for multiNode Serviceconfig response.
        for(String type : lineItemsMap.keySet()){  
            for(Integer i=0;i<lineItemsCount.get(type);i++){        
                Document_Request_Line_Item__c docReqLineItem= new Document_Request_Line_Item__c();
                docReqLineItem.Type__c = type;
                for(String apiName :lineItemsMap.get(type).keySet()){
                    docReqLineItem.put(apiName,lineItemsMap.get(type).get(apiName).get(i));
                }
                 
            docReqLineItemsList.add(docReqLineItem);
            }           
        }
        System.debug('Forms_DocumentRequestDataMapping::mapResponseToDocReqLineItem:: docReqLineItems size: '+docReqLineItemsList.size());
    documentData.setLineItems(docReqLineItemsList);
  }
/*
    Method Name: validateResponseData
    Method Signature/Inputs: Forms_DataValidator dataValidator,Forms_DocumentDataHolder documentData
    Method Return Type/outputs: Result, if the class passes it will be sent to next method for output generation, 
                                if it fails it will retrun Forms_Validation_Result__c object.
    Method Description: This method is called from forms_requestProcessor class, it is to Validate if the data in the Objects 
                        is in right format and retruns the Forms_Validation_Result__c  object if it fails.
*/
 Public Forms_Validation_Result__c validateResponseData(Forms_DataValidator dataValidator,Forms_DocumentDataHolder documentData) 
  {     
    Datetime startDate=system.now();     
    system.debug('Forms_DocumentRequestDataMapping::validateResponseData::Validate method documentData.getLineItems():'+documentData.getLineItems());
    Forms_Validation_Result__c result = dataValidator.validateDocumentData(documentData.getDocumentRequest(),documentData.getLineItems());   
    system.debug('Forms_DocumentRequestDataMapping::validateResponseData::Validate method check:'+result);
    Forms_Utils.executionTime(startDate,system.now(),'Forms_DocumentRequestDataMapping','validateResponseData');
    return result;  
  }

  
/*
    Method Name: generateDmsXML
    Method Signature/Inputs: Forms_DocumentDataHolder documentData
    Method Return Type/outputs: This method will generate XML.
    Method Description: This method is called from forms_requestProcessor class, it is to generate Final XML
*/
  public void generateDmsXML(Forms_DocumentDataHolder documentData)
    {
    
        FORMS_WS_GenerateDocument.XMLNode docReq=FORMS_WS_GenerateDocument.buildFormFieldMap(String.valueOf(documentData.getDocumentRequest().formId__c),documentData.getDocumentRequest(),documentData.getLineItems());
        Forms_DocumentRequestDataMapping.docReqXML= docReq.getXMLString();  
        System.debug('Forms_DocumentRequestDataMapping::mappingResponseToDocReq()::XMLString'+Forms_DocumentRequestDataMapping.docReqXML);
    
    
}
}