AUGREL/src/objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>CustomString4__c</fullName>
        <label>CustomString4</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Render Form Service Status (Success, Failure)</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Document_Request_Line_Item__c.object
<CustomObject>
    <description>Extensions of snapshot data used to generate unique inputs for document processing in the Adobe Forms Service - used for fields that may be used many times as a child node in a single form generation.</description>
    <fields>
        <fullName>Document_Request__c</fullName>
        <label>Document Request</label>
        <referenceTo>Document_Request__c</referenceTo>
        <relationshipLabel>Document Request Line Items</relationshipLabel>
        <relationshipName>Document_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Request Line Item</label>
    <nameField>
        <label>Document Request Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field__c.object
<CustomObject>
    <description>Represents fields that appear on forms in the Adobe Forms Service. The columns identify source objects and fields, the target field on Document Request, and special processing instructions.</description>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>ALFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOGIC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The target field on the document request record or line item where the data will be stored.</description>
        <label>Target Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field_Junction__c.object
<CustomObject>
    <description>Junction object linking Forms with their Form Fields and supporting re-use of fields across forms.</description>
    <fields>
        <fullName>Form_Field__c</fullName>
        <label>Form Field</label>
        <referenceTo>Form_Field__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field if checked then the field is mandatory, if unchecked Field is optional.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Form-Field Junction</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Form-Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Field Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Request__c.object
<CustomObject>
    <label>Form Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Form Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Request_Line_Item__c.object
<CustomObject>
    <label>Form Request Line Item</label>
    <nameField>
        <displayFormat>FRLI-{0000}</displayFormat>
        <label>Form Request Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Request Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_Validation_Result__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>Error Message</label>
        <length>32767</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The field to show successful or failure validation.</description>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Forms Validation Result</label>
    <nameField>
        <displayFormat>FVE-{0000}</displayFormat>
        <label>Forms Validation Error Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Validation Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_DataValidatorTest.cls
/*
#########################################################################################
Project Name..........: TFS Forms Implementation
File..................: Forms_DataValidatorTest
Version...............: 1.0
Created by............: Charitha_Seelam,Kaavya_Kanna,Pranav_Prasun,Geetha_muthukuru
Created Date..........: 10/08/2015 
Last Modified by......: Charitha_Seelam
Last Modified Date....: 11/26/2015
Description...........: Test Class to test the Forms_DataValidator methods

Change Request History:
##########################################################################################
*/


@isTest
Public class Forms_DataValidatorTest
{ 
    Static testmethod void test_ValidateFormReqData()
    {
        Forms_TestDataUtil.insertForms_ErrorMessages();
        Forms_TestDataUtil.insertForm('4201');
        Forms_TestDataUtil.insertFormFieldsForRequest();
        Form_Request__c formReq = Forms_TestDataUtil.getValidFormRequest('4201');
        Form_Request__c invalidFormReq =  Forms_TestDataUtil.getInvalidFormRequest('4201');   
        List<Form_Request_Line_Item__c> lineItems = Forms_TestDataUtil.getValidFormReqLineItems();
        List<Form_Request_Line_Item__c> lineItems1 = Forms_TestDataUtil.getFormReqLineItems();
        
        Forms_DataValidator dataValidator = new Forms_DataValidator('4201');
        Forms_Validation_Result__c validationResult = new Forms_Validation_Result__c();
        
        Forms_DataValidator dataValidator1 = new Forms_DataValidator('4201');
        Forms_Validation_Result__c validationResult1 = new Forms_Validation_Result__c();
        
        Forms_DataValidator dataValidator2 = new Forms_DataValidator('4201');
        Forms_Validation_Result__c validationResult2 = new Forms_Validation_Result__c();
                
        test.starttest();
             
        validationResult  = dataValidator.validateData(formReq,lineItems);//TC_014
        System.assertNotEquals(validationResult.status__c,Forms_constant.SUCCESS);
        validationResult1 = dataValidator.validateData(invalidFormReq,lineItems1);//TC_012
        System.assertEquals(validationResult1.status__c,Forms_constant.FAILURE);
        validationResult2 = datavalidator.validatedata(formReq,null);//TC_013
        System.assertEquals(validationResult2.status__c,Forms_constant.FAILURE);        
        test.stoptest();
        
        
        system.debug('*********Validation Result'+validationResult);       
        system.debug('*********Validation Result Message '+validationResult.ErrorMessage__c);  
         
    }
    
    Static testmethod void test_ValidateFormDataInvalid()
    {
        Forms_TestDataUtil.insertForms_ErrorMessages();        
        Form_Request__c formReq;//TC_011,TC_012     
        List<Form_Request_Line_Item__c> lineItems;//TC_011,TC_013     
                        
        Forms_DataValidator dataValidator = new Forms_DataValidator('4201');
        Forms_Validation_Result__c validationResult = new Forms_Validation_Result__c();
        Forms_DataValidator dataValidator1 = new Forms_DataValidator('4000');
        Forms_Validation_Result__c validationResult1 = new Forms_Validation_Result__c();
        
        test.starttest();       
        validationResult  = dataValidator.validateData(formReq,lineItems);
        System.assertEquals(validationResult.status__c,Forms_constant.FAILURE); 
        validationResult1  = dataValidator1.validateData(formReq,lineItems);
        System.assertEquals(validationResult1.status__c,Forms_constant.FAILURE); 
        test.stoptest();
        
        system.debug('*********Validation Result Invalid'+validationResult);       
        system.debug('*********Validation Result Message '+validationResult.ErrorMessage__c);  
         
    } 
    
    static testmethod void test_validateDocument()
    {               
        Forms_TestDataUtil.insertForms_ErrorMessages();
        Form__c formObj = Forms_TestDataUtil.insertForm('4201');
        Forms_TestDataUtil.insertFormFieldsForResponse();
        List<Document_Request_Line_Item__c> lineItems = new List<Document_Request_Line_Item__c>();
        
        
        Document_Request__c docRequest = Forms_TestDataUtil.getDocumentRequest('4201');       
        Document_Request__c invalidDocReq = Forms_TestDataUtil.getInvalidDocReq('4201');
        
        Document_Request_Line_Item__c docReqLineItem = Forms_TestDataUtil.getDocREqLineItem(docRequest);
        lineItems.add(docReqLineItem);
        Forms_Validation_Result__c validationResult = new Forms_Validation_Result__c();       
        Forms_DataValidator dataValidator = new Forms_DataValidator('4201');
        
        Forms_Validation_Result__c validationResult1 = new Forms_Validation_Result__c();       
        Forms_DataValidator dataValidator1 = new Forms_DataValidator('4201');
        
        Forms_Validation_Result__c validationResult2 = new Forms_Validation_Result__c();       
        Forms_DataValidator dataValidator2 = new Forms_DataValidator('4201');
        
        Forms_Validation_Result__c validationResult3 = new Forms_Validation_Result__c();       
        Forms_DataValidator dataValidator3 = new Forms_DataValidator('4201');
        
        test.starttest(); 
        
        validationResult = dataValidator.validateDocumentData(docRequest,lineItems);//TC_036
        System.assertEquals(validationResult.status__c,Forms_constant.SUCCESS);             
        system.debug('*********Validation Result'+validationResult);       
        system.debug('*********Validation Result Message '+validationResult.ErrorMessage__c);

        validationResult1 = dataValidator1.validateDocumentData(invalidDocReq,lineItems);//TC_034
        System.assertEquals(validationResult1.status__c,Forms_constant.FAILURE);                
        system.debug('*********Validation Result1'+validationResult1);       
        system.debug('*********Validation Result1 Message '+validationResult1.ErrorMessage__c); 
        
        validationResult2 = dataValidator2.validateDocumentData(docRequest,null);//TC_35
        System.assertEquals(validationResult2.status__c,Forms_constant.FAILURE);                
        system.debug('*********Validation Result2'+validationResult2);       
        system.debug('*********Validation Result2 Message '+validationResult2.ErrorMessage__c); 
        
        try{
            //FormField to raise Exception in DataValidator class.
            Form_Field__c formFieldObj7= new Form_Field__c();
            formFieldObj7.Name='customSTring';
            formFieldObj7.Target_Field__c='CustomString4__c';
            formFieldObj7.Data_Type__c = 'Dummy';            
            formFieldObj7.source_system__c='ALFA';
            insert formFieldObj7;
            
            Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
            formFieldJunction.Form__c = formobj.Id;
            formFieldJunction.Form_Field__c = formFieldObj7.Id;
            formFieldJunction.required__c =true;
            insert formFieldJunction;
            docRequest.CustomString4__c = 'testCode';
            Forms_DataValidator dataValidator4 = new Forms_DataValidator('4201');
            validationResult3 = dataValidator4.validateDocumentData(docRequest,lineItems);
        }
        catch(Exception e)
        {
            System.debug('Error In TestClass'+e.getMessage());
            
        }
        Forms_DataValidator dataValidator5 = new Forms_DataValidator('4201');
        validationResult3 = dataValidator5.validateDocumentData(null,null); //TC_033
        //System.assertEquals(validationResult2.status__c,Forms_constant.FAILURE); 
        test.stoptest();
                        
    }        
   
    
}