AUGREL/src/objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <label>CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CurrentDueDate__c</fullName>
        <label>CurrentDueDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CustomString4__c</fullName>
        <label>CustomString4</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number__c</fullName>
        <label>Dealer Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewDueDate__c</fullName>
        <label>NewDueDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewPaymentAmount__c</fullName>
        <label>NewPaymentAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NextMonthPaymentAmount__c</fullName>
        <label>NextMonthPaymentAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recipient_NameLine1__c</fullName>
        <label>Recipient Name Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnEnvelope__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Return Envelope</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Document_Request_Line_Item__c.object
<CustomObject>
    <description>Extensions of snapshot data used to generate unique inputs for document processing in the Adobe Forms Service - used for fields that may be used many times as a child node in a single form generation.</description>
    <fields>
        <fullName>CoCustomer_MiddleName__c</fullName>
        <label>CoCustomer Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Request__c</fullName>
        <label>Document Request</label>
        <referenceTo>Document_Request__c</referenceTo>
        <relationshipLabel>Document Request Line Items</relationshipLabel>
        <relationshipName>Document_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Request Line Item</label>
    <nameField>
        <label>Document Request Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field__c.object
<CustomObject>
    <description>Represents fields that appear on forms in the Adobe Forms Service. The columns identify source objects and fields, the target field on Document Request, and special processing instructions.</description>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Forms_QueryConfig__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forms_QueryConfig</label>
        <referenceTo>Forms_QueryConfig__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_item_field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Checkbox to indicate whether field has multiplicity property and needs to be represented in document request line item.</description>
        <label>Line item field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Line_item_type__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Picklist for multiplicity fields to group together on one line item record when in the same node - value maps to Type field on document request line item.</description>
        <label>Line item type</label>
        <picklist>
            <controllingField>Line_item_field__c</controllingField>
            <picklistValues>
                <fullName>Co-Customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense Type</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>ALFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOGIC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The target field on the document request record or line item where the data will be stored.</description>
        <label>Target Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field_Junction__c.object
<CustomObject>
    <description>Junction object linking Forms with their Form Fields and supporting re-use of fields across forms.</description>
    <fields>
        <fullName>Form_Field__c</fullName>
        <label>Form Field</label>
        <referenceTo>Form_Field__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field if checked then the field is mandatory, if unchecked Field is optional.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Form-Field Junction</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Form-Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Field Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_QueryConfig__c.object
<CustomObject>
    <description>Forms_QueryConfig for SourceSystem=&apos;SFDC&apos; in Form_Field__c</description>
    <fields>
        <fullName>Document_Object_Field__c</fullName>
        <label>Document_Object_Field</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceAttribute__c</fullName>
        <label>ReferenceAttribute</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>Forms Query Configuration</label>
    <nameField>
        <label>QueryConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Query Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/FormServiceConfig__c.object
<CustomObject>
    <fields>
        <fullName>AttributeType__c</fullName>
        <label>AttributeType</label>
        <picklist>
            <picklistValues>
                <fullName>Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>String</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATETIME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Link_to_DocumentRequestLineItem_Object__c</fullName>
        <label>Link to DocumentRequestLineItem Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_to_Document_Request_Object__c</fullName>
        <description>The field which corresponds to this field in Document Request object</description>
        <label>Link to Document Request Object</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentNode__c</fullName>
        <label>ParentNode</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceAttribute__c</fullName>
        <label>ReferenceAttribute</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Form Service Configuration</label>
    <nameField>
        <label>AttributeName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Service Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_DocumentRequestDataMappingTest.cls
/*
#########################################################################################
Project Name        : TFS Forms Implementation
File                : Forms_DocumentRequestDataMappingTest
Version             : <1.0>
Created by          : Kaavya
Created Date        : 19/10/2015 
Last Modified by    : <NAME>
Last Modified Date  : <MM/DD/YYYY >
Description         : This class is the Test class for Forms_DocumentRequestDataMapping

Change Request History:
##########################################################################################
*/

@isTest
Public class Forms_DocumentRequestDataMappingTest{

    /* 
    Method Name:test_docReqMapping
    Method Signature/Inputs:Responsedatamap, Documentrequest object, Forms_DocumentDataHolder.
    Method Return Type/outputs:Test Method Pass/Fail
    Method Description:This method is to cover the mappingResponseToDocReq method positive scenario.
    */
    
 Static testmethod void test_docReqMapping(){
    Map<String,String> responseDataMap1 = new Map<String,String>();
    Map<String,String> responseDataMap2 = new Map<String,String>();
    Map<String,String> DataTypeMap = new Map<String,String>();
    list <FormServiceConfig__c> formServConfigList = new list <FormServiceConfig__c>();
    Forms_TestDataUtil.insertForms_ErrorMessages();
    list <Document_Request_Line_Item__c> docReqLIList = new list <Document_Request_Line_Item__c>();  
    
    FormServiceConfig__c formServObj = new FormServiceConfig__c();
    formServObj.ReferenceAttribute__c='nameline1';
    formServObj.Link_to_Document_Request_Object__c='Recipient_NameLine1__c';
    formServObj.ParentNode__c='response';
    formServObj.AttributeType__c='Response';
    formServObj.data_type__c='String';
    formServConfigList.add(formServObj);
    
    System.assertNotEquals(formServObj,NULL);
       
    FormServiceConfig__c formServObj2 = new FormServiceConfig__c();
    formServObj2.ReferenceAttribute__c='newduedate';
    formServObj2.Link_to_Document_Request_Object__c='NewDueDate__c';
    formServObj2.AttributeType__c='Response';
    formServObj2.ParentNode__c='response';
    formServConfigList.add(formServObj2);
    System.assertNotEquals(formServObj2,NULL);
    
    FormServiceConfig__c formServObj3 = new FormServiceConfig__c();
    formServObj3.ReferenceAttribute__c='newpaymentamount';
    formServObj3.Link_to_Document_Request_Object__c='NewPaymentAmount__c';
    formServObj3.AttributeType__c='Response';
    formServObj3.ParentNode__c='response';
    formServConfigList.add(formServObj3);
    System.assertNotEquals(formServObj3,NULL);
    
    FormServiceConfig__c formServObj4 = new FormServiceConfig__c();
    formServObj4.ReferenceAttribute__c='currentduedate';
    formServObj4.Link_to_Document_Request_Object__c='CurrentDueDate__c';
    formServObj4.AttributeType__c='Response';
    formServObj4.ParentNode__c='response';
    formServConfigList.add(formServObj4);
    System.assertNotEquals(formServObj4,NULL);
    insert formservconfiglist;
    
    list<Forms_QueryConfig__c> configQueryList = new list<Forms_QueryConfig__c>();
    Forms_QueryConfig__c query = new Forms_QueryConfig__c();
    query.Name = 'test';
    query.Document_Object_Field__c = 'newduedate';
    configQueryList.add(query);
    
    Forms_QueryConfig__c query1 = new Forms_QueryConfig__c();
    Forms_QueryConfig__c query2 = new Forms_QueryConfig__c();
    Forms_QueryConfig__c query3 = new Forms_QueryConfig__c();
    
    query1.Name = 'test';
    query1.Document_Object_Field__c = 'newpaymentamount';
    configQueryList.add(query1);
    
    query2.Name = 'test';
    query2.Document_Object_Field__c = 'currentduedate';
    configQueryList.add(query2);
    
    query3.Name = 'test';
    query3.Document_Object_Field__c = 'nameline1';
    configQueryList.add(query3);    
    insert configQueryList;
    
                    
    responseDataMap1.put('nameline1','test');
    responseDataMap1.put('newduedate','2015-10-23');
    responseDataMap1.put('currentduedate','2015-10-30');
    responseDataMap1.put('newpaymentamount','0.25');
    //DataTypeMap.put('nameline1', 'data_type__c');
  
    case caseobj = new case();
    caseobj.Status='New';
    caseobj.Origin='Email';
    caseobj.KM_Department__c='TestDepartment';
    caseobj.KM_Change_Category__c = 'TestCategory';
    caseobj.KM_Documentation_Impacted__c='TestDocumentation';
    insert caseobj;

    Document_Request__c docRequest = new Document_Request__c();
    docRequest.AccountNumber__c='70400100000010001';
    docRequest.CurrentDueDate__c=date.ValueOf('2015-10-29 00:00:00');
    docRequest.Dealer_Number__c='Dealer123';
    docRequest.Case__c= caseobj.id;
    docRequest.NextMonthPaymentAmount__c=2000.0;
    docRequest.language__c='english';
    insert docRequest;
    
    
    Document_Request_Line_Item__c docReqLI = new Document_Request_Line_Item__c();
    docReqLI.name = 'test';
    docReqLI.Document_Request__c = docRequest.id;
    docReqLIList.add(docReqLI);
    insert docReqLIList;
    
    Forms_DocumentDataHolder documentDat = new Forms_DocumentDataHolder();
    documentDat.setDocumentRequest(docRequest);
    documentDat.getLineItems();
    documentDat.setLineItems(docReqLIList);  
    responseDataMap2.put('middleName','test');
    Forms_DataValidator validator= new Forms_DataValidator('4201');
   
    Forms_TestDataUtil.insertForms_ErrorMessages();
    Form__c formObj = Forms_TestDataUtil.insertForm('4201');
    list<Form_Field_Junction__c> formFieldJuncList = new list<Form_Field_Junction__c>();
    Form_Field__c formFieldObj7= new Form_Field__c();
    formFieldObj7.Name='customSTring';
    formFieldObj7.Target_Field__c='CustomString4__c';
    formFieldObj7.Data_Type__c = 'Dummy';            
    formFieldObj7.source_system__c='ALFA';
    insert formFieldObj7;
    
    Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
    formFieldJunction.Form__c = formobj.Id;
    formFieldJunction.Form_Field__c = formFieldObj7.Id;
    formFieldJunction.required__c =true;
    formFieldJuncList.add(formFieldJunction);
    insert formFieldJuncList;
   
    test.startTest();            
    Forms_DocumentRequestDataMapping formObjMapping= new Forms_DocumentRequestDataMapping(); 
    formObjMapping.mappingResponseToDocReq(responseDataMap1,documentDat,formFieldJuncList); //TC_081,TC_084,TC_085
    formObjMapping.mappingResponseToDocReq(responseDataMap2,documentDat, formFieldJuncList); 
    formObjMapping.validateResponseData(validator,documentDat);
    formObjMapping.generateDmsXML(documentDat);
    test.stoptest();
    }
    
Static testmethod void test_docReqMappingconfigSet(){
    Map<String,String> responseDataMap1 = new Map<String,String>();
    Map<String,String> responseDataMap2 = new Map<String,String>();
    Map<String,String> DataTypeMap = new Map<String,String>();
    list <FormServiceConfig__c> formServConfigList = new list <FormServiceConfig__c>();
    Forms_TestDataUtil.insertForms_ErrorMessages();
    list <Document_Request_Line_Item__c> docReqLIList = new list <Document_Request_Line_Item__c>();  
    
    FormServiceConfig__c formServObj = new FormServiceConfig__c();
    formServObj.ReferenceAttribute__c='nameline1';
    //formServObj.Link_to_Document_Request_Object__c='Recipient_NameLine1__c';
    formServObj.ParentNode__c='response';
    formServObj.AttributeType__c='Response';
    formServObj.data_type__c='String';
    formServConfigList.add(formServObj);
    
    System.assertNotEquals(formServObj,NULL);
       
    FormServiceConfig__c formServObj2 = new FormServiceConfig__c();
    formServObj2.ReferenceAttribute__c='newduedate';
    //formServObj2.Link_to_Document_Request_Object__c='NewDueDate__c';
    formServObj2.AttributeType__c='Response';
    formServObj2.ParentNode__c='response';
    formServConfigList.add(formServObj2);
    System.assertNotEquals(formServObj2,NULL);
    
    FormServiceConfig__c formServObj3 = new FormServiceConfig__c();
    formServObj3.ReferenceAttribute__c='newpaymentamount';
    //formServObj3.Link_to_Document_Request_Object__c='NewPaymentAmount__c';
    formServObj3.AttributeType__c='Response';
    formServObj3.ParentNode__c='response';
    formServConfigList.add(formServObj3);
    System.assertNotEquals(formServObj3,NULL);
    
    FormServiceConfig__c formServObj4 = new FormServiceConfig__c();
    formServObj4.ReferenceAttribute__c='currentduedate';
    //formServObj4.Link_to_Document_Request_Object__c='CurrentDueDate__c';
    formServObj4.AttributeType__c='Response';
    formServObj4.ParentNode__c='response';
    formServConfigList.add(formServObj4);
    System.assertNotEquals(formServObj4,NULL);
    insert formservconfiglist;
    
    list<Forms_QueryConfig__c> configQueryList = new list<Forms_QueryConfig__c>();
    Forms_QueryConfig__c query = new Forms_QueryConfig__c();
    query.Name = 'test';
    query.Document_Object_Field__c = 'newduedate';
    //configQueryList.add(query);
    
    Forms_QueryConfig__c query1 = new Forms_QueryConfig__c();
    Forms_QueryConfig__c query2 = new Forms_QueryConfig__c();
    Forms_QueryConfig__c query3 = new Forms_QueryConfig__c();
    
    query1.Name = 'test';
    query1.Document_Object_Field__c = 'NextMonthPaymentAmount__c';
    configQueryList.add(query1);
    
    query2.Name = 'test';
    query2.Document_Object_Field__c = 'currentduedate';
    //configQueryList.add(query2);
    
    query3.Name = 'test';
    query3.Document_Object_Field__c = 'Recipient_NameLine1__c';
    configQueryList.add(query3);    
    insert configQueryList;
    
                    
    responseDataMap1.put('Recipient_NameLine1__c','test');
    //responseDataMap1.put('newduedate','2015-10-23');
    //responseDataMap1.put('currentduedate','2015-10-30');
    responseDataMap1.put('NextMonthPaymentAmount__c','0.25');
    //DataTypeMap.put('nameline1', 'data_type__c');
  
    case caseobj = new case();
    caseobj.Status='New';
    caseobj.Origin='Email';
    caseobj.KM_Department__c='TestDepartment';
    caseobj.KM_Change_Category__c = 'TestCategory';
    caseobj.KM_Documentation_Impacted__c='TestDocumentation';
    insert caseobj;

    Document_Request__c docRequest = new Document_Request__c();
    docRequest.AccountNumber__c='70400100000010001';
    docRequest.CurrentDueDate__c=date.ValueOf('2015-10-29 00:00:00');
    docRequest.Dealer_Number__c='Dealer123';
    docRequest.Case__c= caseobj.id;
    docRequest.NextMonthPaymentAmount__c=2000.0;
    docRequest.language__c='english';
    insert docRequest;
    
    
    Document_Request_Line_Item__c docReqLI = new Document_Request_Line_Item__c();
    docReqLI.name = 'test';
    docReqLI.Document_Request__c = docRequest.id;
    docReqLIList.add(docReqLI);
    insert docReqLIList;
    
    Forms_DocumentDataHolder documentDat = new Forms_DocumentDataHolder();
    documentDat.setDocumentRequest(docRequest);
    documentDat.getLineItems();
    documentDat.setLineItems(docReqLIList);  
    responseDataMap2.put('middleName','test');
    Forms_DataValidator validator= new Forms_DataValidator('4201');
   
    Forms_TestDataUtil.insertForms_ErrorMessages();
    Form__c formObj = Forms_TestDataUtil.insertForm('4201');
    list<Form_Field_Junction__c> formFieldJuncList = new list<Form_Field_Junction__c>();
    Form_Field__c formFieldObj7= new Form_Field__c();
    formFieldObj7.Name='customSTring';
    formFieldObj7.Target_Field__c='CustomString4__c';
    formFieldObj7.Data_Type__c = 'Dummy';            
    formFieldObj7.source_system__c='ALFA';
    insert formFieldObj7;
    
    Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
    formFieldJunction.Form__c = formobj.Id;
    formFieldJunction.Form_Field__c = formFieldObj7.Id;
    formFieldJunction.required__c =true;
    formFieldJuncList.add(formFieldJunction);
    insert formFieldJuncList;
   
    test.startTest();            
    Forms_DocumentRequestDataMapping formObjMapping= new Forms_DocumentRequestDataMapping(); 
    formObjMapping.mappingResponseToDocReq(responseDataMap1,documentDat,formFieldJuncList); //TC_081,TC_084,TC_085
    formObjMapping.mappingResponseToDocReq(responseDataMap2,documentDat, formFieldJuncList); 
    formObjMapping.validateResponseData(validator,documentDat);
    formObjMapping.generateDmsXML(documentDat);
    test.stoptest();
    }
    
    /*
    Method Name:test_docReqMapping2
    Method Return Type/outputs:Test Method Pass/Fail
    Method Description:This method is to cover the mappingResponseToDocReq method positive scenario.
    */
    
    Static testmethod void test_docReqMapping2(){
  
    Map<String,String> responseDataMap1 = new Map<String,String>();
    Map<String,String> responseDataMap2 = new Map<String,String>();
    Map<String,String> DataTypeMap = new Map<String,String>();
    list<FormServiceConfig__c> FSClist = new list<FormServiceConfig__c>();
    Forms_TestDataUtil.insertForms_ErrorMessages();
        
    FormServiceConfig__c formServObj = new FormServiceConfig__c();
    formServObj.ReferenceAttribute__c='nameline1';
    formServObj.Link_to_Document_Request_Object__c='Recipient_NameLine1__c';
    formServObj.ParentNode__c='response';
    formServObj.AttributeType__c='Response';
    formServObj.data_type__c='String';
    System.assertNotEquals(formServObj,NULL);
    FSClist.add(formServObj);
    
    
    FormServiceConfig__c formServObj2 = new FormServiceConfig__c();
    formServObj2.ReferenceAttribute__c='creationdate';
    formServObj2.Link_to_Document_Request_Object__c='CreatedDate__c';
    formServObj2.AttributeType__c='Response';
    formServObj2.ParentNode__c='Entity';
    System.assertNotEquals(formServObj2,NULL);
    FSClist.add(formServObj2);
    
    FormServiceConfig__c formServObj3 = new FormServiceConfig__c();
    formServObj3.ReferenceAttribute__c='IsReturnEnvelopeRequired';
    formServObj3.Link_to_Document_Request_Object__c='ReturnEnvelope__c';
    formServObj3.AttributeType__c='Response';
    formServObj3.ParentNode__c='Dispatch';
    System.assertNotEquals(formServObj3,NULL);
    FSClist.add(formServObj3);
    
    insert FSClist; 
    
    responseDataMap1.put('creationdate','2015-10-23 00:00:00');
    responseDataMap1.put('nameline1','test');
    responseDataMap1.put('IsReturnEnvelopeRequired', 'true');
       
    case caseobj = new case();
    caseobj.Status='New';
    caseobj.Origin='Email';
    caseobj.KM_Department__c='TestDepartment';
    caseobj.KM_Change_Category__c = 'TestCategory';
    caseobj.KM_Documentation_Impacted__c='TestDocumentation';
    insert caseobj;

    Document_Request__c docRequest = new Document_Request__c();
    docRequest.AccountNumber__c='70400100000010001';
    docRequest.CurrentDueDate__c=date.ValueOf('2015-10-29 00:00:00');
    docRequest.Dealer_Number__c='Dealer123';
    docRequest.Case__c= caseobj.id;
    docRequest.NextMonthPaymentAmount__c=2000.0;
    docRequest.language__c='english';
    insert docRequest;
    Forms_DocumentDataHolder documentDat = new Forms_DocumentDataHolder();
    documentDat.setDocumentRequest(docRequest); 
   
    Forms_TestDataUtil.insertForms_ErrorMessages();
    Form__c formObj = Forms_TestDataUtil.insertForm('4201');
    list<Form_Field_Junction__c> formFieldJuncList = new list<Form_Field_Junction__c>();
    Form_Field__c formFieldObj7= new Form_Field__c();
    formFieldObj7.Name='customSTring';
    formFieldObj7.Target_Field__c='CustomString4__c';
    formFieldObj7.Data_Type__c = 'Dummy';            
    formFieldObj7.source_system__c='ALFA';
    insert formFieldObj7;
    
    Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
    formFieldJunction.Form__c = formobj.Id;
    formFieldJunction.Form_Field__c = formFieldObj7.Id;
    formFieldJunction.required__c =true;
    formFieldJuncList.add(formFieldJunction);
    insert formFieldJuncList;
   
    test.startTest();            
    Forms_DocumentRequestDataMapping formObjMapping= new Forms_DocumentRequestDataMapping(); //TC_082,TC_083,TC_098,TC_099
    formObjMapping.mappingResponseToDocReq(responseDataMap1,documentDat, formFieldJuncList);    
    test.stoptest();
    }
    
    /* 
    Method Name:test_docreqlineitem
    Method Signature/Inputs:Responsedatamap, Documentrequest object, Forms_DocumentDataHolder.
    Method Return Type/outputs:Test Method Pass/Fail
    Method Description:This method is to cover the mappingResponseToDocReq method positive scenario with documentRequestLineItem object.
    */
    
    Static testmethod void test_docreqlineitem(){
    
    Map<String,String> responseDataMap1 = new Map<String,String>();
    Map<String,String> responseDataMap2 = new Map<String,String>();
    Map<String,String> DataTypeMap = new Map<String,String>();
    list<FormServiceConfig__c> FSClist = new list<FormServiceConfig__c>();
    Forms_TestDataUtil.insertForms_ErrorMessages();
    
    FormServiceConfig__c formServObj1 = new FormServiceConfig__c();
    formServObj1.ReferenceAttribute__c='cocustomer';
    formServObj1.Link_to_DocumentRequestLineItem_Object__c='CoCustomer_MiddleName__c';
    formServObj1.AttributeType__c='Response';
    formServObj1.ParentNode__c='Entity';
    System.assertNotEquals(formServObj1,NULL);
    FSClist.add(formServObj1);
    insert FSClist;
    
    responseDataMap1.put('cocustomer','test');
    
    case caseobj = new case();
    caseobj.Status='New';
    caseobj.Origin='Email';
    caseobj.KM_Department__c='TestDepartment';
    caseobj.KM_Change_Category__c = 'TestCategory';
    caseobj.KM_Documentation_Impacted__c='TestDocumentation';
    insert caseobj;

    Document_Request__c docRequest = new Document_Request__c();
    docRequest.AccountNumber__c='70400100000010001';
    docRequest.CurrentDueDate__c=date.ValueOf('2015-10-29 00:00:00');
    docRequest.Dealer_Number__c='Dealer123';
    docRequest.Case__c= caseobj.id;
    docRequest.NextMonthPaymentAmount__c=2000.0;
    docRequest.language__c='english';
    insert docRequest;
    Forms_DocumentDataHolder documentDat = new Forms_DocumentDataHolder();
    documentDat.setDocumentRequest(docRequest);
    
    
    Forms_TestDataUtil.insertForms_ErrorMessages();
    Form__c formObj = Forms_TestDataUtil.insertForm('4201');
    list<Form_Field_Junction__c> formFieldJuncList = new list<Form_Field_Junction__c>();
    Form_Field__c formFieldObj7= new Form_Field__c();
    formFieldObj7.Name='customSTring';
    formFieldObj7.Target_Field__c='CustomString4__c';
    formFieldObj7.Data_Type__c = 'Dummy';            
    formFieldObj7.source_system__c='ALFA';
    insert formFieldObj7;
    
    Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
    formFieldJunction.Form__c = formobj.Id;
    formFieldJunction.Form_Field__c = formFieldObj7.Id;
    formFieldJunction.required__c =true;
    formFieldJuncList.add(formFieldJunction);
    insert formFieldJuncList;
    test.startTest();            
    Forms_DocumentRequestDataMapping formObjMapping= new Forms_DocumentRequestDataMapping(); //TC_086,TC_087,TC_088,TC_096,TC_097
    formObjMapping.mappingResponseToDocReq(responseDataMap1,documentDat,formFieldJuncList);
    test.stoptest();
    
    }
    /* 
    Method Name:test_docReqEXC
    Method Signature/Inputs:Responsedatamap, Documentrequest object, Forms_DocumentDataHolder.
    Method Return Type/outputs:Test Method Pass/Fail
    Method Description:This method is to cover the mappingResponseToDocReq method negative scenario.
    */
    
    Static testmethod void test_docReqEXC(){
    Forms_TestDataUtil.insertForms_ErrorMessages();
    list<FormServiceConfig__c>  fsclist = new list<FormServiceConfig__c>();
    FormServiceConfig__c formServObj2 = new FormServiceConfig__c();
    formServObj2.ReferenceAttribute__c='IsReturnEnvelopeRequired';
    formServObj2.Link_to_Document_Request_Object__c='ReturnEnvelope__c';
    formServObj2.AttributeType__c='Response';
    formServObj2.ParentNode__c='Dispatch';
    System.assertNotEquals(formServObj2,NULL);
    fsclist.add(formServObj2);
      
    Map<String,String> responseDataMap2 = new Map<String,String>();
    FormServiceConfig__c formServObj5 = new FormServiceConfig__c();
    formServObj5.ReferenceAttribute__c='nextmonthlypaymentamount';
    formServObj5.Link_to_Document_Request_Object__c='NextMonthPaymentAmount__c';
    formServObj5.AttributeType__c='Response';
    formServObj5.ParentNode__c='response';
    System.assertNotEquals(formServObj5,NULL);
    fsclist.add(formServObj5);
    
    case caseobj = new case();
    caseobj.Status='New';
    caseobj.Origin='Email';
    caseobj.KM_Department__c='TestDepartment';
    caseobj.KM_Change_Category__c = 'TestCategory';
    caseobj.KM_Documentation_Impacted__c='TestDocumentation';
    insert caseobj;

    Document_Request__c docRequest = new Document_Request__c();
    docRequest.AccountNumber__c='70400100000010001';
    docRequest.CurrentDueDate__c=date.ValueOf('2015-10-29 00:00:00');
    docRequest.Dealer_Number__c='Dealer123';
    docRequest.Case__c= caseobj.id;
    docRequest.NextMonthPaymentAmount__c=2000.0;
    docRequest.language__c='english';
    insert docRequest;
    Forms_DocumentDataHolder documentDat = new Forms_DocumentDataHolder();
    documentDat.setDocumentRequest(docRequest);
    insert fsclist;
    //responseDataMap2.put('creationdate','2015-10-23 00:00:00');
    //responseDataMap2.put('IsReturnEnvelopeRequired','true');

    Forms_TestDataUtil.insertForms_ErrorMessages();
    Form__c formObj = Forms_TestDataUtil.insertForm('4201');
    list<Form_Field_Junction__c> formFieldJuncList = new list<Form_Field_Junction__c>();
    Form_Field__c formFieldObj7= new Form_Field__c();
    formFieldObj7.Name='customSTring';
    formFieldObj7.Target_Field__c='CustomString4__c';
    formFieldObj7.Data_Type__c = 'Dummy';            
    formFieldObj7.source_system__c='ALFA';
    insert formFieldObj7;
    
    Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
    formFieldJunction.Form__c = formobj.Id;
    formFieldJunction.Form_Field__c = formFieldObj7.Id;
    formFieldJunction.required__c =true;
    formFieldJuncList.add(formFieldJunction);
    insert formFieldJuncList;

    test.startTest();            
    Forms_DocumentRequestDataMapping formObjMapping= new Forms_DocumentRequestDataMapping(); //TC_089,TC_090,TC_091,TC_092,TC_093,TC_094,TC_095    
    formObjMapping.mappingResponseToDocReq(responseDataMap2,documentDat,formFieldJuncList);
    
    test.stoptest();
    }
    
    Static testmethod void test_Newmethod(){
    
    Map<String,String> responseDataMap1 = new Map<String,String>();    
    Map<String,String> docReqLineItemMap = new Map<STring,String>();
    Map<String,String> DataTypeMap = new Map<String,String>();
    list<FormServiceConfig__c> FSClist = new list<FormServiceConfig__c>();
    Forms_TestDataUtil.insertForms_ErrorMessages();
    
    FormServiceConfig__c formServObj1 = new FormServiceConfig__c();
    formServObj1.ReferenceAttribute__c='cocustomer';
    formServObj1.Link_to_DocumentRequestLineItem_Object__c='CoCustomer_MiddleName__c';
    formServObj1.AttributeType__c='Response';
    formServObj1.ParentNode__c='Entity';
    System.assertNotEquals(formServObj1,NULL);
    FSClist.add(formServObj1);
    insert FSClist;
    
    responseDataMap1.put('cocustomer','test');
    responseDataMap1.put('nameline1','test');
    responseDataMap1.put('newduedate','2015-10-23');
    responseDataMap1.put('currentduedate','2015-10-30');
    responseDataMap1.put('newpaymentamount','0.25');
    responseDataMap1.put('formID','4201');
    responseDataMap1.put(Forms_Constant.FORMNUMBER,'4201');
    docReqLineItemMap.put('Co-Customers','CustomString4__c');
    
    
    
    case caseobj = new case();
    caseobj.Status='New';
    caseobj.Origin='Email';
    caseobj.KM_Department__c='TestDepartment';
    caseobj.KM_Change_Category__c = 'TestCategory';
    caseobj.KM_Documentation_Impacted__c='TestDocumentation';
    insert caseobj;

    Document_Request__c docRequest = new Document_Request__c();
    docRequest.AccountNumber__c='70400100000010001';
    docRequest.CurrentDueDate__c=date.ValueOf('2015-10-29 00:00:00');
    docRequest.Dealer_Number__c='Dealer123';
    docRequest.Case__c= caseobj.id;
    docRequest.NextMonthPaymentAmount__c=2000.0;
    docRequest.language__c='english';
    insert docRequest;
    Forms_DocumentDataHolder documentDat = new Forms_DocumentDataHolder();
    documentDat.setDocumentRequest(docRequest);
    
    
    Forms_TestDataUtil.insertForms_ErrorMessages();
    Form__c formObj = Forms_TestDataUtil.insertForm('4201');
    list<Form_Field_Junction__c> formFieldJuncList = new list<Form_Field_Junction__c>();
    Form_Field__c formFieldObj7= new Form_Field__c();
    formFieldObj7.Name='customSTring';
    formFieldObj7.Target_Field__c='CustomString4__c';
    formFieldObj7.Line_item_field__c=true;
    formFieldObj7.Line_item_type__c ='Co-Customers';
    formFieldObj7.Data_Type__c = 'Dummy';            
    formFieldObj7.source_system__c='ALFA';
    insert formFieldObj7;
    
    Form_Field_Junction__c formFieldJunction = new Form_Field_Junction__c();
    formFieldJunction.Form__c = formobj.Id;
    formFieldJunction.Form_Field__c = formFieldObj7.Id;
    formFieldJunction.required__c =true;
    formFieldJuncList.add(formFieldJunction);
    insert formFieldJuncList;
    Forms_DocumentDataHolder documentData = new Forms_DocumentDataHolder();
    
    test.startTest();            
    Forms_DocumentRequestDataMapping formObjMapping= new Forms_DocumentRequestDataMapping();
    formObjMapping.mapResponseToDocReqLineItem(responseDataMap1,docReqLineItemMap,documentData);
    Forms_DataSelector.getMultiServicesJunctions(responseDataMap1,docReqLineItemMap);       
    test.stoptest();
    
    }   
  }