AUGREL/src/objects/Eligible_Offer__c.object
<CustomObject>
    <description>This is the Junction object between FA and Next Best Offer. This object stores the list of all eligible customers for an offer/Action</description>
    <fields>
        <fullName>Certificate_Number__c</fullName>
        <description>This is the certificate number that is generated for each eligible customer. Business will upload this data in Salesforce.</description>
        <label>Certificate Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_Date__c</fullName>
        <description>This is when the offer begins to be active for the FA</description>
        <label>Eligible Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date for the offer. This is the date when the offer is expired</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Financial Account to which it is related to</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Eligible Offers</relationshipLabel>
        <relationshipName>Eligible_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Best_Action__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Next Best Action it is related to</description>
        <label>Next Best Action</label>
        <referenceTo>Next_Best_Action__c</referenceTo>
        <relationshipLabel>Eligible Offers</relationshipLabel>
        <relationshipName>Eligible_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Eligible Offer</label>
    <nameField>
        <label>Eligible Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eligible Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Code_Edit_Message__c</fullName>
        <description>Edit message code</description>
        <label>Code Edit Message</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Reversed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_Code_Description__c</fullName>
        <label>Type Code Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease type of account</description>
        <label>Lease</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Next_Best_Action__c.object
<CustomObject>
    <description>This is the Master object to store all the Next Best Offer/Action that TFS has to offer</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Next Best Action and will be leveraged in Offer tab to display the description on what this offer is all about</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Next Best Action</label>
    <nameField>
        <label>Eligible Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Next Best Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_AutoLoyaltyTest.cls
@isTest
private class TFSC_AutoLoyaltyTest {

    static testMethod void myUnitTest() {
        	
    // create FA, Next Best Action, Eligible Offer
        Id faRecordTypeId = [select Id from recordType where sObjectType = 'Financial_Account__c' and name = 'Lease' limit 1].Id;
     	Financial_Account__c fa = new Financial_Account__c(name = 'FA',Finance_Account_Status__c = 'Open',
    			code_edit_message__c = '1000', type_code_description__c = 'NotActuarial', RecordTypeId=faRecordTypeId);
    	insert fa;
    	
    	Next_Best_Action__c nba = new Next_Best_Action__c(Description__c = 'Description');
    	insert nba;
    	
    	Eligible_Offer__c eo = new Eligible_Offer__c(Certificate_Number__c = '1000', Eligible_Date__c = date.today(), end_Date__c = date.today().addDays(90),
    		Financial_Account__c = fa.Id, Next_Best_Action__c = nba.Id);
    	insert eo;


		test.startTest();
		
        PageReference pr = Page.TFS_Auto_Loyalty_Universal_Console;
        Test.setCurrentPage(pr);     
        pr.getParameters().put('Id',fa.Id);
        TFSC_AutoLoyalty ctrl = new TFSC_AutoLoyalty();
        ctrl.servicegroup = 'test';
        
        //error coverage
        pr.getParameters().put('12345',fa.Id);
        ctrl = new TFSC_AutoLoyalty();
        
        
		test.stopTest();
        
    }
}