AUGREL/src/objects/Eligible_Offer__c.object
<CustomObject>
    <description>This is the Junction object between FA and Next Best Offer. This object stores the list of all eligible customers for an offer/Action</description>
    <fields>
        <fullName>Certificate_Number__c</fullName>
        <description>This is the certificate number that is generated for each eligible customer. Business will upload this data in Salesforce.</description>
        <label>Certificate Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_Date__c</fullName>
        <description>This is when the offer begins to be active for the FA</description>
        <label>Eligible Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date for the offer. This is the date when the offer is expired</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Financial Account to which it is related to</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Eligible Offers</relationshipLabel>
        <relationshipName>Eligible_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Best_Action__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Next Best Action it is related to</description>
        <label>Next Best Action</label>
        <referenceTo>Next_Best_Action__c</referenceTo>
        <relationshipLabel>Eligible Offers</relationshipLabel>
        <relationshipName>Eligible_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Eligible Offer</label>
    <nameField>
        <label>Eligible Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eligible Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>History_Counter_Days_Past_Due__c</fullName>
        <description>&quot;DPD</description>
        <label>Days Past Due</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount_Past_Due__c</fullName>
        <description>Past due amount</description>
        <label>Past Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date_Next__c</fullName>
        <description>next due payment date</description>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Refi_Pitch_Eligible_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>  This custom field is leveraged to identify if the Refinance Auto Loyalty offer is available for a Customer. Its populated by ETL</description>
        <label>Refi Pitch Eligible Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refi_Pitch_Treatment__c</fullName>
        <description>  This custom field is leverage to capture whether the Auto Loyalty offer was accepted by the Customer</description>
        <label>Refi Pitch Treatment</label>
        <picklist>
            <picklistValues>
                <fullName>Treatment Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Not Provided</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Due__c</fullName>
        <formula>IF(VALUE(History_Counter_Days_Past_Due__c) = 0,  
   Charges_Late__c + Charges_Miscellaneous__c +  Payment_Amount_Next__c , 
    IF(VALUE(History_Counter_Days_Past_Due__c) &gt;= 1, 
      Charges_Late__c + Charges_Miscellaneous__c + Payment_Amount_Past_Due__c +
      IF(AND(RecordType.Name = &quot;Retail&quot;, Payment_Date_Past_Due__c &lt; TODAY(), TODAY() &lt; Maturity_Date__c), 
         Payment_Amount_Scheduled__c ,  
		 IF(AND(RecordType.Name = &quot;Retail&quot;, OR(ISBLANK(Payment_Date_Past_Due__c ) , ISBLANK(Payment_Amount_Past_Due__c)),TODAY() &lt; Maturity_Date__c), 
			Payment_Amount_Next__c,  
			IF(AND(RecordType.Name = &quot;Lease&quot;,Payment_Date_Past_Due__c &lt; TODAY()), 
				Payment_Amount_Scheduled__c , 
				IF(AND(RecordType.Name = &quot;Lease&quot;, OR(ISBLANK(Payment_Date_Past_Due__c ) , ISBLANK(Payment_Amount_Past_Due__c))), 
					Payment_Amount_Next__c, 
				0)))),
         0)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Next_Best_Action__c.object
<CustomObject>
    <description>This is the Master object to store all the Next Best Offer/Action that TFS has to offer</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Next Best Action and will be leveraged in Offer tab to display the description on what this offer is all about</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Next Best Action</label>
    <nameField>
        <label>Eligible Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Next Best Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Service_Request_User_Group__c</fullName>
        <label>Service Request User Group</label>
        <picklist>
            <picklistValues>
                <fullName>ADM COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Solution Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDS System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Recovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Recovery System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate CRM Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Loyalty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Daily System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Control Clerk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBPP System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Management System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPAY System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOCUS General</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_AutoLoyalty.cls
/**
    * Leveraged for Auto Loyalty to display Offer tabs
    * @author: Abhishek Ballabh
    * @version: 1.0
*/

global with sharing class TFSC_AutoLoyalty {
   
    public String servicegroup{get;set;}
    public String offer{get;set;}
    public String financialAccountId {
        get {
            return ApexPages.currentPage().getParameters().get('Id');
        }
        set;
    }
    public Financial_Account__c financialAccount{get;set;}
    public string sergroup{get;set;}
     //Financial Account Customer: The current person spoken to or the primary co-borrower
    public Financial_Account_Customer__c financialAccountCustomer{get;set;}
    public List<item> dataList {get; set;}
    String URL;
    
   
    
   

    public TFSC_Autoloyalty() {
        
        if(isValidFinancialID()){
               
                // First Thing is to retrieve the current financial account record
                setFinancialAccountIdFromMainTab();
                // Also, set the financial account customer
                financialAccountCustomer = TFSC_Utils.getCoBorrowerFinancialAccountCustomerFromPhoneNumber(financialAccountId,'') ;
                }
                dataList = new List<item>();
                for (Eligible_Offer__c c : [select Id, Name, Eligible_Date__c, end_date__c, Next_Best_Action__r.description__c,Certificate_Number__c from Eligible_Offer__c where financial_account__c = :financialAccountId and eligible_Date__c<=TODAY and end_date__c> N_Days_Ago:30
                    order by createdDate desc limit 200]) {
                        dataList.add(new item(c.Id, c.Name,c.Next_Best_Action__r.description__c, c.Eligible_Date__c, c.end_date__c,c.Certificate_Number__c));
                    }
                }
            
    public Boolean isValidFinancialID() {
        if(financialAccountId == null || financialAccountId.length() < 15) {
            
            return false;
        }
        
        return true;
    }
    
     
    public void setFinancialAccountIdFromMainTab(){
        
        try{
        offer='Auto Loyalty';
        
        sergroup = [Select Service_Request_User_Group__c From User Where Id = :UserInfo.getUserId()][0].Service_Request_User_Group__c;
        system.debug('ServiceGroup: '+sergroup);
                Id faAccountId = Id.valueOf(financialAccountId);
                financialAccount = [
                            SELECT
                                        Id,
                                        Financial_Account_Number__c,
                                        Total_Amount_Due__c,
                                        Payment_Amount_Past_Due__c,
                                        Payment_Date_Next__c,
                                        History_Counter_Days_Past_Due__c,
                                        Refi_Pitch_Eligible_Flag__c,
                                        Refi_Pitch_Treatment__c
                            FROM
                                        Financial_Account__c
                            WHERE
                                        //Id = :faAccountId
                                        Id = :financialAccountId
                            LIMIT
                                        1
                ];
                
        }catch(Exception e){
          
        }
        
        //return null;
    }
    
    public class item {
        public Id recId  {get; set;}
        public String Name  {get; set;}
        public string Description {get; set;}
        public string Eligible_Date {get; set;}
        public string End_date {get; set;}
        public string Certificate {get; set;}
      
        
        public item(Id rId, string Name, string Description, Date Eligible_Date, Date End_Date, string Certificate) {
            this.recId = rId;
            this.Name = name;
            this.description = description;
            this.Eligible_date = Eligible_Date.format();
            this.End_date = End_Date.format();
            this.Certificate = Certificate;
        }
        }
}