AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_CoBorrowerExistOnFA.cls
/*
#########################################################################################

Project Name..........: TFS AB

File..................: <TFSC_CoBorrowerExistOnFA> 

Version...............: <1.0>

Created by............: INFOSYS TECHNOLOGIES

Created Date..........: <24/12/2015> 

Last Modified by......: <Megha Dalmia>

Last Modified Date....: <24/12/2015 >

Description...........: <This Class has been written for Returning the data if coborrower exist on Account>
##########################################################################################
*/
public with sharing class TFSC_CoBorrowerExistOnFA
{
@InvocableMethod(label='CoBorroweronFAExist' description='Returns data if coborrower exist on Account')

    public static List<Boolean> CoBorrowerOnAccount(List<String> faIds)
    {
        List<Boolean> CoBorrowerExist=new List<Boolean>();
        if(faIds!=null && faIDs.size()>0)
        {           
            List<Financial_Account_Customer__c> coBorrowers =new List<Financial_Account_Customer__c>();
            coBorrowers = [SELECT id, Customer_Role_Type__c, Borrower_Status__c 
                          FROM Financial_Account_Customer__c 
                          WHERE Financial_Account__c = :faIds 
                          AND Borrower_Status__c = 'Active' AND Customer_Role_Type__c!='0-Primary Borrower'];
                          
            if(coBorrowers!=null && coBorrowers.size()>0){
            CoBorrowerExist.add(True);
            }          
            else 
            CoBorrowerExist.add(False);  
        }
        return  CoBorrowerExist;
    }      
}