AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Code_Edit_Message__c</fullName>
        <description>Edit message code</description>
        <label>Code Edit Message</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master-Detail Relationship to dealership (Account)</description>
        <label>Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Collateral__r.Make__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_Code_Description__c</fullName>
        <label>Type Code Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Full_Name__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to concatenate the proper name field components from the related account object so the customer may be addressed by their full name in a letter or other communication.</description>
        <formula>IF(Account__r.IsPersonAccount,
  IF(!ISBLANK(TEXT(Account__r.Salutation)), TEXT(Account__r.Salutation) &amp; &quot; &quot;, &quot;&quot;) &amp;
  IF(!ISBLANK(Account__r.FirstName), Account__r.FirstName &amp; &quot; &quot;, &quot;&quot;) &amp;
  IF(!ISBLANK(Account__r.Middle_Name__pc), Account__r.Middle_Name__pc &amp; &quot; &quot;, &quot;&quot;) &amp;
  Account__r.LastName &amp;
  IF(!ISBLANK(Account__r.Name_Suffix__pc), &quot;, &quot; &amp; Account__r.Name_Suffix__pc, &quot;&quot;)
,
  Account__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Garage__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Make__c</formula>
        <label>(IVR) Make</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/TFS_Activity__c.object
<CustomObject>
    <description>Contains important data on customer activity</description>
    <fields>
        <fullName>Action__c</fullName>
        <description>This is the Action field that controls the Action Category Topic combination been leveraged for TFS</description>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Edit Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call to Action</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>This is the Category field that is used the ACT combination been leveraged for TFS</description>
        <label>Category</label>
        <picklist>
            <controllingField>Action__c</controllingField>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Modifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Service Technical Difficulty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1099</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excess Wear &amp; Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Profile Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Profile Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maturity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TFS/LFS Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loyalty/Retention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <description>Actual Name of the individual with whom the Agent is corresponding to regarding this activity.</description>
        <inlineHelpText>Actual Name of the individual with whom the Agent is corresponding to regarding this activity.</inlineHelpText>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealership</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities (Dealership)</relationshipLabel>
        <relationshipName>DealershipActivity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account Customer</label>
        <referenceTo>Financial_Account_Customer__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Name__c</fullName>
        <description>Name associated with the Contact that is selected when the Activityis created. Can be Dealer Name, Bank/Ins Name, or Relationship depending on the Contact Type selected. This field will not be populated if the Primary Borrower or Co-Borrower call.</description>
        <inlineHelpText>Name associated with the Contact that is selected when the Activity is created. Can be Dealer Name, Bank/Ins Name, or Relationship depending on the Contact Type selected.</inlineHelpText>
        <label>Relationship Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Recipient__c</fullName>
        <label>Service Recipient</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <inlineHelpText>How contact was made with customer.</inlineHelpText>
        <label>Service Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Inbound Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Correspondence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/UC_NewRelatedActivityController.cls
public with sharing class UC_NewRelatedActivityController {

     
    // jhicks 1/25/16
    // Copied the UC_NewCaseController.  Removed any unnecessary code, but kept the high level
    // sObject variables (eg "newCase", "savedCase") so that we could use the same VF markup for both objects.
      
    private String activityType {get; Set;} 
    public Financial_Account__c   FA  {get; set;}
    public Financial_Account_Customer__c   FAC  {get; set;}
    
    public TFS_Activity__c newCase {get; set;}
    public TFS_Activity__c savedCase {get; set;}
    public string   selectedContact  {get; set;}
    public boolean showContactName {get; set;}
    public string relationshipName {get; set;}
    public boolean customerCorrespondence {get; set;}
    private boolean updateRelationship = false;     // determines if relationship should get updated.  set to true after initialization processes
    
    public boolean saveSuccessful {get; set;}
    public boolean pageIsVisible {get; set;}
    public boolean isActivity {get; set;}
    public List<selectOption> contacts {get; set;}
    private Financial_Account_Customer__c primaryBorrower = new Financial_Account_Customer__c();
    private Financial_Account_Customer__c coBorrower = new Financial_Account_Customer__c();
    // case fields
    public Map<String, List<Schema.FieldSetMember>> fieldSetMap;
    public List<Schema.FieldSetMember> fields {get; set;}
    
    // fa fields
    public Map<String, List<Schema.FieldSetMember>> faFieldSetMap;
    public List<Schema.FieldSetMember> faFields {get; set;}
    public string accountStatus  {get; set;}
    
    // fac fields
    public Map<String, List<Schema.FieldSetMember>> facFieldSetMap;
    public List<Schema.FieldSetMember> facFields {get; set;}
    public boolean facReadOnly {get; set;}
    
    
    public string sessionInfo {get; set;}
    public string action {get; set;}
    public string ServiceChannel{get; set;}
    public string   tempServiceChannel  {get; set;} 
    private string originalRecordType;
    private Case parentCase;
    
      
    public UC_NewRelatedActivityController(apexPages.standardController controller) {
        
        // CASE is the standard controller
        
        string caseId = controller.getId();
        parentCase = [select Id, financial_account__c, financial_account_customer__c,financial_account_customer__r.financial_account_customer__c, caseNumber, action__c, category__c, service_request_type__c,
                             service_type__c,status, service_recipient__c, contact_name__c, relationship_name__c from Case 
                      where id = :caseId];

            string FAId = parentCase.financial_account__c;
            FA = [select Id,name, recordTypeId, recordType.name, code_edit_message__c, type_code_description__c,
                   make__c, dealership__r.name from Financial_Account__c where Id = : FAId limit 1 ];
                   
        system.debug(fa);
        system.debug(parentCase);
        if(parentcase.service_type__c =='Customer Correspondence' || parentcase.service_type__c =='Action Request')
        {
        ServiceChannel=parentCase.service_type__c;
        tempServiceChannel =parentCase.service_type__c;
        }   
        init();
        
    }
    
    public void init() {
        facReadOnly = true;
        saveSuccessful = false;
        pageIsVisible = true;
        customerCorrespondence = false;

        try {
            primaryBorrower = [select Id,Customer_Full_Name__c,Home_Phone_Garage__c  from Financial_Account_Customer__c  where Financial_Account__c =  : fa.Id 
            and Customer_Role_Type__c = '0-Primary Borrower' and Borrower_Status__c = 'Active' limit 1];
        }
        catch(exception e){}
        
        try {coBorrower = [select Id,Customer_Full_Name__c,Home_Phone_Garage__c  from Financial_Account_Customer__c where Financial_Account__c =  : fa.Id 
            and  Customer_Role_Type__c = '6-Co-Borrower' and Borrower_Status__c = 'Active'  limit 1];
        }
        catch(exception e){}
        
        newCase();
    }
    

      
    
    public void getFields() {
    }   
    

    private void newCase() {
        
        string recordType = 'TFS Activity';
 
        Schema.DescribeSObjectResult obj = Schema.SObjectType.TFS_Activity__c;   
        Map<String,Schema.RecordTypeInfo>caseActivityTypeMap = obj.getRecordTypeInfosByName();
        
        newCase = new TFS_Activity__c(Financial_Account__c = FA.Id, recordTypeId= caseActivityTypeMap.get(recordType).getRecordTypeId(), 
             action__c = parentCase.action__c, category__c = parentCase.category__c, topic__c = parentCase.service_request_type__c,
                 case__c = parentCase.Id, financial_account_customer__c = ParentCase.financial_account_customer__c,
                 Financial_Account_Customer_ID__c = ParentCase.financial_account_customer__r.financial_account_customer__c,
                 status__c = ParentCase.status,  
                 contact_name__c = parentCase.contact_name__c, relationship_name__c = parentCase.relationship_name__c);

          //W-000215 Added Interaction Type - modified jhicks 1/28
  
        // get interaction info
        string faId = FA.Id;
        faId = faId.substring(0,15);
  
        try {
             tempinteraction__c ti = [select Interaction_Type__c, ani__c, conn_id__c from tempinteraction__c 
                                        where name = :faId and createdById = :userInfo.getUserId() limit 1];
             newCase.ani__c = ti.ani__c;
             newCase.conn_Id__c = ti.conn_id__c;
             if(ti.Interaction_Type__c=='undefined' && ti.ani__c==null)
             {
             ti.interaction_Type__c = 'Outbound Call';
             }
             newCase.Service_Type__c= ti.Interaction_Type__c;
        }
        catch(exception e){}
  
        originalRecordType = recordType;
        showContactName = false;
        populateContacts();  
        getFields();  
        system.debug(newCase);    
    }

    public void checkRecordType() {}
    
    public void cancelCase() {
        fields = new List<Schema.FieldSetMember> (); 
        newCase();
    }    
      
    // after case is saved & console is refreshed, reset this to false for next case
    public void resetSaveSuccessful() {
        saveSuccessful = false;
    }
    
    public void populateContacts () {
            contacts = new List<selectOption>();
            
            for (Financial_Account_Customer__c fac : [Select Id, Name, Customer_Role_Type__c From Financial_Account_Customer__c 
                where Financial_Account__c = :FA.Id and (Customer_Role_Type__c = '0-Primary Borrower' or Customer_Role_Type__c = '6-Co-Borrower')
                and Borrower_Status__c = 'Active'
                order by Customer_Role_Type__c]) {
                contacts.add(new selectOption(fac.Customer_Role_Type__c.substring(2), fac.Name));
            }
            
            // W-000195 - add additional contacts           
            contacts.add(new selectOption('Non-Signing Spouse', 'Non-Signing Spouse'));
            contacts.add(new selectOption('Third Party', 'Third Party'));
            contacts.add(new selectOption('Dealer', 'Dealer'));
            contacts.add(new selectOption('Bank/Insurance', 'Bank/Insurance'));
            contacts.add(new selectOption('TFS Team Member', 'TFS Team Member'));
            
            
            selectedContact = parentCase.service_recipient__c;
            setShowContact();
             system.debug('++++ selectedContact: ' + selectedContact);
 
 
    }  
  public void setShowContact() {
    
      system.debug('+++selectedContact: ' + selectedContact);
            
      if(selectedContact == 'Primary Borrower') {
         newCase.Financial_Account_Customer__c = primaryBorrower.Id;
         newCase.contact_name__c = primaryBorrower.Customer_Full_Name__c;
         showContactName = false;
         relationshipName = '';
         newCase.relationship_name__c = '';
      }
      
      else if (selectedContact == 'Co-Borrower') {
         newCase.Financial_Account_Customer__c = coBorrower.Id;
         newCase.contact_name__c = coBorrower.Customer_Full_Name__c;
         showContactName = false;
         relationshipName = '';
         newCase.relationship_name__c = '';
        
      } 
      else {
         newCase.Financial_Account_Customer__c = primaryBorrower.Id;
         //newCase.contact_name__c = null;
         showContactName = true;   
         relationshipName = '';
         if (updateRelationship)  {   //Contact has changed so clear out the relationship name and contact name
                 newCase.relationship_name__c = '';
                 newCase.contact_name__c = '';
         }
         if (selectedContact == 'Third Party')
            relationshipName = 'Relationship' ;
         else if (selectedContact == 'Dealer')  
            relationshipName = 'Dealer Name' ;   
         else if(selectedContact == 'Bank/Insurance')  
            relationshipName = 'Bank/Ins Name' ; 
         else if(selectedContact == 'TFS Team Member') 
            showContactName = false;   
              
        
      }
       
      system.debug('++++ contact name set: ' +  newCase.contact_name__c);
      system.debug('+++ showContactName: ' + showContactName);
      newCase.service_recipient__c = selectedContact;
      system.debug('+++newCase.service_recipient: : ' +  newCase.service_recipient__c);
      
      system.debug('++++ newCae after setShowContact(): ' + newCase);
      updateRelationship = true;
   }
    
    
   public void clearMessage() {}
   
   private void setDefaults() {
       //if (this.customerCorrespondence)  // in case no interation record
           // newCase.Service_Type__c = 'Customer Correspondence';
   }
    public void ServiceChannel() {
      if(ServiceChannel!=tempServiceChannel){
      if(ServiceChannel=='Customer Correspondence'){
            newCase.Service_Type__c='Customer Correspondence';
        }else if(ServiceChannel=='Action Request'){
            newCase.Service_Type__c='Action Request';
        }
        
       
       }else{
            ServiceChannel=null;
            newCase.Service_Type__c=null;
       }
        tempServiceChannel=newCase.Service_Type__c;
    }
   public PageReference createCase() {
        system.debug('**********   CREATE CASE ***************');
        setDefaults();
         // get interaction info
        string faId = FA.Id;
        faId = faId.substring(0,15);
        //W-000215 Added Interaction Type
        try {
             tempinteraction__c ti = [select Interaction_Type__c, ani__c, conn_id__c from tempinteraction__c 
                                        where name = :faId and createdById = :userInfo.getUserId() limit 1];
             if(ti!=null){
                 newCase.ani__c = ti.ani__c;
                 newCase.conn_Id__c = ti.conn_id__c;
                 if(ti.Interaction_Type__c=='undefined' && ti.ani__c==null)
             {
             ti.interaction_Type__c = 'Outbound Call';
             }
             //if (this.customerCorrespondence){
                // newCase.Service_Type__c = 'Customer Correspondence';
                 //}   else{
             
                  newCase.Service_Type__c = ti.Interaction_Type__c;
             // }
          }
        }
        catch(exception e){newCase.Service_Type__c = ServiceChannel;}
     
        // insert the case
         
        savePoint sp = Database.setSavepoint();
         ServiceChannel=null;
        tempServiceChannel=null;
        if(newcase.service_type__c==null)
        {
            newcase.service_type__c='Action Request';
        }
        TFS_Activity__c caseBeforeInsert = newCase.clone(false, true);   // in case there is an error in FAC update. this is deep clone.
        system.debug('+++ caseBeforeInsert1: ' + caseBeforeInsert);
            
        if ( insertCase()) {
             savedCase = newCase;
             newCase();
             
        }
        else {
            
            Database.rollback(sp);
            system.debug('+++ caseBeforeInsert2: ' + caseBeforeInsert);
            newCase = caseBeforeInsert;
            system.debug('+++ Case Restored: ' + newCase);
        }
  
        return null;
    }     
    
    
    public boolean insertCase() {
          
        try {
            
            System.debug('**** the inserted Case: '+newCase);
           if (newCase.contact_name__c == null && selectedContact != 'TFS Team Member')
                throw new DMLException('Please enter a value for Contact Name.');
            insert newCase; 
 
           SaveSuccessful = true; 
           return true;  

        } catch(System.Exception ex){
           string message = ex.getMessage().replace('First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION,','');
           message = message.replace(': []','');
  
            system.debug('exception: ' + ex);
            system.debug('message: ' + message);          
          // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, message));
            apexPages.addMessages(ex);
            system.debug('apexPages.message: ' +new ApexPages.Message(ApexPages.Severity.ERROR, message) );

             SaveSuccessful = false;
            
            system.debug('+++ Save Successful: ' + SaveSuccessful);
            return false;
        } 
    } 

}