AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Code_Edit_Message__c</fullName>
        <description>Edit message code</description>
        <label>Code Edit Message</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Reversed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flag_Office_Of_Foreign_Asset_Control__c</fullName>
        <label>Flag Office Of Foreign Asset Control</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NULL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PND</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Affiliate_Marketing__c</fullName>
        <description>Affiliate Marketing Flag</description>
        <label>Affiliate Marketing</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Affiliate_Sharing__c</fullName>
        <description>Affiliate Sharing Flag</description>
        <label>Affiliate Sharing</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Dealership__c</fullName>
        <description>Dealer Privacy Flag</description>
        <label>Toyota/Lexus Dealer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_FCRA_Sharing__c</fullName>
        <description>FCRA Sharing Flag</description>
        <label>Credit App/Rpt</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Telemarketing__c</fullName>
        <description>Telemarketing Flag</description>
        <label>TFS Telemarketing</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Third_Party_Sharing__c</fullName>
        <description>Third Party Sharing Flag</description>
        <label>3rd Party</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Latest Title on the Financial Account</description>
        <label>Title</label>
        <referenceTo>Title__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_Code_Description__c</fullName>
        <label>Type Code Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease type of account</description>
        <label>Lease</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flag_Office_Of_Foreign_Asset_Control__c</fullName>
        <label>Flag Office Of Foreign Asset Control</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Affiliate_Marketing__c</fullName>
        <description>Affiliate Marketing Flag</description>
        <label>Affiliate Marketing</label>
        <picklist>
            <picklistValues>
                <fullName>OUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Affiliate_Sharing__c</fullName>
        <description>Affiliate Sharing Flag</description>
        <label>Affiliate Sharing</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Dealership__c</fullName>
        <description>Dealer Privacy Flag</description>
        <label>Toyota/Lexus Dealer</label>
        <picklist>
            <picklistValues>
                <fullName>OUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_FCRA_Sharing__c</fullName>
        <description>FCRA Sharing Flag</description>
        <label>Credit App/Rpt</label>
        <picklist>
            <picklistValues>
                <fullName>OUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Telemarketing__c</fullName>
        <description>Telemarketing Flag</description>
        <label>TFS Telemarketing</label>
        <picklist>
            <picklistValues>
                <fullName>OUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Third_Party_Sharing__c</fullName>
        <description>Third Party Sharing Flag</description>
        <label>3rd Party</label>
        <picklist>
            <picklistValues>
                <fullName>OUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/TFS_Activity__c.object
<CustomObject>
    <description>Contains important data on customer activity</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account Customer</label>
        <referenceTo>Financial_Account_Customer__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Title__c.object
<CustomObject>
    <description>This object contains Title info. It will be related to the  FA.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Collateral that is related to the FA</description>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FA Account that this Title record belongs to</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title_Status__c</fullName>
        <description>Depicts the status of the Title.</description>
        <label>Title Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending-Not Yet Received</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Title</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/UC_Account_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the icon and message displayed based on FinAcct Code_Edit_Message__c</description>
    <fields>
        <fullName>Icon__c</fullName>
        <description>Identifies the icon to display.</description>
        <inlineHelpText>Identifies the icon to display.</inlineHelpText>
        <label>Icon</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Message__c</fullName>
        <description>Message to display in hover in Salesforce.</description>
        <inlineHelpText>Message to display in hover in Salesforce.</inlineHelpText>
        <label>Salesforce Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UC Account Status</label>
</CustomObject>

AUGREL/src/objects/UC_Unbound_Field_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Add input fields to publishers which do not correspond to a field in the schema</description>
    <fields>
        <fullName>Display_Label__c</fullName>
        <label>Display Label</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UC Unbound Field List</label>
</CustomObject>

AUGREL/src/classes/UC_NewActivitiesTestClass.cls
@isTest
public with sharing class UC_NewActivitiesTestClass {
  

	static Collateral__c collateral;
	static Account acct;
	static Account acct2;
	static Financial_Account__c fa;
	static Financial_Account__c fa2;
	static Financial_Account__c fa3;
	static List<Financial_Account_Customer__c> fac ;
	static List<Financial_Account_Customer__c> fac2 ;
	static Case parentCase;
	
    /* Note: References to "newCase" in this class are actually a TFS_Activity__c in the controller */
    
    static testMethod void testCallToAction() {
        /********************** create data *********************/
     	
    	collateral = new Collateral__c(name = 'Toyota');
    	insert collateral;
    	
    	title__c t1 = new Title__c(title_status__c = 'Held', collateral__c = collateral.id);
    	insert t1;
    	
    	acct = new Account(name = 'John Doe');
    	insert acct;
    	
    	acct2 = new Account(name = 'Mary Doe');
    	insert acct2;
    	
    	UC_Account_Status__c acctStatus = new UC_Account_Status__c(name='1000', Icon__c = 'Green', Salesforce_Message__c='test');
    	insert acctStatus;
    	
    	Id faRecordTypeId = [select Id from recordType where sObjectType = 'Financial_Account__c' and name = 'Lease' limit 1].Id;
    	fa = new Financial_Account__c(name = 'FA', collateral__c = collateral.Id, title__c = t1.id, Finance_Account_Status__c = 'Close',
    			code_edit_message__c = '1000', type_code_description__c = 'NotActuarial', RecordTypeId=faRecordTypeId);
    	insert fa;
    	
    	
    	t1.title_status__c = 'whatever';
    	fa2 = new Financial_Account__c(name = 'FA2', collateral__c = collateral.Id, title__c = t1.id 	);
    	insert fa2;
    	
    	fa3 = new Financial_Account__c(name = 'FA2', collateral__c = collateral.Id, title__c = t1.id);
    	insert fa3;
    	
    	fac = new List<Financial_Account_Customer__c>();
    	fac.add(new Financial_Account_Customer__c(name = 'FAC1', financial_account__c = fa.id, account__c = acct.Id,
    				Customer_Role_Type__c = '0-Primary Borrower', Borrower_Position__c = 'Primary', Borrower_Status__c='ACTIVE' ));
    				
    	fac.add(new Financial_Account_Customer__c(name = 'FAC2', financial_account__c = fa.id, account__c = acct2.Id,
    				Customer_Role_Type__c = '6-Co-Borrower', Borrower_Position__c = 'Co-X', Borrower_Status__c='ACTIVE',
			      	Privacy_Election_Third_Party_Sharing__c='Y' , Privacy_Election_Affiliate_Marketing__c='Y' , Privacy_Election_Dealership__c='Y'  ,
			    	Privacy_Election_Telemarketing__c='Y'  , Flag_Office_Of_Foreign_Asset_Control__c='Y', Privacy_Election_Affiliate_Sharing__c='Y' ,
			    	Privacy_Election_FCRA_Sharing__c='Y'   				
    				
    				));
    	insert fac; 
    	
    	UC_Unbound_Field_List__c ub = new UC_Unbound_field_List__c (Name='1',display_label__c = 'unbound', action__c='Start Process', category__c = 'Lease End',
    	     Topic__c = 'Direct Sales');
    	insert ub;           // used for Direct Sales test
    	
    	string faId = fa.id;
    	faId = faId.substring(0,15);
    	tempInteraction__c ti = new tempInteraction__c(name = faId, Interaction_Type__c = 'Inbound Call', ani__c='9999999999');
    	insert ti;
      	
    	Id recordTypeId = [select Id from recordType where sObjectType = 'Case' and name = 'UC - Request Information' limit 1].Id;
     	parentCase = new Case(financial_account__c = fa.Id, financial_account_customer__c = fac[0].Id,  action__c='Request Information', category__c='Fees', 
    				service_request_type__c = 'Disposition Fee',service_type__c='Inbound Call', Description = 'Description', recordTypeId = recordTypeId);
    	insert parentCase; 	
    	
          

        /*******************************************************/
        
        
    	test.startTest();
    	
        PageReference pr = Page.UC_NewActivityCallToAction;
        pr.getParameters().put('Id',fa.Id);
        Test.setCurrentPage(pr);     
        ApexPages.StandardController ctrl = new ApexPages.StandardController(fa);
        UC_NewActivityController actCtrl = new UC_NewActivityController(ctrl);
        
        actCtrl.CallToAction();
    
        actCtrl.cancelCase();  // coverage
        actCtrl.newCase.category__c = 'Programs';
        actCtrl.newCase.Service_Request_Type__c = 'College Rebate Exceptions';
        actCtrl.newCase.Description__c = 'College Rebate';
        actCtrl.selectedContact = 'Co-Borrower';
        actCtrl.clearMessage();   // coverage
        actCtrl.setShowContact();
        
        actCtrl.createCase();
        
        
        test.stopTest();
    	
    }
  
     static testMethod void testRelatedActivity() {
    	
       /********************** create data *********************/
     	
    	collateral = new Collateral__c(name = 'Toyota');
    	insert collateral;
    	
    	title__c t1 = new Title__c(title_status__c = 'Held', collateral__c = collateral.id);
    	insert t1;
    	
    	acct = new Account(name = 'John Doe');
    	insert acct;
    	
    	acct2 = new Account(name = 'Mary Doe');
    	insert acct2;
    	
    	UC_Account_Status__c acctStatus = new UC_Account_Status__c(name='1000', Icon__c = 'Green', Salesforce_Message__c='test');
    	insert acctStatus;
    	
    	Id faRecordTypeId = [select Id from recordType where sObjectType = 'Financial_Account__c' and name = 'Lease' limit 1].Id;
    	fa = new Financial_Account__c(name = 'FA', collateral__c = collateral.Id, title__c = t1.id, Finance_Account_Status__c = 'Close',
    			code_edit_message__c = '1000', type_code_description__c = 'NotActuarial', RecordTypeId=faRecordTypeId);
    	insert fa;
    	
    	
    	t1.title_status__c = 'whatever';
    	fa2 = new Financial_Account__c(name = 'FA2', collateral__c = collateral.Id, title__c = t1.id 	);
    	insert fa2;
    	
    	fa3 = new Financial_Account__c(name = 'FA2', collateral__c = collateral.Id, title__c = t1.id);
    	insert fa3;
    	
    	fac = new List<Financial_Account_Customer__c>();
    	fac.add(new Financial_Account_Customer__c(name = 'FAC1', financial_account__c = fa.id, account__c = acct.Id,
    				Customer_Role_Type__c = '0-Primary Borrower', Borrower_Position__c = 'Primary', Borrower_Status__c='ACTIVE' ));
    				
    	fac.add(new Financial_Account_Customer__c(name = 'FAC2', financial_account__c = fa.id, account__c = acct2.Id,
    				Customer_Role_Type__c = '6-Co-Borrower', Borrower_Position__c = 'Co-X', Borrower_Status__c='ACTIVE',
			      	Privacy_Election_Third_Party_Sharing__c='Y' , Privacy_Election_Affiliate_Marketing__c='Y' , Privacy_Election_Dealership__c='Y'  ,
			    	Privacy_Election_Telemarketing__c='Y'  , Flag_Office_Of_Foreign_Asset_Control__c='Y', Privacy_Election_Affiliate_Sharing__c='Y' ,
			    	Privacy_Election_FCRA_Sharing__c='Y'   				
    				
    				));
    	insert fac; 
    	
    	UC_Unbound_Field_List__c ub = new UC_Unbound_field_List__c (Name='1',display_label__c = 'unbound', action__c='Start Process', category__c = 'Lease End',
    	     Topic__c = 'Direct Sales');
    	insert ub;           // used for Direct Sales test
    	
    	string faId = fa.id;
    	faId = faId.substring(0,15);
    	tempInteraction__c ti = new tempInteraction__c(name = faId, Interaction_Type__c = 'Inbound Call', ani__c='9999999999');
    	insert ti;
      	
    	Id recordTypeId = [select Id from recordType where sObjectType = 'Case' and name = 'UC - Request Information' limit 1].Id;
     	parentCase = new Case(financial_account__c = fa.Id, financial_account_customer__c = fac[0].Id,  action__c='Request Information', category__c='Fees', 
    				service_request_type__c = 'Disposition Fee',service_type__c='Inbound Call', Description = 'Description', recordTypeId = recordTypeId);
    	insert parentCase; 	
    	
         /*******************************************************/
    	test.startTest();
        PageReference pr = Page.UC_NewRelatedActivity;
        pr.getParameters().put('Id',parentCase.Id);
        Test.setCurrentPage(pr);   
    	
        ApexPages.StandardController ctrl = new ApexPages.StandardController(ParentCase);
        UC_NewRelatedActivityController actCtrl = new UC_NewRelatedActivityController(ctrl);
        
        actCtrl.checkRecordType();
        actCtrl.clearMessage();
        actCtrl.cancelCase();
        actCtrl.newCase.Description__c = 'An Activity';
        actCtrl.createCase();
        
        List <TFS_Activity__c> acts = [select Id from TFS_Activity__c];
        delete acts;
         
        
        //additional coverage
  
        actCtrl.fac = fac[0];
        actCtrl.isActivity = true;
        actCtrl.sessionInfo = 'test';
        actCtrl.action = 'test';
        List<Financial_Account_Customer__c> acctsToDelete = [select Id from Financial_Account_Customer__c];
        delete acctsToDelete;
        
        
        ctrl = new ApexPages.StandardController(ParentCase);
        actCtrl = new UC_NewRelatedActivityController(ctrl);
        
        actCtrl.resetSaveSuccessful();
        actCtrl.newCase = new TFS_Activity__c();
        actCtrl.insertCase();    //error
        
        test.stopTest();
    	
    }
     
}