AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_CoBorroweronFATest.cls
/*
#########################################################################################

Project Name..........: TFS AB

File..................: <TFSC_CoBorroweronFATest> 

Version...............: <1.0>

Created by............: INFOSYS TECHNOLOGIES

Created Date..........: <24/12/2015> 

Last Modified by......: <Megha Dalmia>

Last Modified Date....: <24/12/2015 >

Description...........: <This Test Class has been written for the test coverage of TFSC_CoBorrowerExistOnFA class>
##########################################################################################
*/
@isTest
private class TFSC_CoBorroweronFATest
    {
    //Setup test data
    Static List<String> testFAId = new List<String>();
    private static void setupTestFA()
    {    
        Financial_Account__c FA=new Financial_Account__c(Name='Account1', Financial_Account_Number__c = '12345');
        Insert FA;
        Account acc= new Account(name='CoBorrower');
        Insert acc;
        Financial_Account_Customer__c fac=new Financial_Account_Customer__c(Customer_Role_Type__c='1-CoBorrower', Borrower_Status__c= 'Active' , Financial_Account__c=FA.Id, account__c=acc.id);  
        Insert fac;
    } 

    private static void setupTestFAC()
    {    
        Financial_Account__c FAnoCB=new Financial_Account__c(Name='Account1', Financial_Account_Number__c = '123456');
        Insert FAnoCB;
        Account accBo= new Account(name='Borrower');
        Insert accBo;
        Financial_Account_Customer__c facnoCB=new Financial_Account_Customer__c(Customer_Role_Type__c='0-Primary Borrower', Borrower_Status__c= 'Active' , Financial_Account__c=FAnoCB.Id, account__c=accBo.id);  
        Insert facnoCB;
    }     
    static testmethod void CoBorroweronFATest()
    {
        TFSC_CoBorroweronFATest.setupTestFA();      
        Financial_Account__c testFA=[SELECT id  FROM Financial_Account__c where Financial_Account_Number__c='12345'];
        String testFAIds = String.ValueOf(testFA.Id);          
        testFAId.add(testFAIds);   
        Test.startTest();
        List<Boolean> CoBorrExist = TFSC_CoBorrowerExistOnFA.CoBorrowerOnAccount(testFAId); 
        System.assertequals(True,CoBorrExist[0] );      
        Test.stopTest();
    }
    
    static testmethod void CoBorrowerNotonFATest()
    {
        TFSC_CoBorroweronFATest.setupTestFAC();      
        Financial_Account__c testFA=[SELECT id  FROM Financial_Account__c where Financial_Account_Number__c='123456'];
        String testFAIds = String.ValueOf(testFA.Id);          
        testFAId.add(testFAIds);   
        Test.startTest();
        List<Boolean> CoBorrExist = TFSC_CoBorrowerExistOnFA.CoBorrowerOnAccount(testFAId); 
        System.assertequals(False,CoBorrExist[0] );      
        Test.stopTest();
    }
 
 }