AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Latest Title on the Financial Account</description>
        <label>Title</label>
        <referenceTo>Title__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Full_Name__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to concatenate the proper name field components from the related account object so the customer may be addressed by their full name in a letter or other communication.</description>
        <formula>IF(Account__r.IsPersonAccount,
  IF(!ISBLANK(TEXT(Account__r.Salutation)), TEXT(Account__r.Salutation) &amp; &quot; &quot;, &quot;&quot;) &amp;
  IF(!ISBLANK(Account__r.FirstName), Account__r.FirstName &amp; &quot; &quot;, &quot;&quot;) &amp;
  IF(!ISBLANK(Account__r.Middle_Name__pc), Account__r.Middle_Name__pc &amp; &quot; &quot;, &quot;&quot;) &amp;
  Account__r.LastName &amp;
  IF(!ISBLANK(Account__r.Name_Suffix__pc), &quot;, &quot; &amp; Account__r.Name_Suffix__pc, &quot;&quot;)
,
  Account__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Title__c.object
<CustomObject>
    <description>This object contains Title info. It will be related to the  FA.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Collateral that is related to the FA</description>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Communications__c</fullName>
        <description>Communication sent to the customer regarding the Title</description>
        <label>Customer Communications</label>
        <picklist>
            <picklistValues>
                <fullName>Sent Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent Bill of Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent CLAH Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent GAP Letter</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Mail_Date__c</fullName>
        <description>Date when Title is expected to be mailed to the customer</description>
        <label>Estimated Mail Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FA Account that this Title record belongs to</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Reason__c</fullName>
        <description>Reason why the Title is being hold off</description>
        <label>Hold Reason</label>
        <picklist>
            <controllingField>Title_Status__c</controllingField>
            <picklistValues>
                <fullName>Band2 Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BK No Closing Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSG Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat/Rebook/SCRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Overpayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misapplied Pmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Acct-Title Not Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Contract/DMS Folder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No ODO/Missing Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Within Maturity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total Loss-Addr Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payoff_Date__c</fullName>
        <description>last payoff date</description>
        <label>Payoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Send_To__c</fullName>
        <description>Option to whom the Title should be send to</description>
        <label>Send To</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Originating Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title_Notes__c</fullName>
        <description>Notes from Agents related to Title</description>
        <label>Title Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title_State__c</fullName>
        <label>Title State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title_Status__c</fullName>
        <description>Depicts the status of the Title.</description>
        <label>Title Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending-Not Yet Received</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title_Type__c</fullName>
        <description>Indicates the type of Title</description>
        <label>Title Type</label>
        <picklist>
            <picklistValues>
                <fullName>Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lien Release</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Holds the Tracking number of the shipped Title</description>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Title</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/UC_Title_Update_Est_Mailing__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Values for calculating Est Mailing Date</description>
    <fields>
        <fullName>Hold_Reason__c</fullName>
        <label>Hold Reason</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_State__c</fullName>
        <label>Title State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>UC Title Update Est Mailing</label>
</CustomObject>

AUGREL/src/classes/UC_UpdateCaseController.cls
/**
	* UC_UpdateCaseController - Controller for updating Cases
	* Created by BrainEngine Cloud Studio
	* @author: Clayton Bruckert
	* @version: 1.0
*/

public with sharing class UC_UpdateCaseController{
	public Case thisCase {get; set;}
    public boolean saveSuccessful {get; set;}
    public boolean pageIsVisible {get; set;}
	public Boolean showTitleUpdate {get; Set;}
	public Boolean showControlButtons {get; Set;}
	private ApexPages.StandardController thisCon;
	
	public Title__c thisTitle {get; Set;}
	public Financial_Account_Customer__c PrimaryBorrower {get; Set;}
	public Financial_Account_Customer__c CoBorrower {get; Set;}
	public Financial_Account__c FA {get; Set;}
	
	public UC_UpdateCaseController(ApexPages.StandardController con){
		thisCon = con;
		init();
	}
	
	private void init(){
		pageIsVisible=true;
		showControlButtons = true;
		showTitleUpdate = false;
		saveSuccessful = false;
		
		thisCase = [Select Authorization_Received__c, Customer_Communications__c, Estimated_Mail_Date__c, Mailing_Account__c, CaseNumber,
							Payoff_Date__c, Payoff_Method__c, Send_To__c, Send_to_Name_Address__c, Tracking_Number__c, Financial_Account__c, 
							Financial_Account_Customer__c, Service_Type__c 
					FROM Case 
					WHERE Id =: thisCon.getId()];
		
		try {
            PrimaryBorrower = [select Id  
						from Financial_Account_Customer__c  
						where Financial_Account__c =: thisCase.Financial_Account__c 
            				and Customer_Role_Type__c = '0-Primary Borrower' 
							and Borrower_Status__c = 'Active' limit 1];
        }
        catch(exception e){}
        
        try {CoBorrower = [select Id,Customer_Full_Name__c  
						from Financial_Account_Customer__c 
						where Financial_Account__c =: thisCase.Financial_Account__c 
            				and  Customer_Role_Type__c = '6-Co-Borrower' 
							and Borrower_Status__c = 'Active'  limit 1];
        }
        catch(exception e){}
		
        try {FA = [select id 
						from Financial_Account__c 
						where id =: thisCase.Financial_Account__c];
        }
        catch(exception e){}
		//
		System.debug('*** retrieved borrower: '+PrimaryBorrower);
		System.debug('*** retrieved coborrower: '+CoBorrower);
		System.debug('*** retrieved fa: '+FA);
	}
	// on page actions
	// Title Update Actions
    public void updateTitle() {
	    showTitleUpdate=true;
		
		List<Title__c> relatedTitles = [select Title_State__c, Title_Type__c, Title_Notes__c, Collateral__r.name, Payoff_Date__c, 
							Customer_Communications__c, Hold_Reason__c, Title_Status__c, Payoff__c, Estimated_Mail_Date__c, 
							APO_Received__c, Send_To__c , Title_Send_To_Address__c, Mail_Acct_Num__c, Tracking_Number__c	
					FROM title__c 
					WHERE Id IN (SELECT title__c FROM financial_account__c WHERE id =: thisCase.Financial_Account__c)];
		if(relatedTitles.size()>0){
			thisTitle = relatedTitles[0];
			System.debug('**** the selected title is: ' + relatedTitles);
			// update case values
			thisCase.Payoff_Method__c = thisTitle.Payoff__c;
			thisCase.Payoff_Date__c = thisTitle.Payoff_Date__c;
			
			CalcEstMailingDate();
		}else{
			String message = 'The current FA has no primary title assigned to it \b Please assign a title and try again.';
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, message));
			showTitleUpdate = false;
			showControlButtons = false;
		}
    }
    public void SendToUpdate(){
		UC_NewCase_SendTo AddUpdate = new UC_NewCase_SendTo(thisCase, PrimaryBorrower, CoBorrower, FA);
		AddUpdate.FillAddress();
	}
	public void CalcEstMailingDate(){
		//even if Est Mail Date is populated this will set the date
		System.debug('**** hold reason: ' + ThisTitle.Hold_Reason__c);
		if(thisTitle != null){
			if(ThisCase.Payoff_Date__c==null && ThisTitle.Hold_Reason__c!=null){
				ThisCase.Estimated_Mail_Date__c = null;
			}else if(ThisTitle.Title_Status__c=='Ready to be Released'){
				ThisCase.Estimated_Mail_Date__c = date.today().addDays(1);
			}else if(ThisTitle.Title_Status__c=='Released'){
				ThisCase.Estimated_Mail_Date__c = date.today();
			}else{
				if(thisTitle.Hold_Reason__c!='') ThisCase.Estimated_Mail_Date__c = DecideOnMailingDate();
			}	
		}
	}
	private Date DecideOnMailingDate(){
		date result = Date.today();
		
		LIST<UC_Title_Update_Est_Mailing__c> mailingRules = [Select Id, Name, Hold_Reason__c, Days_to_Add__c, Title_State__c 
					from UC_Title_Update_Est_Mailing__c 
					WHERE Hold_Reason__c =: thisTitle.Hold_Reason__c];
		if(mailingRules != null){
			System.debug('**** the mailing rules are: '+mailingRules);
			if(mailingRules.size()==1){
				// if there is only one rule then add the days, but if the days is blank return null
				if(mailingRules[0].Days_to_Add__c>0){
					return thisCase.Payoff_Date__c.addDays((integer)mailingRules[0].Days_to_Add__c);
				}else{
					return null;
				}
			}else if(mailingRules.size()>1){
				// for multiple rules on a single hold reason: Look through the list for a matching state and then return. 
				// If no state matches return the value of the record with a blank state
				for (UC_Title_Update_Est_Mailing__c mailRule: mailingRules){
					if(thisTitle.Title_State__c == mailRule.Title_State__c){
						result = thisCase.Payoff_Date__c.addDays((integer)mailRule.Days_to_Add__c);
						return result;
					}else if(mailRule.Title_State__c == null){
						result = thisCase.Payoff_Date__c.addDays((integer)mailRule.Days_to_Add__c);
					}
				}
			}else{
				return null;
			}
		}else{
			return null;
		}
		return result;
	}
	// on page buttons
	public void cancelCase(){}
	public PageReference updateCase(){
    	// if this is a title release then update the title fields
		if(showTitleUpdate){
			thisTitle.Payoff_Date__c = thisCase.Payoff_Date__c;
			thisTitle.Payoff__c = thisCase.Payoff_Method__c;
			thisTitle.Customer_Communications__c = thisCase.Customer_Communications__c;
			thisTitle.Estimated_Mail_Date__c = thisCase.Estimated_Mail_Date__c;
			if(thisCase.Authorization_Received__c == 'Yes - Written' || thisCase.Authorization_Received__c == 'Yes - Verbal') thisTitle.APO_Received__c = 'Yes';
			if(thisCase.Authorization_Received__c == 'No') thisTitle.APO_Received__c = 'No';
			if(thisCase.Authorization_Received__c == 'N/A') thisTitle.APO_Received__c = 'N/A';
			thisTitle.Send_To__c = thisCase.Send_To__c;
			thisTitle.Title_Send_To_Address__c = thisCase.Send_to_Name_Address__c;
			thisTitle.Mail_Acct_Num__c = thisCase.Mailing_Account__c;
			thisTitle.Tracking_Number__c = thisCase.Tracking_Number__c;
		}
		
		// update the case
         
        savePoint sp = Database.setSavepoint();
        Case caseBeforeInsert = thisCase.clone(false, true);   // in case there is an error in this is deep clone.
        system.debug('+++ caseBeforeInsert1: ' + caseBeforeInsert);
	
            
        if (doUpdate()){
        }else{            
            Database.rollback(sp);
            system.debug('+++ caseBeforeInsert2: ' + caseBeforeInsert);
            thisCase = caseBeforeInsert;
            system.debug('+++ Case Restored: ' + thisCase);
        }
  
		return null;
	}
    public boolean doUpdate() {
          
        try{
        	System.debug('**** the updated Case: '+thisCase);
           	update thisCase; 
			
			if(showTitleUpdate) update thisTitle;
              
        	System.debug('**** the updated Title__c: '+thistitle);
           SaveSuccessful = true; 
           return true;  

        } catch(System.Exception ex){
           string message = ex.getMessage().replace('First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION,','');
           message = message.replace(': []','');
  
            system.debug('exception: ' + ex);
            system.debug('message: ' + message);          
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, message));
            system.debug('apexPages.message: ' +new ApexPages.Message(ApexPages.Severity.ERROR, message) );

             SaveSuccessful = false;
            
            system.debug('+++ Save Successful: ' + SaveSuccessful);
            return false;
        }
    } 
}