AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Code_Edit_Message__c</fullName>
        <description>Edit message code</description>
        <label>Code Edit Message</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Reversed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Privacy_Election_Third_Party_Sharing__c</fullName>
        <description>Third Party Sharing Flag</description>
        <label>3rd Party</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Latest Title on the Financial Account</description>
        <label>Title</label>
        <referenceTo>Title__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_Code_Description__c</fullName>
        <label>Type Code Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease type of account</description>
        <label>Lease</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Loan type of account</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/Title__c.object
<CustomObject>
    <description>This object contains Title info. It will be related to the  FA.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Collateral that is related to the FA</description>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FA Account that this Title record belongs to</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_Reason__c</fullName>
        <description>Reason why the Title is being hold off</description>
        <label>Hold Reason</label>
        <picklist>
            <controllingField>Title_Status__c</controllingField>
            <picklistValues>
                <fullName>Band2 Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BK No Closing Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSG Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat/Rebook/SCRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Overpayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misapplied Pmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Acct-Title Not Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Contract/DMS Folder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No ODO/Missing Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Within Maturity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total Loss-Addr Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payoff_Date__c</fullName>
        <description>last payoff date</description>
        <label>Payoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Send_To__c</fullName>
        <description>Option to whom the Title should be send to</description>
        <label>Send To</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Originating Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title_State__c</fullName>
        <label>Title State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title_Status__c</fullName>
        <description>Depicts the status of the Title.</description>
        <label>Title Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending-Not Yet Received</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pulled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Title</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/UC_Account_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the icon and message displayed based on FinAcct Code_Edit_Message__c</description>
    <fields>
        <fullName>Icon__c</fullName>
        <description>Identifies the icon to display.</description>
        <inlineHelpText>Identifies the icon to display.</inlineHelpText>
        <label>Icon</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Message__c</fullName>
        <description>Message to display in hover in Salesforce.</description>
        <inlineHelpText>Message to display in hover in Salesforce.</inlineHelpText>
        <label>Salesforce Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UC Account Status</label>
</CustomObject>

AUGREL/src/objects/UC_Title_Update_Est_Mailing__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Values for calculating Est Mailing Date</description>
    <fields>
        <fullName>Hold_Reason__c</fullName>
        <label>Hold Reason</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_State__c</fullName>
        <label>Title State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>UC Title Update Est Mailing</label>
</CustomObject>

AUGREL/src/classes/UC_UpdateCaseControllerTest.cls
/**
	* UC_UpdateCaseControllerTest - <description>
	* @author: Clayton Bruckert
	* @version: 1.0
*/

@isTest
private  class UC_UpdateCaseControllerTest {
	static Collateral__c collateral;
    
	static title__c t1;
	
	static Account acct;
    static Account acct2;
    static Account acct3;
    
    static Financial_Account__c fa;
    static Financial_Account__c fa2;
    static Financial_Account__c fa3;
    static List<Financial_Account_Customer__c> fac ;
    static List<Financial_Account_Customer__c> fac2 ;
	
	static UC_Title_Update_Est_Mailing__c mailRule1;
	static UC_Title_Update_Est_Mailing__c mailRule2;
	static UC_Title_Update_Est_Mailing__c mailRule3;
    
    static Case testCase;
    
    static testmethod void UpdatePIFTitleCase(){
        createBaseData();
        test.startTest();
		t1.Financial_Account__c = fa.Id;
		update t1;
		
		RecordType useRecordType = [Select Name, Id from RecordType WHERE Name = 'UC - Title Release' limit 1];
        testCase = new Case(Financial_Account__c = fa.id, Financial_Account_Customer__c = fac.get(0).id, Service_Recipient__c = 'Borrower/Customer', 
                           Service_Type__c='Inbound Call', Contact_Name__c = 'testing person', PIF_Group__c = 'Retail Portal', Title__c = fa.Title__c,
                           Status = 'In Process', Action__c = 'Start Process', Category__c = 'Title', Service_Request_Type__c = 'PIF Release', 
                           Admin_Group__c = 'Default',Subject = 'Title - PIF Release', Description = 'testing update functionality', RecordTypeId = useRecordType.id);
		System.debug('*** new Case: '+testCase);
      	insert testCase;
		
        // open VF page
        UC_UpdateCaseController cont = new UC_UpdateCaseController(new ApexPages.StandardController(testCase));
		
        PageReference updateCasePage = Page.UC_UpdateCaseTitle;
        Test.setCurrentPage(updateCasePage);
		cont.updateTitle();
		// populate fields
		cont.thisCase.Payoff_Date__c = Date.today();
		cont.thisCase.Payoff_Method__c = 'Certified';
		cont.thisCase.Send_To__c = 'Customer';
		cont.thisCase.Authorization_Received__c = 'No';
		// test est. mailing
		cont.thisTitle.Title_State__c='FL';
		cont.CalcEstMailingDate();
		
		cont.thisTitle.Hold_Reason__c = 'Not Within Maturity';
		cont.CalcEstMailingDate();
		
		cont.thisTitle.Hold_Reason__c = 'Not Within Maturity';
		cont.thisTitle.Title_State__c = 'UT';
		cont.CalcEstMailingDate();
			
        // update case
		cont.cancelCase();
		cont.SendToUpdate();
		PageReference updatedCase = cont.updateCase();
        // verify results
        test.stopTest();
    }
    
    
    static void createBaseData() {
		collateral = new Collateral__c(Name = 'Toyota');
		insert collateral;
		
       	t1 = new Title__c(title_status__c = 'Held', Hold_Reason__c = 'Band2 Review', collateral__c = collateral.id);
      	insert t1;
      	
        Id acctRecordType = [select Id from recordtype where sObjectType = 'Account' and name = 'Customer' limit 1].Id;
      
      	acct = new Account(firstName = 'John', lastName = 'Doe',recordTypeId = acctRecordType,Social_Security_Number__pc='123123123');
      	insert acct;
      
      	acct2 = new Account(firstName = 'Mary', lastName = 'Doe',recordTypeId = acctRecordType,Social_Security_Number__pc='456456456');
      	insert acct2;
      
      	acct3 = new Account(firstName = 'Mary', lastName = 'Doe',recordTypeId = acctRecordType,Social_Security_Number__pc='123123123');
      	insert acct3;
      
      	UC_Account_Status__c acctStatus = new UC_Account_Status__c(name='1000', Icon__c = 'Green', Salesforce_Message__c='test');
      	insert acctStatus;
      
      	Id faRecordTypeId = [select Id from recordType where sObjectType = 'Financial_Account__c' and name = 'Lease' limit 1].Id;
 
      	fa = new Financial_Account__c(name = 'FA', collateral__c = collateral.Id, Title__c = t1.id, Finance_Account_Status__c = 'Open',
          	code_edit_message__c = '1000', type_code_description__c = 'NotActuarial', RecordTypeId=faRecordTypeId);
      	insert fa;
      	System.debug('*** the first FA: '+fa);
      	t1.title_status__c = 'whatever';
      	fa2 = new Financial_Account__c(name = 'FA2', collateral__c = collateral.Id,  RecordTypeId=faRecordTypeId   );
      	insert fa2;
      
      	fa3 = new Financial_Account__c(name = 'FA3', collateral__c = collateral.Id, RecordTypeId=faRecordTypeId);
      	insert fa3;
      
      	fac = new List<Financial_Account_Customer__c>();
      	fac.add(new Financial_Account_Customer__c(name = 'FAC1000', financial_account__c = fa.id, account__c = acct.Id,
            Customer_Role_Type__c = '0-Primary Borrower', Borrower_Position__c = 'Primary', Borrower_Status__c='ACTIVE',
            financial_account_customer__c = 'FAC1000'));
            
      	fac.add(new Financial_Account_Customer__c(name = 'FAC2000', financial_account__c = fa.id, account__c = acct2.Id,
            Customer_Role_Type__c = '6-Co-Borrower', Borrower_Position__c = 'Co-X', Borrower_Status__c='ACTIVE',
              Privacy_Election_Third_Party_Sharing__c='Y' , Privacy_Election_Affiliate_Marketing__c='Y' , Privacy_Election_Dealership__c='Y'  ,
            Privacy_Election_Telemarketing__c='Y' ,
            financial_account_customer__c = 'FAC2000'             
            ));

      	// create second acct for John Doe      
      	fac.add(new Financial_Account_Customer__c(name = 'FAC3000', financial_account__c = fa2.id, account__c = acct.Id,
            Customer_Role_Type__c = '0-Primary Borrower', Borrower_Position__c = 'Primary', Borrower_Status__c='ACTIVE',
            financial_account_customer__c = 'FAC3000'));
  
      	system.debug('**** fac[0] ' + fac[0]);
      	system.debug('**** fac[1] ' + fac[1]);
      	system.debug('**** fac[2] ' + fac[2]);  
              
      	insert fac; 
      
      	fac = [select name,  account__r.name, financial_Account__r.name, Account__r.Social_Security_Number__pc from financial_account_customer__c];

      	mailRule1 = new UC_Title_Update_Est_Mailing__c(Name = 'rule 1', hold_reason__c = 'Band2 Review', Days_to_Add__c = 10.0, Title_State__c = 'FL');
		insert mailRule1;
      	mailRule2 = new UC_Title_Update_Est_Mailing__c(Name = 'rule 2', hold_reason__c = 'Not Within Maturity', Days_to_Add__c = 9.0, Title_State__c = 'UT');
		insert mailRule2;
      	mailRule3 = new UC_Title_Update_Est_Mailing__c(Name = 'rule 3', hold_reason__c = 'Not Within Maturity', Days_to_Add__c = 7.0, Title_State__c = '');
		insert mailRule3;
    }
}