AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_DNC_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_DNC_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Mobile_Phone_DNC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_DNC_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_DNC_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/UC_CeaseAndDeaseFlowUtilTest.cls
@isTest
private class UC_CeaseAndDeaseFlowUtilTest {
	static testMethod void getFinancialAccountIdTest() {
     	Test.startTest();
     
		String facNumber = '123testfac';
		Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
		Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);

		System.assertEquals( UC_CeaseAndDeaseFlowUtil.getFinancialAccountId(dbFinancialAccount.Financial_Account_Number__c),
		                    UC_CeaseAndDeaseFlowUtil.getFinancialAccountId(financialAccount.Financial_Account_Number__c)
		                  );

		Test.stopTest();
    
   	}
   
    static testMethod void getFinancialAccountIdsTest() {     
     	Test.startTest();
     
		String facNumber = '123testfac';
		Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
		Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);

		System.assertEquals( UC_CeaseAndDeaseFlowUtil.getFinancialAccountIds(dbFinancialAccount.Financial_Account_Number__c).size(),
		                    UC_CeaseAndDeaseFlowUtil.getFinancialAccountIds(financialAccount.Financial_Account_Number__c).size()
                  );
       
       
     	Test.stopTest();    
   	}	
   
   
   
   	static testMethod void getFinancialAccountCustomersTest() {
     
		Test.startTest();

		String facNumber = '123testfac';
		Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
		Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);

		System.assertEquals((UC_CeaseAndDeaseFlowUtil.getFinancialAccountCustomers(dbFinancialAccount.Financial_Account_Number__c)).size(),
		                    0);

		Test.stopTest();
   	}	
   
   
   	static testMethod void getDNCConsentDataTest() {     
		Test.startTest();

		String facNumber = '123testfac';
		Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
		Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);

		System.assertEquals(UC_CeaseAndDeaseFlowUtil.getDNCConsentData(dbFinancialAccount.Financial_Account_Number__c, 'Primary'),
					null);
       
       Test.stopTest();
   	}
   
   
    static testMethod void getFlagBankruptcyTest() {     
     	Test.startTest();
     
		String facNumber = '123testfac';
		Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
		Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);

		System.assertEquals(UC_CeaseAndDeaseFlowUtil.getFlagBankruptcy(dbFinancialAccount.Financial_Account_Number__c, 'Primary'),
				null);
		
 		Test.stopTest();    
   }
   
   
   
   	static testMethod  void updateFlagBankruptcyTest() {                                       
		Test.startTest();

		String financialAccountNumber = '123testfac' ;
		String borrowerPosition = 'Primary';
		String bkValue ='BK';
		Financial_Account__c financialAccount = insertFinancialAccount(financialAccountNumber);
		Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);
		
		try {
		 	UC_CeaseAndDeaseFlowUtil.updateFlagBankruptcy(dbFinancialAccount.Financial_Account_Number__c, 'Primary', 'BK');
		}
		catch (Exception e) {
		  	System.debug(e);			
		}                       
		  
 		Test.stopTest();
    }
   
    static testMethod void getActivityCodeDescTest() {
     	Test.startTest();
		System.assertEquals(UC_CeaseAndDeaseFlowUtil.getActivityCodeDesc('DNC1'),null );
	 	Test.stopTest();     
    }
    
    static testMethod void  getDNCStrTest() { 
		Test.startTest();
		System.assertEquals(UC_CeaseAndDeaseFlowUtil.getDNCStr('a:b'),'' );
		Test.stopTest();
    }
    
    static testMethod void getCaseIdTest() {
		Test.startTest();
		
		String facNumber = '123testfac';
		Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
		Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);
		
		System.assertEquals(FlowUtil.getCaseId(dbFinancialAccount.Id),null );

		Test.stopTest();

    }
    //getDNCMap
    static testMethod void getDNCMapTest() {
     
     	Test.startTest();
       	String input = 'true,true,false,false';
       	System.assertEquals(UC_CeaseAndDeaseFlowUtil.getDNCMap(input) == null, false );
       
       	String borrowerPosition = 'Primary';
       	List<String> recs = input.split(',');
       	Integer loc = 0;
       	Map<String,Boolean> valueDNCMap = new Map<String,Boolean>();
       	for (String rec: recs) {
       		if (0 == loc && null != rec && 'true' == rec) {
	            valueDNCMap.put('Flag_Home_Phone_DNC_Garage__c', true);
	        }
	        System.assertEquals(valueDNCMap.get('Flag_Home_Phone_DNC_Garage__c'), true);
	        
	        if (1 == loc && null != rec && 'true' == rec) {
            	valueDNCMap.put('Flag_Work_Phone_DNC_Garage__c', true);
	        }
	        if (2 == loc && null != rec && 'true' == rec) {
	            valueDNCMap.put('Flag_Mobile_Phone_DNC__c', true);
	        }
	        if (3 == loc && null != rec && 'true' == rec) {
	            valueDNCMap.put('Flag_Home_Phone_DNC_BillTo__c', true);
	        }
	        if (4 == loc && null != rec && 'true' == rec) {
	            valueDNCMap.put('Flag_Work_Phone_DNC_BillTo__c', true);
	        }
            loc++;
       	}
     	
		Test.stopTest();
    }
    
    
    static testMethod void sendEmailTest() {
		Test.startTest();
		UC_CeaseAndDeaseFlowUtil.sendEmail('mchinnappan@salesforce.com', 'SUBJECT', 'BODY of the email');
		Test.stopTest();
    }
    
    
    static testMethod void valueMapTest() {
		Test.startTest();
		
		Map<String,Boolean> valueDNCMap = new Map<String,Boolean>();
		valueDNCMap.put('Flag_Home_Phone_DNC_Garage__c', false);
		
		System.assertEquals(valueDNCMap.get('Flag_Home_Phone_DNC_Garage__c'), false);
		
		Test.stopTest(); 
    }
    
    
    static testMethod void insertActivityCodeInTaskTest() {
     
    	Test.startTest();
       	String facNumber = '123testfac';
       	Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
       	Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);
      
      	String whatId = null;
      
      	if (null == whatId) {
	    	Task newTask = new Task(
	        			Subject =  'codeDescription',
	                  	WhatId = whatId,
	                  	Financial_Account__c =  dbFinancialAccount.Id,
	                  	Financial_Account_Number__c = dbFinancialAccount.Financial_Account_Number__c,
	                  	Status = 'statusStr',
	                  	Collection_Activity_Code__c = 'activityCode',
	                  	Description = 'taskDesc',
	                  	ActivityDate = Date.today()
	             		);
	    	insert newTask; 
	     
	    	System.assertEquals(newTask.whatId, null );
     	}
     
     
      	UC_CeaseAndDeaseFlowUtil.insertActivityCodeInTask(
       				dbFinancialAccount.Financial_Account_Number__c,
       				dbFinancialAccount.Id,
       				'activityCode',  'codeDescription',  dbFinancialAccount.Id,
               		'status', 'taskDesc');
     
       	Test.stopTest();
    }
    
    private static Financial_Account__c coBorrowerTest( String facNumber) {
    	Test.startTest(); 
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = facNumber);
        insert financialAccount;
        
        String borrowerPosition = 'Primary';
        List <Financial_Account_Customer__c>  facs = UC_CeaseAndDeaseFlowUtil.getFinancialAccountCustomers(financialAccount.id);
        Map<String,Boolean> valueDNCMap = null;
        for (Financial_Account_Customer__c fac : facs) {
        	if (fac.Borrower_Position__c != borrowerPosition) {
         		System.assertNotEquals(fac.Borrower_Position__c, borrowerPosition);
         	} else {
         		valueDNCMap = new Map<String,Boolean>();
         	}
         	System.assertEquals(fac.Borrower_Position__c, null);
        }
        
        Test.stopTest();  
               
    	return financialAccount;
    }
   
   
     private static Financial_Account__c insertFinancialAccount( String facNumber) {
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = facNumber);
        insert financialAccount;       
        return financialAccount;
    }
    
    private static Financial_Account__c getFinancialAccount(String id) {
		Financial_Account__c financialAccount = [ SELECT id, Financial_Account_Number__c FROM Financial_Account__c WHERE id=:id];
		return financialAccount;
    }
}