AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Identity_Theft_Indicator_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Identity Theft Indicator Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_CommunitiesIntermediateController.cls
global with sharing class TFSC_CommunitiesIntermediateController {

    public String defaultPage {
        get {             
            if (TFSC_CommunitySettings.PERSONID != null ) {
                for(Financial_Account_Customer__c fac : TFSC_CommunitySettings.findFinancialAccountCustomersForWeblogin()) {
                    if (fac.Identity_Theft_Indicator_Flag__c){
                        return TFSC_CommunitySettings.ID_THEFT_FLAG_ERROR_URL;                        
                    }
                }
            }
            
            return TFSC_CommunitySettings.DEFAULT_PAGE;
        }
    }
    
     public String getCustomSettingsDefaultPage() {
          return TFSC_CommunitySettings.DEFAULT_PAGE;
     }

    global TFSC_CommunitiesIntermediateController() {

    }

    @RemoteAction
    global static void noop() {
        return;
    }

}