AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/objects/TFS_Activity__c.object
<CustomObject>
    <description>Contains important data on customer activity</description>
    <fields>
        <fullName>Action__c</fullName>
        <description>This is the Action field that controls the Action Category Topic combination been leveraged for TFS</description>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Edit Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call to Action</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Case Object</description>
        <inlineHelpText>Lookup to Case Object</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>This is the Category field that is used the ACT combination been leveraged for TFS</description>
        <label>Category</label>
        <picklist>
            <controllingField>Action__c</controllingField>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Modifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Service Technical Difficulty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1099</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excess Wear &amp; Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Profile Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Profile Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maturity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TFS/LFS Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loyalty/Retention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account Customer</label>
        <referenceTo>Financial_Account_Customer__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>Payment Amount from the Western Union Payment Screen</description>
        <inlineHelpText>Payment Amount from the Western Union Payment Screen</inlineHelpText>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <description>This is the Topic field that is used the ACT combination been leveraged for TFS</description>
        <label>Topic</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Affiliate Marketing Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comm Preference Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit App/Rpt Flag Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telemarketing Flag Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Request Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1099</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party Flag Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account History Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address/Phone/Name Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address/Phone/Name Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Privacy Election Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Letter Flag Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autocheque Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autocheque Enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autocheque Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Statement Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Bank Account Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Consents Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Email Address Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Password Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Payment Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Registration Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P User ID Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call From Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misapplied Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_UCCaseTriggerHandler.cls
public with sharing class TFSC_UCCaseTriggerHandler  implements TFSC_TriggerDispatcher.Handler {


    // trigger created to handle Misapplied Payments in UC Console
    public static boolean alreadyProcessed = false;
    public static boolean alreadyAssigned = false;
    public  Map<Id, Id> facMap = new Map<Id,Id>();
    
    public void handle(){
        system.debug('+++ TFSC_UCCaseTriggerHandler - alreadyProcessed: ' + alreadyProcessed);
        if (!alreadyProcessed ) {
            handleMisappliedPayments(trigger.new);
            alreadyProcessed = true;
        }

    }
    

    public void handleMisappliedPayments(List<Case> caseList) {
    
            
            
            Set<Id> caseIds = new Set<Id>();
            Set<Id> faIds = new Set<Id>();
            for (Case c : caseList) {
                if (c.status == 'Resolved' || c.Service_Request_Type__c != 'Misapplied Payment')
                    continue;
                    
                Case oldCase;
                if (trigger.isUpdate)
                     oldCase = (Case) trigger.oldMap.get(c.Id);
                else
                     oldCase = new Case();
    
                if (oldCase.description != c.description ||
                    oldCase.Effective_Date__c != c.Effective_Date__c || 
                    oldCase.Payment_Amount__c != c.Payment_Amount__c ||
                    oldCase.Effective_Date1__c != c.Effective_Date1__c ||
                    oldCase.Payment_Amount1__c != c.Payment_Amount1__c ||
                    oldCase.Effective_Date2__c != c.Effective_Date2__c ||
                    oldCase.Payment_Amount2__c != c.Payment_Amount2__c) {
                
                        caseIds.add(c.Id);
                        faIds.add(c.Acct_Misapplied_To__c);
                        faIds.add(c.Apply_to_Account1__c);
                        faIds.add(c.Apply_to_Account2__c);
                    }
            }
            if (caseIds.size() == 0)
                return;
             
            faIds.remove(null); 

            // get primary borrowers for the FAs
            
            for (Financial_Account_Customer__c fac : [select Id, Financial_Account__c from Financial_Account_Customer__c where Financial_Account__c in : faIds
                        and Customer_Role_Type__c = '0-Primary Borrower' and Borrower_Status__c = 'Active' ]) {
                  facMap.put(fac.Financial_Account__c, fac.Id);
                 
            }
            // build map of cases and activities
            
            
            Map<Id, List<TFS_Activity__c>> caseActivityMap = new Map<Id, List<TFS_Activity__c>>();
            /* W-001386- Always create new Activity
            for (TFS_Activity__c act :[select Id, case__c, description__c, financial_account__c, financial_account_customer__c from TFS_Activity__c where case__c in :caseIds]) {
            
                List<TFS_Activity__c> tempActList = caseActivityMap.get(act.case__c);
                if (tempActList == null)
                    tempActList = new List<TFS_Activity__c>();
                tempActList.add(act);
                caseActivityMap.put(act.case__c,tempActList.clone());
            }         
            // determine if adding or updating activities
            */
            
            List<TFS_Activity__c> newActivities = new List<TFS_Activity__c>();
            List<TFS_Activity__c> activitiesToUpdate = new List<TFS_Activity__c>();
            
            
            for (Case c : caseList) {
                List<TFS_Activity__c> caseActivities = new List<TFS_Activity__c> ();
                caseActivities = caseActivityMap.get(c.Id);

                //No need to update activities
                //if (caseActivities == null)
                    newActivities.addAll(createActivities(c));
                //else {
                //    activitiesToUpdate.addAll(updateActivities(c, caseActivities));
                    
                //}
                    
                
            }

                if (newActivities.size() > 0)
                        insert newActivities;
                if (activitiesToUpdate.size() > 0)
                         update activitiesToUpdate;
                        
            
    }                   
        
    public List<TFS_Activity__c> createActivities(Case c) { 
    
        Id facId;
        List<TFS_Activity__c> newActivities = new List<TFS_Activity__c>();  
        if (c.action__c == 'Start Process' && c.Category__c == 'Payments' && c.Service_Request_Type__c == 'Misapplied Payment'
                    && c.Description != null  && c.Effective_Date__c != null && c.Payment_Amount__c!= null
                    && c.Effective_Date1__c != null && c.Payment_Amount1__c!= null
                    ) {
              try {
                 facId = this.facMap.get(c.Acct_Misapplied_To__c);
              }
              catch(exception e) {
                facId = null;
              }
              newActivities.add (new TFS_Activity__c(
                 case__c = c.Id,
                 action__c = c.action__c,
                 category__c = c.Category__c,
                 topic__c = c.service_request_type__c,
                 
                 financial_account__c = c.Acct_Misapplied_To__c,
                 financial_account_customer__c = facId,
                 
                 description__c = c.description + '\nEffective Date: ' + c.Effective_Date__c.format() + '\nPayment Amount: ' + 
                      string.valueOf(c.Payment_Amount__c)  
                 ));            

              try {
                 facId = facMap.get(c.Apply_to_Account1__c);
              }
              catch(exception e) {
                facId = null;
              }                     
              newActivities.add (new TFS_Activity__c(
                 case__c = c.Id,
                 action__c = c.action__c,
                 category__c = c.Category__c,
                 topic__c = c.service_request_type__c,
                 
                 financial_account__c = c.Apply_to_Account1__c,
                 financial_account_customer__c = facId,
                 description__c = c.description + '\nEffective Date: ' + c.Effective_Date1__c.format() + '\nPayment Amount: ' + 
                      string.valueOf(c.Payment_Amount1__c)  
                 ));            

              try {
                 facId = facMap.get(c.Apply_to_Account2__c);
              }
              catch(exception e) {
                facId = null;
              }                     
              if(c.Apply_to_Account2__c != null) {          
                  newActivities.add (new TFS_Activity__c(
                     case__c = c.Id,
                     action__c = c.action__c,
                     category__c = c.Category__c,
                     topic__c = c.service_request_type__c,
                     
                     financial_account__c = c.Apply_to_Account2__c,
                     financial_account_customer__c = facId,
                     
                     description__c = c.description + '\nEffective Date: ' + c.Effective_Date2__c.format() + '\nPayment Amount: ' + 
                          string.valueOf(c.Payment_Amount2__c)  
                     ));            
              }     
            }   
            return newActivities;
            
        }   
    
    public List<TFS_Activity__c> updateActivities(Case c, List<TFS_Activity__c> activityList) {
        
        List<TFS_Activity__c> updatedActivities = new List<TFS_Activity__c>();  
        //append description, effective date, payment amount

        for (TFS_Activity__c act : activityList) {
        //system.debug('++++ processing activity: ' + act.name);
            Case oldCase = (Case) trigger.oldMap.get(act.case__c);  
            
            string updatedDescription = '';
            string activityUpdate = '';
            string overallUpdate = '';
            
            if (oldCase.description != c.description ){
                updatedDescription += '\nDescription: ' + c.description;    // applies to all activities
                
            }
            

        
            if ( c.Acct_Misapplied_To__c == act.financial_account__c) {
                if ( oldCase.Effective_Date__c != c.Effective_Date__c){
                    activityUpdate += '\nEffective Date: ' +c.Effective_Date__c.format();
                }
                if ( oldCase.Payment_Amount__c != c.Payment_Amount__c){
                    activityUpdate += '\nPayment Amount: ' + string.valueOf(c.Payment_Amount__c)  ;
                }
                overallUpdate = updatedDescription + activityUpdate;

                if (overallUpdate != '') {
                    overallUpdate = '\n\n*** Updated: ' + datetime.now().format() + ' ***' + overallUpdate;
                    act.description__c += overallUpdate;
                }
                    
            }
            
            activityUpdate = '';
            overallUpdate = '';
            if ( c.Apply_to_Account1__c == act.financial_account__c) {
                if ( oldCase.Effective_Date1__c != c.Effective_Date1__c){
                    activityUpdate += '\nEffective Date: ' +c.Effective_Date1__c.format();
                }
                if ( oldCase.Payment_Amount1__c != c.Payment_Amount1__c){
                    activityUpdate += '\nPayment Amount: ' + string.valueOf(c.Payment_Amount1__c)  ;
                }
                overallUpdate = updatedDescription + activityUpdate;

                if (overallUpdate != '') {
                    overallUpdate = '\n\n*** Updated: ' + datetime.now().format() +  ' ***' + overallUpdate;
                    act.description__c += overallUpdate;
                }
                    
            }
            
            activityUpdate = '';
            overallUpdate = '';
            if ( c.Apply_to_Account2__c == act.financial_account__c) {
                if ( oldCase.Effective_Date2__c != c.Effective_Date2__c){
                    activityUpdate += '\nEffective Date: ' +c.Effective_Date2__c.format();
                }
                if ( oldCase.Payment_Amount2__c != c.Payment_Amount2__c){
                    activityUpdate += '\nPayment Amount: ' + string.valueOf(c.Payment_Amount2__c)  ;
                }
                overallUpdate = updatedDescription + activityUpdate;

                if (overallUpdate != '') {
                    overallUpdate = '\n\n*** Updated: ' + datetime.now().format() +  ' ***' + overallUpdate;
                    act.description__c += overallUpdate;
                }
                    
            }
            updatedActivities.add(act);
        }
        return updatedActivities;
    }
    

}