AUGREL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

AUGREL/src/objects/TFS_Activity__c.object
<CustomObject>
    <description>Contains important data on customer activity</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_User_Group__c</fullName>
        <label>Service Request User Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Created_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Source Created Date</label>
        <type>DateTime</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_MostRecentDDLYNote.cls
/*
#########################################################################################

Project Name..........: TFS AB

File..................: <TFSC_MostRecentDDLYNote> 

Version...............: <1.0>

Created by............: INFOSYS TECHNOLOGIES

Created Date..........: <14/12/2015> 

Last Modified by......: <ARJUN SONI>

Last Modified Date....: <16/12/2015 >

Description...........: <This Class has been written for feching the description field from standard object CASE.>
##########################################################################################
*/
public with sharing class TFSC_MostRecentDDLYNote 
{
  
    @InvocableMethod(label='Most recent DDLY note' description='Returns the Most recent record-Description of PayOff SR')
    
    public static List<String> MostRecentRecorDescriptionOfPayOffSR(List<String> faIds)
        {
        List<String> DescriptionList=new List<String>();
        if(faIds!=null && faIDs.size()>0){           
             List<Case> serviceRequests =new List<Case>();
             List<TFS_activity__c> tfsActivityList=new List<TFS_activity__c> ();
             serviceRequests =[Select Description,Source_Created_Date__c from Case where Service_Request_Type__c='Payoff Request' AND Service_Request_User_Group__c='Dealer Daily System' AND Financial_Account__c in :faIds order by Source_Created_Date__c desc limit 1];
             tfsActivityList=[Select Description__c,Source_Created_Date__c from TFS_activity__c where Service_Request_Type__c='Payoff Request' AND Service_Request_User_Group__c='Dealer Daily System' AND Financial_Account__c in :faIds order by Source_Created_Date__c desc limit 1];
             if(serviceRequests.size()>0 && tfsActivityList.size()>0){
                if(serviceRequests[0].Source_Created_Date__c > tfsActivityList[0].Source_Created_Date__c)
                    DescriptionList.add(serviceRequests[0].description );
                else
                    DescriptionList.add(tfsActivityList[0].Description__c );
                }
             else if(serviceRequests.size()==0 && tfsActivityList.size()>0){
                DescriptionList.add(tfsActivityList[0].Description__c );
                }
             else if(serviceRequests.size()>0 && tfsActivityList.size()==0){
                DescriptionList.add(serviceRequests[0].description );
                }             
            }
        return DescriptionList;  
        }
}