AUGREL/src/objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Field_Junction__c.object
<CustomObject>
    <description>Junction object linking Forms with their Form Fields and supporting re-use of fields across forms.</description>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form-Field Junction</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Form-Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Field Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_WebServiceExecutorTest.cls
@isTest
private class Forms_WebServiceExecutorTest
{   
    //Muthu
    static void createrecords(String formNumber){

        Form__c form = Forms_TestDataUtil.insertForm(formNumber);
        Forms_TestDataUtil.insertFormFieldsForRequest();//TC_154,TC_155,TC_156
        Forms_TestDataUtil.insertFormFieldsForALFAandSFDC();
        Forms_TestDataUtil.insertEndPoints();
        
    }

    static testMethod void executeWebServiceSuccess() {
        createrecords('2000');
        //recordsCreation('success');
        try{
            Map<String,String> inputMap  = new Map<String,String>();
            inputMap.put('accountnumber', '70000012345');
            inputMap.put('formnumber', '2000');
            List<Form_Field_Junction__c> formFieldjunctionList = new Forms_DataSelector().getServiceList(inputMap.get('formnumber'));
            new Forms_WebServiceExecutor().executeWebServices(inputMap,formFieldJunctionList);//TC_151
            system.debug('+++In try++++ inputMap : '+inputMap.size());
            system.assertEquals('70000012345', inputMap.get('accountnumber'));
        } catch(Exception e){
            system.debug('Error::'+e.getMessage());
        }
    }
    //method for testing the service error exception
      static testMethod void executeWebService_serviceError() {
        createrecords('5001');
        try{
            Map<String,String> inputMap  = new Map<String,String>();
            inputMap.put('accountnumber', '70000012345');
            inputMap.put('formnumber', '5001');
            List<Form_Field_Junction__c> formFieldjunctionList = new Forms_DataSelector().getServiceList(inputMap.get('formnumber'));
            new Forms_WebServiceExecutor().executeWebServices(inputMap,formFieldJunctionList);//TC_152
          
            system.assertEquals('70000012345', inputMap.get('accountnumber'));
        } catch(Exception e){
            system.debug('Error::'+e.getMessage());
        }
        
    }
    
  //method for testing the internal error exception
      static testMethod void executeWebService_internalError() {
        createrecords('5002');
        try{
        Map<String,String> inputMap  = new Map<String,String>();
        inputMap.put('accountnumber', '70000012345');
        inputMap.put('formnumber', '5002');
        List<Form_Field_Junction__c> formFieldjunctionList = new Forms_DataSelector().getServiceList(inputMap.get('formnumber'));//TC_153
        new Forms_WebServiceExecutor().executeWebServices(inputMap,formFieldJunctionList);
        system.assertEquals('70000012345', inputMap.get('accountnumber'));
        } catch(Exception e){
            system.debug('Error::'+e.getMessage());
        }
           
    }

    
 
}