AUGREL/src/objects/Form_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreationDate__c</fullName>
        <label>CreationDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Name__c</fullName>
        <label>Device Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_Name__c</fullName>
        <label>Dispatch Name</label>
        <picklist>
            <picklistValues>
                <fullName>Print Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Form_Number__c</fullName>
        <label>Form Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Recipient</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestID__c</fullName>
        <label>RequestID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <label>SourceSystem</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Form Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Form Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Form_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>FormAttributeKey__c</fullName>
        <label>Form Attribute Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormAttributeValue__c</fullName>
        <label>Form Attribute Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Form Request Line Item</label>
    <nameField>
        <displayFormat>FRLI-{0000}</displayFormat>
        <label>Form Request Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Request Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/objects/Forms_Validation_Result__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>Error Message</label>
        <length>32767</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The field to show successful or failure validation.</description>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Forms Validation Result</label>
    <nameField>
        <displayFormat>FVE-{0000}</displayFormat>
        <label>Forms Validation Error Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Validation Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/Forms_AdverseActionDemoController.cls
public Class Forms_AdverseActionDemoController{

Public static Form_Request__c frmReq;

public List<SelectOption> dispatchSelectOptions{get;set;}

    public Forms_AdverseActionDemoController() {
        sourceSystem = 'SFDC';
        populateDispatchSelectOptions();
       
    }

public String formNumber{get;set;}
public String creationDate{get;set;}
public String accountNumber{get;set;}
public String deviceName{get;set;}
public List<String> dispatchName{get;set;}
public String sourceSystem{get;set;}
public String requestId{get;set;}
public String recipient{get;set;}
String dispatchNm;

   public PageReference submit(){ 
      try{
         frmReq  = new Form_Request__c ();
         frmReq.Form_Number__c = formNumber;
         frmReq.Account_Number__c = accountNumber;
    
         if(creationDate!=null && creationDate!=''){
           frmReq.CreationDate__c= Date.valueof(creationDate);
         }     
         frmReq.Device_Name__c = deviceName;
         if(dispatchName.size()>0){
            dispatchNm=String.join(dispatchName,';');
         }
         frmReq.Dispatch_Name__c =dispatchNm;
         frmReq.SourceSystem__c = sourceSystem;
         frmReq.RequestID__c =requestId;
         if(recipient!=null && recipient!=''){
           frmReq.Recipient__c = recipient;
         }    
    
         
        
     invokeDAE();       
    
    
    }Catch(Exception e){
      ApexPages.Message apexMseg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()) ;
      ApexPages.addMessage(apexMseg);
      return null;
    }
    return null;
  }
 
  
 private static void invokeDAE(){
    Forms_RequestProcesser reqprocess = new Forms_RequestProcesser();
    Forms_Validation_Result__c validationresult = new Forms_Validation_Result__c();
    List<Form_Request_Line_Item__c> frmReqLineItems = new List<Form_Request_Line_Item__c>();
    Form_Request_Line_Item__c li = new Form_Request_Line_Item__c();
    li.FormAttributeKey__c='tmpkey####';
	li.FormAttributeValue__c = '1111';
    frmReqLineItems.add(li);
     
    validationresult = reqprocess.processInternalFormRequest(frmReq,frmReqLineItems);
     
     if(validationresult.Status__c=='Success'){
        ApexPages.Message apexMsg = new ApexPages.Message(ApexPages.Severity.Info,'Form Submitted Successfully') ;
        ApexPages.addMessage(apexMsg);
     }else{
        ApexPages.Message apexMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR,validationresult.ErrorMessage__c);
        ApexPages.addMessage(apexMsg1);
     }
 }
private void populateDispatchSelectOptions() {
        dispatchSelectOptions = new List<SelectOption>();             
         dispatchSelectOptions.add( new SelectOption('Print Local', 'Print Local') );
         dispatchSelectOptions.add( new SelectOption('Network Print', 'Network Print') );
         dispatchSelectOptions.add( new SelectOption('Email', 'Email') );
         dispatchSelectOptions.add( new SelectOption('Fax', 'Fax') );
        }       
    
}