AUGREL/src/objects/TFS_Activity__c.object
<CustomObject>
    <description>Contains important data on customer activity</description>
    <fields>
        <fullName>Case_Action__c</fullName>
        <formula>TEXT(Case__r.Action__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Action</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Category__c</fullName>
        <formula>TEXT(Case__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Topic__c</fullName>
        <formula>TEXT(Case__r.Service_Request_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Topic</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Case Object</description>
        <inlineHelpText>Lookup to Case Object</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AUGREL/src/classes/TFSC_ActivityTriggerAfterHandler.cls
public with sharing class TFSC_ActivityTriggerAfterHandler implements TFSC_TriggerDispatcher.Handler {
	
	/* Handler for TFS_Activity__c after insert */
	
	public void handle(){
		execute(trigger.new);
	}
	
	public void execute(List<TFS_Activity__c> activityList) {

	 //system.debug('++++++TFSC_ActivityTriggerAfterHandler')	;

		Set<Id> caseIds = new Set<Id>();
		for (TFS_Activity__c act : activityList) {
			if (act.case__c != null)
				caseIds.add(act.case__c);
		}
		
		Map<Id, Case> caseMap = new Map<Id,Case> ([select Id, payment_channel__c from case where id in :caseIds]);

		List<case> caseList = new List<case>();
		
		for (TFS_Activity__c act : activityList){
			if (act.case_action__c == 'Start Process' && act.case_category__c == 'Payments' && act.case_Topic__c == 'Refund'
							&& caseMap.get(act.case__c).payment_channel__c == 'WUSP') {

	 //system.debug('++++++ record meets criteria')	;
	 								
				caseList.add(new Case(Id = act.case__c, status = 'Resolved'));					
			}	
		}	
	 //system.debug('++++++ caseList: ' + caseList)	;
		if (caseList.size() > 0)
			update caseList;
	}

}