AUGREL/src/objects/Title_Files__c.object
<CustomObject>
    <description>Title Files are used for attaching files related to Title Cases</description>
    <fields>
        <fullName>Attachment__c</fullName>
        <description>Field to reference actual Attachment ID from the Standard Notes &amp; Attachments.</description>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>MD Relationship to Cases (specifically Title Cases)</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Title_Files</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Printed_Date__c</fullName>
        <description>Date in which this documented was Printed</description>
        <label>Printed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Print Immediately (w/o Title/Lien Release)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Print with Title/Lien Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AUGREL/src/classes/UploadAttachmentController.cls
public class UploadAttachmentController {
    
    private Case orgCase {get;set;} 
    public String fileName {get;set;}
    public Blob fileBody {get;set;}
    public Date strPrintedDate {get;set;}
    public String strStatus {get;set;}
    
    public UploadAttachmentController(ApexPages.StandardController controller) { 
        this.orgCase = (Case)controller.getRecord();
    }   
    
    // creates a new Title_Files__c record
    private Database.SaveResult saveCustomAttachment() {
        Title_Files__c obj = new Title_Files__c();
        obj.case__c = orgCase.Id; 
        obj.printed_date__c = strPrintedDate;
        obj.status__c = strStatus;
        // fill out cust obj fields
        return Database.insert(obj);
    }
    
    // create an actual Attachment record with the Title_Files__c as parent
    private Database.SaveResult saveStandardAttachment(Id parentId) {
        Database.SaveResult result;       
        Attachment attachment = new Attachment();
        attachment.body = this.fileBody;
        attachment.name = this.fileName;
        attachment.parentId = parentId;
        // insert the attachment
        result = Database.insert(attachment);
        // reset the file for the view state
        fileBody = Blob.valueOf(' ');
        return result;
    }
    
    /**
    * Upload process is:
    *  1. Insert new Title_Files__c record
    *  2. Insert new Attachment with the new Title_Files__c record as parent
    *  3. Update the Title_Files__c record with the ID of the new Attachment
    **/
    public PageReference processUpload() {
        try {
            Database.SaveResult customAttachmentResult = saveCustomAttachment();
        
            if (customAttachmentResult == null || !customAttachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                  'Could not save attachment.'));
                return null;
            }
        
            Database.SaveResult attachmentResult = saveStandardAttachment(customAttachmentResult.getId());
        
            if (attachmentResult == null || !attachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                  'Could not save attachment.'));            
                return null;
            } else {
                // update the custom attachment record with some attachment info
                Title_Files__c customAttachment = [select id from Title_Files__c where id = :customAttachmentResult.getId()];
                customAttachment.name = this.fileName;
                customAttachment.Attachment__c = attachmentResult.getId();
                update customAttachment;
            }
        
        } catch (Exception e) {
            ApexPages.AddMessages(e);
            return null;
        }
        
        return new PageReference('/'+orgCase.Id);
    }
    
    public PageReference back() {
        return new PageReference('/'+orgCase.Id);
    }     

}